package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckFurryPack extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("Personals ad: Seeking a female who doesn't mind ____, might also be willing to try a male if they're ____.", true),
		new Card("I tell everyone I'm not a furry, but I've drawn a lot of ____.", true),
		new Card("My original species combines ____ and ____. It's called ____.", true),
		new Card("____. And now I'm bleeding.", true),
		new Card("Suck my ____.", true),
		new Card("I also take ____ as payment for commissions.", true),
		new Card("____ looks pretty in all the art, but have you seen one in real life?", true),
		new Card("Don't knock ____ until you've tried it.", true),
		new Card("Once I started roleplaying ____, it was all downhill from there.", true),
		new Card("____ are so goddamn cool.", true),
		new Card("____, by Bad Dragon™.", true),
		new Card("No, look, you don't understand. I REALLY like ____.", true),
		new Card("I don't think my parents will ever accept that the real me is ____.", true),
		new Card("You can try to justify ____ all you want, but you don't have to be ____ to realize it's just plain wrong.", true),
		new Card("I've been waiting all year for ____.", true),
		new Card("I can't wait to meet up with my internet friends for ____.", true),
		new Card("Most cats are ____.", true),
		new Card("Taking pride in one's collection of ____.", true),
		new Card("Did you hear about the guy that smuggled ____ into the hotel?", true),
		new Card("The panel I'm looking forward to most at AC this year is...", true),
		new Card("My Original Character's name is ____.", true),
		new Card("My secret tumblr account where I post nothing but ____.", true),
		new Card("Only my internet friends know that I fantasize about ____.", true),
		new Card("Everyone really just goes to the cons for ____.", true),
		new Card("It all started with ____.", true),
		new Card("I'll roleplay ____, you can be ____.", true),
		new Card("I'm no longer allowed near ____ after the incident with ____.", true),
		new Card("I've been into ____ since before I hit puberty, I just didn't know what it meant.", true),
		new Card("Realizing, too late, the implications of your interest in ____ as a child.", true),
		new Card("Whoa, I might fantasize about ____, but I'd never actually go that far in real life.", true),
		new Card("I realized they were a furry when they mentioned ____.", true),
		new Card("Everyone on this site has such strong opinions about ____.", true),
		new Card("My landlord had a lot of uncomfortable questions for me when when he found ____ in my bedroom while I was at work.", true),
		new Card("I'm not even aroused by normal porn anymore, I can only get off to ____ or ____.", true),
		new Card("____? Oh, yeah, I could get my mouth around that.", true),
		new Card("What wouldn't I fuck?", true),
		new Card("When I thought I couldn't go any lower, I realized I would probably fuck ____.", true),
		new Card("I knew my boyfriend was a keeper when he said he'd try ____, just for me.", true),
		new Card("Fuck ____, get ____.", true),
		new Card("I would bend over for ____.", true),
		new Card("I think having horns would make ____ complicated.", true),
		new Card("In my past life, I was ____.", true),
		new Card("____ is my spirit animal.", true),
		new Card("____. This is what my life has come to.", true),
		new Card("I'm not even sad that I devote at least six hours of each day to ____.", true),
		new Card("I never felt more accomplished than when I realized I could fit ____ into my ass.", true),
		new Card("Yeah, I know I have a lot of ____ in my favorites, but I'm just here for the art.", true),
		new Card("I'm not a ", true),
		new Card("Okay, ____? Pretty much the cutest thing ever.", true),
		new Card("____. Yeah, that's a pretty interesting way to die.", true),
		new Card("I didn't believe the rumors about ____, until I saw the videos.", true),
		new Card("I knew I needed to leave the fandom when I realized I was ____.", true),
		new Card("After being a furry for so long, I can never see ____ without getting a little aroused.", true),
		new Card("It's really hard not to laugh at ____.", true),
		new Card("If my parents ever found ____, I'd probably be disowned.", true),
		new Card("____ ruined the fandom.", true),
		new Card("The most recent item in my search history.", true),
		new Card("Is it weird that I want to rub my face on ____?", true),
		new Card("____? Oh murr.", true),
		new Card("I never thought I'd be comfortable with ____, but now it's pretty much the only thing I masturbate to.", true),
		new Card("My next fursuit will have ____.", true),
		new Card("I'm writing a porn comic about ____ and ____. ", true),
		new Card("I tell everyone that I make my money off ", true),
		new Card("Oh, you're an artist? Could you draw ____ for me?", true),
		new Card("Everyone thinks they're so great, but the only thing they're good at drawing is ____.", true),
		new Card("They're just going to spend all that money on ____.", true),
		new Card("While everyone else seems to have a deep, instinctual fear of ____, it just turns me on.", true),
		new Card("Lying about having ____ to get donations, which you spend on ____.", true),
		new Card("It's not bestiality, it's ____.", true),
		new Card("Everyone thinks that because I'm a furry, I'm into ____. Unfortunately, they're right.", true),
		new Card("I'm only gay for ____.", true),
		new Card("Excuse you, I'm a were-____.", true),
		new Card("If you like it, then you should put ____ on it.", true),
		new Card("My girlfriend won't let me do ____.", true),
		new Card("The most pleasant surprise I've had this year.", true),
		new Card("I knew I had a problem when I had to sell ____ to pay for ____.", true),
		new Card("I'm about 50% ____.", true),
		new Card("____: Horrible tragedy, or sexual opportunity?", true),
		new Card("It's a little worrying that I have to compare the size of ____ to beverage containers.", true),
		new Card("Hey, you guys wanna come back to my place? I've got ____ and ____.", true),
		new Card("Jizzing all over ____.", true),
		new Card("It's just that much creepier when 40-year-old men are into ____.", true),
		new Card("____ is no substitute for social skills, but it's a start.", true),
		new Card("The real reason I got into the fandom? ____.", true),
		new Card("____ are definitely the new huskies.", true),
		new Card("I remember when ____ was just getting started.", true),
		new Card("When no one else is around, sometimes I consider doing things with ____.", true),
		new Card("Actually coming inside ____.", true),
		new Card("I don't know how we got on the subject of dragon cocks, but it probably started with ____.", true),
		new Card("____ is a shining example of what those with autism can really do.", true),
		new Card("It is my dream to be covered with ____.", true),
		new Card("____ fucking ____. Now that's hot.", true),
		new Card("Would you rather suck ____, or get dicked by ____?", true),
		new Card("It never fails to liven up the workplace when you ask your coworkers if they'd rather have sex with ____ or ____.", true),
		new Card("HELLO FURRIEND, HOWL ARE YOU DOING?", true),
		new Card("What are the two worst cards in your hand right now?", true),
		new Card("Nobody believes me when I tell that one story about walking in on ____.", true),
		new Card("You don't know who ____ is? They're the one that draws ____.", true),
		new Card("You sometimes wish you'd encounter ____ while all alone, in the woods. With a bottle of lube.", true),
		new Card("I used to avoid talking about ____, but now it's just a part of normal conversation with my friends.", true),
	}, responseCards = new Card[]{
		new Card("Dragon dildos.", false),
		new Card("Adam Wan.", false),
		new Card("Non-consensual sex with Zaush.", false),
		new Card("My tailhole.", false),
		new Card("Adoptables with visible genitalia.", false),
		new Card("An embarrassingly long F-List profile.", false),
		new Card("Catching STDs at conventions.", false),
		new Card("Fursuit adventures.", false),
		new Card("A semen-stained fursuit.", false),
		new Card("Fake furry girls.", false),
		new Card("That one straight guy at the party.", false),
		new Card("An apartment full of internet-obsessed losers.", false),
		new Card("People who cosplay at furry conventions.", false),
		new Card("Fursuiters at anime conventions.", false),
		new Card("Embarrassing craigslist ads.", false),
		new Card("Pounced.org.", false),
		new Card("A large, flared Chance.", false),
		new Card("Stretching your anus in preparation for horse cock.", false),
		new Card("A hermaphrodite foxtaur.", false),
		new Card("Babyfurs.", false),
		new Card("Uncomfortably attractive animals.", false),
		new Card("Confusing feelings about cartoon characters.", false),
		new Card("Krystal, the fox.", false),
		new Card("Bowser's sweaty balls.", false),
		new Card("A furpile.", false),
		new Card("The stench of half a dozen unwashed bronies.", false),
		new Card("Intimacy with the family dog.", false),
		new Card("Horses.", false),
		new Card("Fursecution.", false),
		new Card("Chakats.", false),
		new Card("Otherkin.", false),
		new Card("Heated debates about human genitalia versus animal genitalia.", false),
		new Card("Taking the knot.", false),
		new Card("Really, really liking Disney's Robin Hood.", false),
		new Card("Applying your obscure, unrealistic fetishes to 90's cartoon characters.", false),
		new Card("The texture and color of raw meat.", false),
		new Card("An oversized clitoris that acts as a functional penis.", false),
		new Card("A hermaphrodite snow leopard.", false),
		new Card("Drawing furry porn.", false),
		new Card("Lovingly rendered dragon anus.", false),
		new Card("Cloaca.", false),
		new Card("Animal genitalia.", false),
		new Card("Motherfucking wolves.", false),
		new Card("Christian furries.", false),
		new Card("Barbed penises.", false),
		new Card("Two knots.", false),
		new Card("A really attractive wolf.", false),
		new Card("A slutty gay fox.", false),
		new Card("A surprisingly attractive anteater.", false),
		new Card("FUCK YOU, I'M A DRAGON.", false),
		new Card("Tumbles, the Stair Dragon.", false),
		new Card("Furry Weekend Atlanta.", false),
		new Card("Further Confusion.", false),
		new Card("AnthroCon.", false),
		new Card("Literally a bucket of semen.", false),
		new Card("Sexual interest in pretty much anything with a hole.", false),
		new Card("Attraction to pretty much anything with a penis.", false),
		new Card("Transformation porn.", false),
		new Card("Anatomically incorrect genitalia.", false),
		new Card("When you catch yourself glancing at the crotches of animated characters.", false),
		new Card("Belly rubs leading to awkward boners.", false),
		new Card("Scritches.", false),
		new Card("Lifting your tail.", false),
		new Card("Experimenting with fisting.", false),
		new Card("Bad decisions.", false),
		new Card("A little bitch.", false),
		new Card("A lime Citra.", false),
		new Card("Sergals.", false),
		new Card("An autistic knife fight.", false),
		new Card("The noises red pandas make during sex.", false),
		new Card("About 16 ounces of horse semen.", false),
		new Card("Dog cum.", false),
		new Card("Oral knotting.", false),
		new Card("Leaving your orifices bloody and sore.", false),
		new Card("Rubbing peanut butter on your genitals.", false),
		new Card("Bad Dragon&trade; cumlube.", false),
		new Card("Piss.", false),
		new Card("Smells.", false),
		new Card("When ", false),
		new Card("Forgetting which set of fursuit paws you use for handjobs.", false),
		new Card("A strategically placed hole.", false),
		new Card("Shitting on my face.", false),
		new Card("Barking at strangers.", false),
		new Card("Sitting on your face.", false),
		new Card("Spending more money on commissions than food in a given week.", false),
		new Card("A dick so big you have to give it a hugjob.", false),
		new Card("The fine line between feral and outright bestiality.", false),
		new Card("Anal training.", false),
		new Card("Discovering monster porn.", false),
		new Card("Realizing that rimming is pretty cool.", false),
		new Card("Endearing social ineptitude.", false),
		new Card("All this lube.", false),
		new Card("That thing that gives your dick a knot IRL.", false),
		new Card("Gay.", false),
		new Card("Really, truly heterosexual.", false),
		new Card("Drenching your fursuit in Febreeze.", false),
		new Card("That time you let your dog go a little further than just sniffing your crotch.", false),
		new Card("Poodles with afros.", false),
		new Card("Offensively stereotyped African animals.", false),
		new Card("A sassy lioness.", false),
		new Card("Surprise hermaphrodites.", false),
		new Card("Taking special interest in nature documentaries.", false),
		new Card("Becoming a veterinarian for all the wrong reasons.", false),
		new Card("The premise of every furry comic ever.", false),
		new Card("Anal sex you didn't know you wanted.", false),
		new Card("The incredibly satisfying sound it makes when you pull it out.", false),
		new Card("Bear tits.", false),
		new Card("Big cute paws.", false),
		new Card("Paws.", false),
		new Card("Furry porn, shamelessly taped to the walls.", false),
		new Card("Grabby-paws.", false),
		new Card("Masturbating, with claws.", false),
		new Card("Pawing-off.", false),
		new Card("Tail-sex.", false),
		new Card("Mary, the anthro mare.", false),
		new Card("Natascha, the anthro husky.", false),
		new Card("Nipple buffet.", false),
		new Card("Crotch-tits.", false),
		new Card("The tailstar tango.", false),
		new Card("Furries in heat.", false),
		new Card("Fantasizing about sex with just about every monster you encounter in your video game.", false),
		new Card("Impure thoughts about Kobolds.", false),
		new Card("Erotic roleplay.", false),
		new Card("Monsters with bedroom eyes.", false),
		new Card("Accurate avian anatomy.", false),
		new Card("Getting fur stuck in your teeth.", false),
		new Card("Getting feathers stuck in your teeth.", false),
		new Card("Ignoring a person's faults because their character is hot.", false),
		new Card("Discovering that it's never just a big vagina.", false),
		new Card("Dragoneer.", false),
		new Card("A horny dragon.", false),
		new Card("A sexually frustrated griffon.", false),
		new Card("Species stereotypes.", false),
		new Card("HELLO FURRIEND, HOWL ARE YOU DOING.", false),
		new Card("Convention sluts.", false),
		new Card("Horns and hooves.", false),
		new Card("Being 'prison gay.'", false),
		new Card("Microwaving diapers.", false),
		new Card("Adorable dog people.", false),
		new Card("Sexy the Cat.", false),
		new Card("SecondLife.", false),
		new Card("The Gay Yiffy Club.", false),
		new Card("Hyper-endowed squirrels.", false),
		new Card("A spider furry who isn't even into bondage.", false),
		new Card("Being really, really into monsters.", false),
		new Card("Sexual arousal from children's cartoons.", false),
		new Card("No males, no herms, no cuntboys, no shemales, no trannys, no furries, no aliens, no vampires, and no werewolves. ONLY STRAIGHT OR BI HUMAN FEMALES.", false),
		new Card("Overcompensating with a huge horse penis.", false),
		new Card("A fedora enthusiast.", false),
		new Card("A tongue-beast.", false),
		new Card("Frisky tentacles.", false),
		new Card("A very steampunk rat.", false),
		new Card("Canine superiority.", false),
		new Card("Oviposition.", false),
		new Card("Flares.", false),
		new Card("Dogs wearing panties.", false),
		new Card("Monster boys in lingerie.", false),
		new Card("Power bottoms.", false),
		new Card("Sheath licking.", false),
		new Card("Sex with Pok&eacute;mon.", false),
		new Card("Making out with dogs.", false),
		new Card("YouTube videos of horse breeding.", false),
		new Card("Pissing on your significant other to show ownership.", false),
		new Card("Being able to recognize your friends by the scent of their asses.", false),
		new Card("A notebook full of embarrassing niche porn sketches.", false),
		new Card("Cockvore.", false),
		new Card("A prehensile penis.", false),
		new Card("Puns involving the word 'knot.'", false),
		new Card("Jerking off on an unconscious friend's feet.", false),
		new Card("CrusaderCat.", false),
		new Card("Your Character Here.", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Sodomy Dog's Furry Pack";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Furry";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}