package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckGameGrumps extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("Welcome back to ____.", true),
		new Card("Welcome to Sonic Team! We make ____, I think!", true),
		new Card("What am I willing to put up with today?", true),
		new Card("What can be found in Arin's chins?", true),
		new Card("What do Mumbo's magic words mean?", true),
		new Card("What is the boopinest shit?", true),
		new Card("WHAT THE FUCK IS A ____?!", true),
		new Card("What's better than Skyward Sword?", true),
		new Card("What's the real reason Jon left?", true),
		new Card("When I look in the mirror I see ____.", true),
		new Card("Who replaced Jon when he left GameGrumps?", true),
		new Card("Why is Steam Train so controversial?", true),
		new Card("WOOP WOOP WOOP I'M A ____!", true),
		new Card("You know what fan mail makes me the happiest every time I see it? It's the ones where people are like, ", true),
		new Card("You're ruining my integrity! ____ won't hire me now!", true),
		new Card("I've been ____ again!", true),
		new Card("Rolling around at the speed of ____!", true),
		new Card("This time on Guest Grumps, we have ____.", true),
		new Card("Top five games, go! 1? Mega Man X. 2-5? ____.", true),
		new Card("Use your ____!", true),
		new Card("Look at this guy, he's like ____.", true),
		new Card("Look, it's ____!", true),
		new Card("Next time on Game Grumps, ____!", true),
		new Card("Nightshade: The Claws of ____.", true),
		new Card("Number one! With a bullet! Zoom in on the ____!", true),
		new Card("Oh, it's ____!", true),
		new Card("One slice of ____ please.", true),
		new Card("Pikachu, use your ____ attack!", true),
		new Card("Put a hole in that ____!", true),
		new Card("Real talk? ____.", true),
		new Card("Jon's mom called him to tell him about ____.", true),
		new Card("Kirby has two iconic abilities: suck and ____.", true),
		new Card("Listen to the ____ on this shit.", true),
		new Card("Jon believes that the most important part of any video game is ____.", true),
		new Card("Jon can't get enough of ____.", true),
		new Card("Jon can't survive air travel without ____.", true),
		new Card("Jon just wants to touch ____.", true),
		new Card("Is there anything to gain from this?", true),
		new Card("It's no use! Take ____!", true),
		new Card("Jon and Arin suck at ____.", true),
		new Card("Jon and Arin win! They realize ____ is more important.", true),
		new Card("If the ____ wasn't there, I would do. But it's there, so it's not.", true),
		new Card("How many ____ does Mega Man get?", true),
		new Card("How many nose hairs does ____ have?", true),
		new Card("I certainly can't do it without you, and I know you can't do it without ____!", true),
		new Card("I tell you once, I tell you twice! ____ is good for economy!", true),
		new Card("I wanna put my ____ in her!", true),
		new Card("I'm not even SELLING ____!", true),
		new Card("Do you remember the episode where Ash caught a ____?", true),
		new Card("Don't throw ____! It's expensive to somebody!", true),
		new Card("Dude, real talk? ____.", true),
		new Card("Eat your ____, son.", true),
		new Card("Egoraptor's fiancee is actually a ____.", true),
		new Card("Everybody wants to know about me, but they don't know about my ____.", true),
		new Card("Fool me once, I'm mad. Fool me twice? How could you. Fool me three times, you're officially ____.", true),
		new Card("For my first attack, I will juggle ____ to impress you.", true),
		new Card("Fuck, I found a ____.", true),
		new Card("Game Grumps: sponsored by ____.", true),
		new Card("Give ____ a chance! He'll grow on you!", true),
		new Card("____? Ten-outta-ten!", true),
		new Card("____. I AAAAAAIN’T HAVIN’ THAT SHIT!", true),
		new Card("____. It's no use!", true),
		new Card("____. MILLIONS ARE DEAD!!!", true),
		new Card("____. Put that in, Barry.", true),
		new Card("____. This is like one of my Japanese animes!", true),
		new Card("...What the bloody hell are you two talking about?!", true),
		new Card("These new ____ t-shirts are gonna change some lives, Arin.', 0, 1, ", true),
		new Card("You want cheese pizza?", true),
		new Card("And then, as a fuckin' goof, I'd put a hole in ____.", true),
		new Card("And there it was...Kirby had finally met the ____ of the lost city.", true),
		new Card("Arin believes that the most important part of any video game is ____.", true),
		new Card("Arin has an adverse reaction to ____.", true),
		new Card("Barry entertains himself by watching old episodes of ____.", true),
		new Card("Barry, add ____ into the video!", true),
		new Card("Barry, we need a replay on ____.", true),
		new Card("BARRY! SHOW ____ AGAIN!", true),
		new Card("Barry's sheer skill at ____ is unmatched.", true),
		new Card("I don't like the ____ flavor.", true),
		new Card("____ don't even cost this less!", true),
		new Card("____ Grumps!", true),
		new Card("____ has aged really well.", true),
		new Card("____ is GREAT GREAT GREAT!", true),
		new Card("____ is Jon's favorite video game of all time.", true),
		new Card("____ is not Jon's strong suit.", true),
		new Card("____ Train!", true),
		new Card("____ WINS!", true),
		new Card("____: Better than deer shit!", true),
		new Card("Welcome back to ____ ____!", true),
		new Card("Real talk? Is that ____ ____?", true),
		new Card("Look at that ____-ass ____!", true),
		new Card("JON'S ____, SHOW US YOUR ____.", true),
		new Card("The Grumps' latest silly player names are ____ and ____.", true),
		new Card("If you don't know what ____ is, you can't go to ____.", true),
		new Card("In this corner, ____; in the other corner, ____; it's Game Grumps VS!", true),
		new Card("IF I CAN'T BE ____, I SURE AS HELL CAN BE ____!!", true),
		new Card("COME ON AND ____, AND WELCOME TO THE ____!", true),
		new Card("If ____ evolved from ____, why the fuck is there still ____, dude?!", true),
		new Card("____? Pretty smart. ____? Pretty fuckin' smart. ____? FUCKING GENIUS!!!!", true),
	}, responseCards = new Card[]{
		new Card("...Metal Gear?!", false),
		new Card("A humanlike bat with tits.", false),
		new Card("A little dingle-dang.", false),
		new Card("A replay from Barry.", false),
		new Card("A Scottish bloke that talks too fast.", false),
		new Card("A Sonic.", false),
		new Card("A whale making a seal noise.", false),
		new Card("Accidentally resetting a video game.", false),
		new Card("Anne Frank doing a striptease.", false),
		new Card("Arin actually winning a Game Grumps VS.", false),
		new Card("Arin Hanson / Egoraptor.", false),
		new Card("Arin's big floppy penis.", false),
		new Card("Arin's dicksaber.", false),
		new Card("Arin's voice acting.", false),
		new Card("Barry Kramer.", false),
		new Card("Barry's censorship noises.", false),
		new Card("Becoming a vegetarian, then becoming clinically depressed.", false),
		new Card("Being forced to replay the same section of the game over and over.", false),
		new Card("Birdemic.", false),
		new Card("Borderline narcissism.", false),
		new Card("Breaking a basketball net's back board.", false),
		new Card("Breaking into song.", false),
		new Card("Brian / Frank / Steve / Willard / Jonathan / Michael IV / Michael III / Michael Jordan / Scott.", false),
		new Card("Bumping butts.", false),
		new Card("Buying chicken fingers for homeless people.", false),
		new Card("Carefully escorting Anna.", false),
		new Card("Catharsis.", false),
		new Card("Cheese pizza.", false),
		new Card("Chu Chu Rocket.", false),
		new Card("Chulip.", false),
		new Card("Comparing someone to a trainwreck.", false),
		new Card("Completely missing the tutorials and instructions.", false),
		new Card("Cumfaggots.", false),
		new Card("Dan getting some action with one of Egoraptor's action figures.", false),
		new Card("Danny Sexbang.", false),
		new Card("Danny's crippling Skittles addiction.", false),
		new Card("Dipping your balls in the sand.", false),
		new Card("Dixon.", false),
		new Card("Donkey-ass Kong.", false),
		new Card("Drakkhen's realistic fight sequences.", false),
		new Card("Drawing the line in the fucking sand.", false),
		new Card("Eating the Holocaust.", false),
		new Card("Eating your peas.", false),
		new Card("Egofaptor.", false),
		new Card("Ending an episode on 'Heil Hitler!'", false),
		new Card("The eyeless girl demographic.", false),
		new Card("Fast-forwarding.", false),
		new Card("Fighting Iblis for the hundredth time.", false),
		new Card("Fooling me three times.", false),
		new Card("Fuckin' Larry.", false),
		new Card("FUCKING LEGO CARS!!?!", false),
		new Card("Game feel.", false),
		new Card("Game Grumps remixes.", false),
		new Card("Game Grumps VS.", false),
		new Card("Game Grumps.", false),
		new Card("Garshstostoles.", false),
		new Card("GeorgLopez.", false),
		new Card("Getting censored by a stampede of elephants.", false),
		new Card("Getting diddled again.", false),
		new Card("Getting fucking ganked.", false),
		new Card("Getting horribly diarrhea'd on by an owl.", false),
		new Card("Getting killed by a motherfucking paralyzed Taillow.", false),
		new Card("Getting stuck on the ceiling for no explicable reason.", false),
		new Card("Getting violently sick at MAGfest.", false),
		new Card("Goof Troop.", false),
		new Card("Goofy masturbating in the fields.", false),
		new Card("Grade A meat.", false),
		new Card("Grant Kirkhope.", false),
		new Card("Grant Kirkhope’s knackers.", false),
		new Card("GREAT! GREAT! GREAT!", false),
		new Card("Grep.", false),
		new Card("Grumping it.", false),
		new Card("Güf Troop.", false),
		new Card("Half the deal for twice the price!", false),
		new Card("Having a cough that lasts forever.", false),
		new Card("Helicopter tits.", false),
		new Card("Hepatitis Sea.", false),
		new Card("Hitting a Nightshade cartridge with Thor’s Hammer only to break the hammer.", false),
		new Card("Homoerotic subtext between two grown men playing video games.", false),
		new Card("Ice hair.", false),
		new Card("Incriminating footage of Jon.", false),
		new Card("Insta-killing your partner with the Select button.", false),
		new Card("It being no use.", false),
		new Card("Jacques.", false),
		new Card("JonTron.", false),
		new Card("Jon winning. AS USUAL.", false),
		new Card("Jon's soulful singing.", false),
		new Card("Jon/Arin slash fiction.", false),
		new Card("JonTron’s musical theater voice.", false),
		new Card("Js'keep goin'.", false),
		new Card("Killing zombies by typing on a keyboard-gun.", false),
		new Card("Kirby.", false),
		new Card("Kitty Cat Dance Party.", false),
		new Card("Learning that your son is dead, but not caring because you didn't want him anyway.", false),
		new Card("Lemon and Bill.", false),
		new Card("Lightsaber Fightsaber.", false),
		new Card("Mediocrity, as a power.", false),
		new Card("Mega Man.", false),
		new Card("Mike Tyson.", false),
		new Card("Mispronouncing Duran Duran.", false),
		new Card("Mister Mosquito.", false),
		new Card("MomTron.", false),
		new Card("Moundo.", false),
		new Card("Naughty Bear.", false),
		new Card("Nazi von Killyou.", false),
		new Card("Ninja Sex Party.", false),
		new Card("Nixon.", false),
		new Card("NO JON NO.", false),
		new Card("NOT FUCKING THIS!", false),
		new Card("Not knowing the controls to Nickelodeon GUTS.", false),
		new Card("Not reading the game's instructions.", false),
		new Card("Obeying Protoman and burning down a forest.", false),
		new Card("Pause balls.", false),
		new Card("Pelistorm.", false),
		new Card("Playing a terrible game for more than a hundred episodes.", false),
		new Card("Playing slaps to break a tie.", false),
		new Card("PONY.MOV.", false),
		new Card("Poopy butt.", false),
		new Card("Poppy Bros.", false),
		new Card("Princess Elise's octopus face.", false),
		new Card("Punching a hole in a gingerbread house.", false),
		new Card("Queefing bombs out of your vagina.", false),
		new Card("Racial slurs.", false),
		new Card("RIDIN’ ON CARS!!!", false),
		new Card("Robots ordering cheese pizza.", false),
		new Card("Rocket. To the moon.", false),
		new Card("Rolling around at the speed of sound.", false),
		new Card("RubberRoss.", false),
		new Card("Rouge's gross bat face.", false),
		new Card("Screaming out Whitney Houston’s “I Will Always Love You�? in primal agony.", false),
		new Card("Sequelitis.", false),
		new Card("Seven asses.", false),
		new Card("Signing and destroying a copy of Sonic '06.", false),
		new Card("Silver the Hedgehog.", false),
		new Card("Sneaking dirty British humour into an unassuming video game about a bear and a bird.", false),
		new Card("Snow white shit.", false),
		new Card("Snowboarding uphill", false),
		new Card("Solid Snake.", false),
		new Card("Sonic '06.", false),
		new Card("Spice World.", false),
		new Card("Spraying compressed air with a bittering agent in your face, and subsequently vomiting.", false),
		new Card("Stairfax Temperatures.", false),
		new Card("Staring at a menu while Ross stuffs his disgusting face with candy.", false),
		new Card("Stasis-ing the drill.", false),
		new Card("Steam Train.", false),
		new Card("Sticky sap.", false),
		new Card("Stretch Panic.", false),
		new Card("STRGG.", false),
		new Card("Struggling to fight Silver the Hedgehog.", false),
		new Card("Sucking blood from a Japanese girl's tits.", false),
		new Card("Suzy the Goose.", false),
		new Card("TENOUTTATEN.", false),
		new Card("That guy.", false),
		new Card("The Awesome Series.", false),
		new Card("The band Egoraptor.", false),
		new Card("The Chinless Wonder.", false),
		new Card("The Goshdangodon.", false),
		new Card("The Higgs Boson.", false),
		new Card("The Knuckles wall glitch.", false),
		new Card("The rarest form of Arin having fun.", false),
		new Card("The realization that friendship is more important.", false),
		new Card("Three big feet of pleasure.", false),
		new Card("Tonguing up.", false),
		new Card("Typing 'C D PLAYER' and getting 'MODEL CAR.'", false),
		new Card("WAAAAAAAVE LAAAAZEEEEEEER.", false),
		new Card("Walking around in my banana shoes.", false),
		new Card("World Dick Barf Syndrome.", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Game Grumps";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "GG";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}