package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckNorthernlion extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("_ caused Northernlion to take stupid damage."),
		new Card("_ Is the best item in The Binding of Isaac."),
		new Card("_ is the worst item in The Binding of Isaac."),
		new Card("_ is/are Northernlion's worst nightmare."),
		new Card("_: The Northernlion Story."),
		new Card("_? Well, I won't look a gift horse in the mouth on that one."),
		new Card("'Hey everybody and welcome to Let's Look At _!'"),
		new Card("As always, I will _ you next time!"),
		new Card("But that _ has sailed."),
		new Card("Even _ is/are better at video games than Northernlion."),
		new Card("Everything's coming up _."),
		new Card("Finding something like _ would turn this run around."),
		new Card("Fuck the haters, this is _."),
		new Card("Get in my _ zone."),
		new Card("I can do _ and die immediately afterward."),
		new Card("I don't even see _ anymore; all I see are blondes, brunettes, redheads..."),
		new Card("I'm in the permanent _ state."),
		new Card("If sloth _ are wrong I don’t want to be right."),
		new Card("Invaded the world of _."),
		new Card("It's _, ya dangus!"),
		new Card("JSmithOTI: Total _."),
		new Card("Legend has it, the Thug of Porn was arrested for _."),
		new Card("Let's Look At: _."),
		new Card("Northernlion's latest novelty Twitter account is @_."),
		new Card("More like the Duke of _, right?"),
		new Card("No one man should have all that _."),
		new Card("Northernlion has been facing ridicule for calling _ a rogue-like."),
		new Card("Northernlion always forgets the name of _."),
		new Card("Northernlion's refusal to Let's Play _ was probably a good call."),
		new Card("Of all the things that Ryan and Josh have in common, they bond together through their mutual love of _."),
		new Card("One thing Northernlion was right about was _."),
		new Card("Praise the _!"),
		new Card("Recently, Northernlion has felt woefully insecure due to _."),
		new Card("Roguelike? How about ___-like."),
		new Card("Sometimes, a man's just gotta _."),
		new Card("The hero of the stream was _."),
		new Card("The stream was going well until _."),
		new Card("The Youtube chat proved ineffective, so instead we had to communicate via _."),
		new Card("This new game is an interesting _-like-like."),
		new Card("We're rolling in _!"),
		new Card("Whenever I ___, take a drink."),
		new Card("Today's trivia topic is _."),
		new Card("What do you give to the CEO of Youtube as a gift?"),
		new Card("The only way NL is ever going to make it to Hell in Spelunky is by using _."),
		new Card("Welcome back to The Binding of Isaac. Today's challenge run will be based on  _."),
		new Card("Well there's nothing wrong with _ by any stretch of the imagination."),
		new Card("I'd sacrifice _ at the Altar."),
		new Card("Fox would still be here if not for _."),
		new Card("I wasn't even that drunk! I just had some _, _, and _."),
		new Card("_ was indicted on account of _."),
		new Card("_: The _ Story."),
		new Card("Hello everybody, welcome to a new episode of _ plays _."),
		new Card("I beat Blue Baby with only _ and _!"),
		new Card("Northernlion has alienated fans of _ by calling them _."),
		new Card("Northernlion was fired from his teaching job and had to flee South Korea after an incident involving  _ and _."),
		new Card("Northernlion's doctor diagnosed him today with _, an unfortunate condition that would lead to _."),
		new Card("And now we're going to be fighting _ on _."),
		new Card("Dang it, _!"),
		new Card("_ was full of leeches."),
		new Card("Pimp your ___!"),
		new Card("My apologies to the _ estate."),
		new Card("What interrupted the #NLSS?"),
		new Card("Travel by _."),
		new Card("The stream broke when Ryuka stepped on the _ key."),
		new Card("Say that to my face one more time and I'll start _."),
		new Card("Oh my god, he's using _ magic!"),
		new Card("Krazy Mike lost to _!"),
		new Card("What would you do if Ohm really did just die?"),
		new Card("_ has invaded!"),
		new Card("We're having technical difficulties due to _."),
		new Card("JSmithOTI is referred to as a Scumlord, but his friends call him _."),
		new Card("Ohmwrecker is known for his MLG online play. What people don't know is that he's also MLG at _."),
		new Card("Follow MichaelALFox on Twitter and you can see pictures of _."),
		new Card("After Mars, _ is the next furthest planet from the sun."),
		new Card("What would Ohm do?"),
		new Card("The next movie reading will be of _."),
		new Card("How did Northernlion unite Scotland?"),
		new Card("Green loves the new Paranautical Activity item _, but keeps comparing it to the crossbow."),
		new Card("_ is really essential to completing the game."),
		new Card("My channel is youtube.com/_."),
		new Card("Northernlion's cat Ryuka is known for _ while he records."),
		new Card("What gave Ohmwrecker his gaming powers?"),
		new Card("Hello anybody, I am ____Patrol."),
		new Card("I have _, can you _ me?"),
		new Card("_! Get off the _!"),
		new Card("My name is _ and today we'll be checking out _."),
		new Card("It's true that Green9090 is _, but we must all admit that Ohm is better at _"),
		new Card("That's the way _ did it, that's the way _ does it, and it''s worked out pretty well so far."),
		new Card("Today on Crusader Kings 2, NL plays King _ the _."),
		new Card("After winning yet another race, Josh made _ tweet about _."),
		new Card("This time on _ vs. _, we're playing _.")
	}, responseCards = new Card[]{
		new Card("Steven Docking."),
		new Card("/r/Letsplay."),
		new Card("/r/sloths."),
		new Card("#Krazymike."),
		new Card("A Bane impression."),
		new Card("A bunch of jabronies."),
		new Card("A docking sleeve."),
		new Card("A little bit of added defense."),
		new Card("An old man carrying a box of glass down stairs."),
		new Card("Anything from http://www.thenorthernlionstory.com/."),
		new Card("Beating it on camera."),
		new Card("Being terrible at games."),
		new Card("Bejeweed."),
		new Card("Big Hat Logan."),
		new Card("Blondes, brunettes, and redheads."),
		new Card("Blue Baby."),
		new Card("BOOYAH!"),
		new Card("Bow to your sensei!"),
		new Card("Brimstone."),
		new Card("Butt meat."),
		new Card("Checking the wiki."),
		new Card("Cheeseysaurus Rex."),
		new Card("Classic Northernlion."),
		new Card("Coming on Milhouse."),
		new Card("Corner fucking."),
		new Card("Crazy Mike."),
		new Card("Cross-dimensional fucking."),
		new Card("Dark holes."),
		new Card("Detroit Dock City."),
		new Card("Docking."),
		new Card("DockLeeSmile."),
		new Card("Dung pies."),
		new Card("Dying in a hang gliding accident. "),
		new Card("Excuse me?"),
		new Card("Eyeless ooze guys."),
		new Card("Falling down the stairs with a bag full of glass."),
		new Card("Fat Robert Downey Jr."),
		new Card("Feline eugenics."),
		new Card("Fuck tables."),
		new Card("Fucking during a Diphtheria epidemic."),
		new Card("Garglebutts."),
		new Card("Getting corner fucked."),
		new Card("Getting wood."),
		new Card("Greed."),
		new Card("Harry Potter and the Chamber of a Salty Surprise."),
		new Card("Hookers, blow, and JSmithOTI."),
		new Card("Infomercials."),
		new Card("JSmithOTI."),
		new Card("Kate's Mario Party skills."),
		new Card("Krazy Mike doing a backflip, throwing a talking nut, and chanting 'Hello!'"),
		new Card("Krazy Mike."),
		new Card("Like you, but not rogue-like you."),
		new Card("Losing to Monstro after 300 hours of experience."),
		new Card("The backroom casting couch."),
		new Card("The fuck zone."),
		new Card("Losing to Quelaag 12 times in 72 minutes."),
		new Card("Michael Caine's spider collection."),
		new Card("Michaelalfox."),
		new Card("Michaelalfox's love of cheese."),
		new Card("Michaelalfox's muscles."),
		new Card("Milking the poop for red hearts."),
		new Card("Mom's knife."),
		new Card("Mom's pad."),
		new Card("Monty."),
		new Card("A motherfucker."),
		new Card("Motherfucking."),
		new Card("Nipple hair."),
		new Card("Northernlion."),
		new Card("Northernlion's cancelled Assassin's Creed II let's play."),
		new Card("Northernlion's coffee maker."),
		new Card("Northernlion's hair."),
		new Card("Northernlion's pooping album."),
		new Card("Not Satan, I promise."),
		new Card("Permanent Polaroid invincibility."),
		new Card("Poison Mushroom."),
		new Card("Poutine-induced diabetes."),
		new Card("Pretending youtube let's playing is a real job."),
		new Card("Projectile annoyance."),
		new Card("Putting your balls in her butt."),
		new Card("Puzzle platformers with rogue-like elements."),
		new Card("Quelaag's Furysword."),
		new Card("Residue."),
		new Card("RockLeeSmile."),
		new Card("Rogue-like likes."),
		new Card("Roll Fizzlebeef."),
		new Card("Ronald McDonald."),
		new Card("Shit happens."),
		new Card("Shooting the poop."),
		new Card("Solaire of Astora."),
		new Card("Stream lag."),
		new Card("Stupid damage."),
		new Card("A tactical backflip."),
		new Card("The Northernlion Story."),
		new Card("Whispering sweet nothings into your rear."),
		new Card("The notorious Grey's Anatomy let's play."),
		new Card("The Binding of Isaac wiki."),
		new Card("Thornforg."),
		new Card("When you fuck a dog in the ass and it shits all over your dick."),
		new Card("The USS Buttfucker."),
		new Card("Vaginal silk worms."),
		new Card("The Anor Londo Archers."),
		new Card("The saga of Krazy Mike."),
		new Card("A urination break."),
		new Card("The World Docking Champion."),
		new Card("The Thug of Porn."),
		new Card("That damned HDPVR."),
		new Card("The NLSS: drawing unwanted attention from the actual docking community."),
		new Card("Patrick Dempsey thrusting violently into my midsection."),
		new Card("Well, what is it?"),
		new Card("The Four Horsemen of The Apocolypse."),
		new Card("Talking nuts."),
		new Card("The Ozymandias head."),
		new Card("A total scumbag."),
		new Card("Striking fear into the hearts of your enemies."),
		new Card("Using the tears of an abused toddler to conquer my foes."),
		new Card("A beef swarm."),
		new Card("A butt pooping upwards an egg."),
		new Card("JSmith's salty nuts."),
		new Card("#ShotsFired."),
		new Card("Banana bread."),
		new Card("Butterjail."),
		new Card("A DraculaFetus animation."),
		new Card("A profile pic that looks like a dick and balls."),
		new Card("Spy Party racism."),
		new Card("The ghost of Ohmwrecker."),
		new Card("Shooting the black guy."),
		new Card("Ohm's mindgames."),
		new Card("Magic: The Gathering."),
		new Card("A failed challenge run."),
		new Card("Setting the world on fire."),
		new Card("Pot magic."),
		new Card("Josh's washing machine."),
		new Card("Dang it, Bobby!"),
		new Card("Up in the air like a George Clooney movie."),
		new Card("A lemon mishap."),
		new Card("This cat, I swear to god."),
		new Card("Ohmwrecker."),
		new Card("youtube.com/Ohmwrecker."),
		new Card("Drinkable fire."),
		new Card("Ohmsdrawings.tumblr.com."),
		new Card("Soul level 1 invasions."),
		new Card("Ryuka."),
		new Card("The blue candle."),
		new Card("JSmith's laundry."),
		new Card("Mount Your Friends: Docking Edition."),
		new Card("Childlike bukakke."),
		new Card("A water supply full of leeches."),
		new Card("Travelling by bones."),
		new Card("AlpacaPatrol."),
		new Card("Zen."),
		new Card("Green9090."),
		new Card("#MikeBithell."),
		new Card("RedPandaGamer."),
		new Card("Ohm, our god.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Northernlion";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Lion";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}