package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckAdminPicks extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("What is the next great Kickstarter project?"),
		new Card("Praise _!"),
		new Card("_ for president!"),
		new Card("Cunnilungus and psychiatry brought us to _."),
		new Card("_ is the only thing that matters."),
		new Card("I'm an expert on _."),
		new Card("What can you always find in between the couch cushions?"),
		new Card("Don't get mad, get _."),
		new Card("Have fun, don't be _."),
		new Card("It's the end of _ as we know it."),
		new Card("_ is my worst habit."),
		new Card("Everything's better with _."),
		new Card("What would you taste like?"),
		new Card("What have you accomplished today?"),
		new Card("What made you happy today?"),
		new Card("Why are you frothing with rage?"),
		new Card("What mildy annoyed you today?"),
		new Card("We'll always have _."),
		new Card("_ uses _. It is SUPER EFFECTIVE!"),
		new Card("Let's all rock out to the sounds of _."),
		new Card("Take _, it will last longer."),
		new Card("A wild _ appeared! It used _!"),
		new Card("If life gives you _, make _."),
		new Card("Who needs a bidet when you have _?"),
		new Card("Kill it with _!"),
		new Card("My _ is too big!"),
		new Card("Best drink ever: One part _, three parts _, and a splash of _."),
		new Card("_ makes me uncomfortable."),
		new Card("Stop, drop, and _."),
		new Card("Think before you _."),
		new Card("_ is the name of my _ cover band."),
		new Card("Alcoholic games of Clue&reg; lead to _."),
		new Card("After I saw _, I needed _."),
		new Card("There's _ in my soup."),
		new Card("_ sounds like a great alternative rock band."),
		new Card("_. Everything else is uncivilized."),
		new Card("Best game of 2013? _, of course."),
		new Card("How do you get your dog to stop humping your leg?"),
		new Card("Oh god, I can't believe we ate _ at PAX."),
		new Card("Only in Korea can you see _."),
		new Card("_? It's a DLC item."),
		new Card("The Holy Trinity: _, _, and _!"),
		new Card("My life for _!"),
		new Card("Who let the dogs out?"),
		new Card("In his next movie, Will Smith saves the world from _."),
		new Card("When North Korea gets _, it will be the end of the world."),
		new Card("Plan a three course meal."),
		new Card("Tastes like _."),
		new Card("_ and _ are the new hot couple."),
		new Card("What will Xyzzy take over the world with?"),
		new Card("Welcome to my secret lair on _."),
		new Card("Dustin Browder demands more _ in StarCraft&reg;."),
		new Card("I write slash fanfiction pairing _ with _."),
		new Card("Ladies and gentlemen, I give you _...COVERED IN BEES!!!"),
		new Card("When I was a kid, all we had in Lunchables were three _ and _."),
		new Card("On its last dying breath, _ sent out a cry for help. A bunch of _ heard the cry."),
		new Card("At first I couldn't understand _, but now it's my biggest kink."),
		new Card("Long story short, I ended up with _ in my ass."),
		new Card("Who knew I'd be able to make a living off of _?"),
		new Card("It's difficult to explain to friends and family why I know so much about _."),
		new Card("I can't believe I spent most of my paycheck on _."),
		new Card("Hey guys, check out my _ montage!"),
		new Card("_! You know, for kids."),
		new Card("I watch movies just to see if I can find a Big Lipped _ Moment."),
		new Card("No one wants to see your _."),
		new Card("OH MY GOD THIS IS THE GREATEST _ I'VE EVER SEEN IN MY LIFE!"),
		new Card("STOP OR I WILL _."),
		new Card("What doesn't work that way?"),
		new Card("What the fuck is wrong with you?"),
		new Card("_ is camping my lane."),
		new Card("Vegeta, what does the scouter say?"),
		new Card("Who the hell do you think I am?!"),
		new Card("On the next episode of Dragon Ball Z, Goku has a fierce battle with _."),
		new Card("So wait, _ was actually _? Wow, I didn't see that one coming!"),
		new Card("Real men watch _."),
		new Card("Whenever I'm splashed with cold water, I turn into _."),
		new Card("No matter how you look at it, ultimately _ is responsible for _."),
		new Card("There are guilty pleasures. And then there's _."),
		new Card("When it comes to Japanese cuisine, there's simply nothing better than _."),
		new Card("Just announced: The brand new anime adaptation of _, starring _ as the voice of _."),
		new Card("_. Goddammit, Japan."),
		new Card("I have never in my life laughed harder than the first time I watched _."),
		new Card("Digimon! Digivolve to: _-mon!"),
		new Card("People die when they are _."),
		new Card("Okay, I'll admit it. I would totally go gay for _."),
		new Card("Truly and without question, _ is the manliest of all men."),
		new Card("WANTED: $50,000,000,000 reward for the apprehension of____."),
		new Card("The government of Japan recently passed a law that effectively forbids all forms of _."),
		new Card("Of my entire collection, my most prized possession is _."),
		new Card("I'M-A FIRIN' MAH _!"),
		new Card("The sad truth is, that at the edge of the universe, there is nothing but _."),
		new Card("The Himalayas are filled with many perils, such as _."),
		new Card("The road to success is paved with _."),
		new Card("And on his farm he had _, E-I-E-I-O!"),
		new Card("_ is the root of all evil."),
		new Card("The primitive villagers were both shocked and amazed when I showed them _."),
		new Card("And it is said his ghost still wanders these halls, forever searching for his lost _."),
		new Card("The best part of waking up is _ in your cup."),
		new Card("What do I keep hidden in the crawlspace?"),
		new Card("Go-Go-Gadget, _!"),
		new Card("I finally realized I hit rock bottom when I started digging through dumpsters for _."),
		new Card("And the award for the filthiest scene in an adult film goes to '5 women and _.'"),
		new Card("'Why Grandma', said Little Red Riding Hood, 'What big _ you have!'"),
		new Card("Who would have guessed that the alien invasion would be easily thwarted by _."),
		new Card("With Democrats and Republicans in a dead heat, the election was snatched by _ party."),
		new Card("_. That is my fetish."),
		new Card("All your _ are belong to us"),
		new Card("Sorry Mario, but _ is in another castle."),
		new Card("_ is a lie."),
		new Card("Who's an asshole?"),
		new Card("_ is the greatest Canadian."),
		new Card("If you could fuck anyone in the world, who would you choose?"),
		new Card("What is the meaning of life?"),
		new Card("What is the saddest thing you've ever seen?"),
		new Card("What is the worst thing anyone could say in front of the police?"),
		new Card("What is your favorite book?"),
		new Card("What is your mating call?"),
		new Card("Why are there six _ when there are only four _?"),
		new Card("TotalBiscuit's top hat is actually _. "),
		new Card("The Xbox One's DRM policy isn't half as bad as _."),
		new Card("What will YouTube add in its next unneeded update?"),
		new Card("The seldomly mentioned 4th little pig built his house out of _."),
		new Card("Mom, I swear! Despite its name, _ is NOT a porno!")
	}, responseCards = new Card[]{
		new Card("The world's tallest midget."),
		new Card("Four Loko."),
		new Card("Xyzzy playing around with gender roles."),
		new Card("Sonic brutally murdering Mario."),
		new Card("Mario brutally murdering Sonic."),
		new Card("The Bible."),
		new Card("Two midgets stacked up pretending to be one person."),
		new Card("Mr. Hankey the Christmas Poo."),
		new Card("Show me your tits!"),
		new Card("Thanking your sex slaves."),
		new Card("Googly eyes on a cock."),
		new Card("Typing with your genitals."),
		new Card("Pirate hookers."),
		new Card("Mandatory Sex Party."),
		new Card("Games you can play with bricks."),
		new Card("Fancy tampons."),
		new Card("Boobs."),
		new Card("Moobs."),
		new Card("Tinychat."),
		new Card("THE GODDAMN BATMAN."),
		new Card("Swinging an axe in the air while cornholing a bear."),
		new Card("Fuck you, I'm a bear."),
		new Card("Doctor Who."),
		new Card("EXTERMINATE."),
		new Card("Bearshark."),
		new Card("SCIENCE!!1!"),
		new Card("Just the tip!"),
		new Card("Trouser snakes."),
		new Card("Drinking on live TV."),
		new Card("The Power of Greyskull."),
		new Card("Hello Kitty."),
		new Card("Tots."),
		new Card("Getting drunk before noon."),
		new Card("Clown strippers."),
		new Card("KERMIT FLAIL."),
		new Card("Premature ejaculation."),
		new Card("Bounty, the Quicker Picker Upper."),
		new Card("A spoon that is too big."),
		new Card("Bleeding Anuses."),
		new Card("Not being pregnant."),
		new Card("Hookers and blow."),
		new Card("Standing next to short people to use them as armrests."),
		new Card("The sound a single ThunderStix&reg; makes."),
		new Card("Dr. Phil."),
		new Card("The Columbine Shooting."),
		new Card("A big wet pink laser sword."),
		new Card("A brief moment of aptitude."),
		new Card("A butt egg."),
		new Card("A delicious baby."),
		new Card("A street cleaning simulator."),
		new Card("John Madden."),
		new Card("Maple syrup."),
		new Card("A mile-long penis."),
		new Card("Novelty Twitter accounts."),
		new Card("Olmec."),
		new Card("Reddit."),
		new Card("Sex."),
		new Card("South Korea."),
		new Card("YouTube."),
		new Card("Type-C Tetris music."),
		new Card("Hentai."),
		new Card("Indiana Jones."),
		new Card("Smooth jazz."),
		new Card("Soviet Russia."),
		new Card("Using hot sauce as lube."),
		new Card("Fruit Fuckers."),
		new Card("Beer Pong."),
		new Card("Rule 34."),
		new Card("The smallest, whitest dick."),
		new Card("Skullcrusher Mountain."),
		new Card("Mr. Fancy Pants."),
		new Card("TotalBiscuit's top hat."),
		new Card("An 8-ball."),
		new Card("Penn and Teller."),
		new Card("My mom."),
		new Card("My penis catching fire."),
		new Card("Santa Christ."),
		new Card("Stick figure porn."),
		new Card("The Angry Video Game Nerd."),
		new Card("The elephant in the room."),
		new Card("The Nostalgia Critic."),
		new Card("The Power Glove."),
		new Card("Time travel."),
		new Card("Your mom."),
		new Card("Bees!"),
		new Card("A baseball to the nuts."),
		new Card("A Big Lipped Alligator Moment."),
		new Card("A bird fucking a horse."),
		new Card("A killer rabbit."),
		new Card("A tiny white dick."),
		new Card("A zombie fisherman."),
		new Card("An obscure reference only two people will get."),
		new Card("Anal tearing."),
		new Card("Bees. My God."),
		new Card("Being frozen today."),
		new Card("Chuck Norris."),
		new Card("Fuck you, I do what I want."),
		new Card("FUCK YOU, I'M SPIDERMAN!"),
		new Card("Getting mauled by a mountain lion AND a grizzly bear at the same time."),
		new Card("Glenn Beck being torn apart by zombies."),
		new Card("Going full retard."),
		new Card("Ham?"),
		new Card("An awkward slash fic between The Nostalgia Critic and The Angry Video Game Nerd."),
		new Card("The League of Legends."),
		new Card("A tub of Vaseline."),
		new Card("Sex with strangers."),
		new Card("PetSmart."),
		new Card("StarFox."),
		new Card("Sonic the Hedgehog."),
		new Card("DeviantArt."),
		new Card("STEAL ALL THE FARM."),
		new Card("PEEEEEEEEEEEEEEEENIIIISSSSSSSS."),
		new Card("Jumanji."),
		new Card("Wards."),
		new Card("K-Pop."),
		new Card("Doing Gangnam Style at a funeral."),
		new Card("125% Reccomended Daily Allowance of cock."),
		new Card("A 3am phone call."),
		new Card("Ezreal's hot sugary ass."),
		new Card("Narutards."),
		new Card("Dead catgirls."),
		new Card("Tentacle rape."),
		new Card("A fuck-mothering vampire."),
		new Card("FUNimation."),
		new Card("Aya Hirano being gang-banged by her entire band."),
		new Card("OVER 9000!!"),
		new Card("Idiots who don't seem to realize that Avatar: The Last Airbender isn't really an anime."),
		new Card("Yu-Gi-Oh! The Abridged Series."),
		new Card("A fat middle-aged man in a Sailor Moon costume."),
		new Card("Sarah Fuckin' Palin."),
		new Card("Naruto."),
		new Card("Vash the Stampede."),
		new Card("Cowboy Bebop."),
		new Card("Fullmetal Alchemist."),
		new Card("Futanari."),
		new Card("Tengen Toppa Gurren Lagann."),
		new Card("Being eaten by a titan."),
		new Card("The Death Note."),
		new Card("A Hello Kitty! vibrator."),
		new Card("A mindfuck."),
		new Card("The Hare Hare Yukai dance."),
		new Card("Getting your penis cut in half."),
		new Card("Cousin marriage."),
		new Card("4Kids."),
		new Card("Watching FLCL while tripping on acid."),
		new Card("Sticking your finger up her ass."),
		new Card("Standing outside the gates of the White House completely naked with a revolver in your hand."),
		new Card("Catholic priests who drink, smoke, and carry guns."),
		new Card("Your virgin soul."),
		new Card("Engrish."),
		new Card("A dead meme."),
		new Card("Twincest."),
		new Card("Asian cock."),
		new Card("Holy dildos."),
		new Card("Drills for hands."),
		new Card("Taking a seat with Chris Hansen."),
		new Card("The Village People."),
		new Card("A Cleveland steamer."),
		new Card("A big floppy donkey dick."),
		new Card("Toilet paper."),
		new Card("Getting off on anime porn."),
		new Card("The Teenage Mutant Ninja Turtles."),
		new Card("Mining for nose gold."),
		new Card("Laxatives."),
		new Card("Genital warts."),
		new Card("A dead hooker."),
		new Card("A skeptical sheriff."),
		new Card("The crushed dreams of a stripper."),
		new Card("Peanutbutter jelly time."),
		new Card("Granny panties."),
		new Card("A Fleshlite&trade;."),
		new Card("A molotov cocktail."),
		new Card("The end of the world."),
		new Card("Don Knotts."),
		new Card("Morbid obesity."),
		new Card("A MILF."),
		new Card("Yellow snow."),
		new Card("Miss. Piggy."),
		new Card("The town drunk."),
		new Card("The Fresh Prince of Bel-Air."),
		new Card("Talking like a pirate."),
		new Card("A Facebook stalker."),
		new Card("Bed wetting."),
		new Card("Nuns."),
		new Card("Scotch."),
		new Card("Realizing, too late, that there is no toilet paper left."),
		new Card("Illegal immigrants."),
		new Card("That one episode of CSI."),
		new Card("A giant horse cock."),
		new Card("A juice box."),
		new Card("A tree."),
		new Card("Lesbians."),
		new Card("George Costanza"),
		new Card("The Wii U"),
		new Card("the PS4"),
		new Card("the NES"),
		new Card("the SNES"),
		new Card("the SEGA Genesis"),
		new Card("the PSX"),
		new Card("the duck hunt dog"),
		new Card("Mountain Dew"),
		new Card("Duck Hunt"),
		new Card("Space Core."),
		new Card("Surprise blowjobs."),
		new Card("DOTA 2."),
		new Card("A beautiful little moment."),
		new Card("A couch stinking of naked people."),
		new Card("A pretty epic poo."),
		new Card("A smaller, whiter dick."),
		new Card("A testicle examination."),
		new Card("An expensive rental costume."),
		new Card("Fart science."),
		new Card("Literally going to Hell."),
		new Card("Pacific Rim."),
		new Card("Reading the manual."),
		new Card("Surgeon Simulator 2013."),
		new Card("A wet paper towel."),
		new Card("Minecraft."),
		new Card("A bag of dicks."),
		new Card("The Card Czar."),
		new Card("Lara Croft."),
		new Card("Being banned from /r/pyongyang."),
		new Card("The lost city of Atlantis.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Admin's Picks";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Admin";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}