package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckRPAnons extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("____ doesn't need to be judged right now.", true),
		new Card("____ is a terrible thing to do to the ____!", true),
		new Card("____ &amp; ____: Worst mods ever.", true),
		new Card("/____ all over this post.", true),
		new Card("/____ delicately from the butt.", true),
		new Card("/slides hand up your ____.", true),
		new Card("____ is not an island.", true),
		new Card("____ runs into the forest, screaming.", true),
		new Card("____ was better before the anon meme.", true),
		new Card("We'd love to have you at ____ Island!", true),
		new Card("Bad news guys, my parents found that thread involving ____.", true),
		new Card("But what are your thoughts on ____?", true),
		new Card("Chaos ensued when Wankgate banned ____.", true),
		new Card("Cute, fun and ____.", true),
		new Card("Does anyone ____? I feel like the only one.", true),
		new Card("Excuse me, but I identify as ____.", true),
		new Card("Great, another ____ event.", true),
		new Card("How can there be a group of people more ____ than us?", true),
		new Card("How's my driving?", true),
		new Card("I can only ____ if I feel a deep emotional connection.", true),
		new Card("I can't believe we just spent a whole page wanking about ____.", true),
		new Card("I have a PHD in ____.", true),
		new Card("I just benchpressed, like, 14 ____.", true),
		new Card("I need deets on ____, stat.", true),
		new Card("I predict ____ will close by the end of the year.", true),
		new Card("I randomly began to ____ and ____ came galloping up the stairs.", true),
		new Card("I see Wankgate's bitching about ____ again.", true),
		new Card("I'm literally shaking and ____ right now.", true),
		new Card("I'm married to ____ on the astral plane.", true),
		new Card("I'm really into ____, so please don't kinkshame.", true),
		new Card("I'm sad we lost ____ in the exodus from LJ to DW.", true),
		new Card("I'm starting a game where the characters are stuck in ____.", true),
		new Card("I'm taking commissions for ____!", true),
		new Card("How dare you not warn for ____! Don't you know how triggering that is?", true),
		new Card("In this world, sexual roles are divided into three categories: the ____, the ____, and the ____", true),
		new Card("It's ____ o'clock.", true),
		new Card("ITT: ____.", true),
		new Card("Join my new game about ____!", true),
		new Card("Keep fucking that ____.", true),
		new Card("Let me tell you about ____.", true),
		new Card("Log in and ____.", true),
		new Card("My favorite thread is the one where ____ has kinky sex with ____.", true),
		new Card("My headcanon is that ____ is ____.", true),
		new Card("My OTP: ____ x ____.", true),
		new Card("New game idea! You're kidnapped by ____ and forced into ____.", true),
		new Card("no actually i don't care at all, i don't even ____. :))))", true),
		new Card("OMG you guys I have so many feels about ____!", true),
		new Card("Only ____ would play from ____.", true),
		new Card("Raising money for ____! Please replurk!", true),
		new Card("RPAnons made me ____.", true),
		new Card("SHUT UP ABOUT YOUR ____.", true),
		new Card("Signal boosting for ____!", true),
		new Card("Since ____ is on hiatus, fans have migrated to ____.", true),
		new Card("Someone just stuck their head out of the window and screamed ", true),
		new Card("Someone left a ____ out in the rain.", true),
		new Card("That ____. You know, *that* one.", true),
		new Card("The ____ is happy.", true),
		new Card("The perfect username for my next character: ____.", true),
		new Card("The thing I hate most about RP is ____.", true),
		new Card("Their ____ are of age.", true),
		new Card("There are too many memes about ____.", true),
		new Card("There is no ____ in Holly Heights.", true),
		new Card("We need a new post. This one smells like ____.", true),
		new Card("Why was I asked for app revisions?", true),
		new Card("Why was I banned?", true),
		new Card("Who apps ____ to a sex game?", true),
		new Card("Who should I play next?", true),
		new Card("You can't fist ____.", true),
		new Card("You sound ____, tbh.", true),
	}, responseCards = new Card[]{
		new Card("Rule 63.", false),
		new Card("'The' Hateboner.", false),
		new Card("(I glances.)", false),
		new Card("(unsure).", false),
		new Card("Too rad to be cis.", false),
		new Card("A 'shopped vendetta.", false),
		new Card("A 5-page-long kink list.", false),
		new Card("A bouquet of dicks.", false),
		new Card("A creepy Corruption of Champions OC.", false),
		new Card("A funny name for Benedict Cumberbatch.", false),
		new Card("A genderswapped vampire AU Cloud Strife.", false),
		new Card("A glopping noise.", false),
		new Card("A misfire.", false),
		new Card("A paid account full of nothing but terrible fanart icons.", false),
		new Card("A penis approximately the size and shape of a Guinness can.", false),
		new Card("A shitty urban fantasy OC.", false),
		new Card("A spooky jamjar.", false),
		new Card("A tag so boring it makes you want to delete all of your journals.", false),
		new Card("A tragic Christmas hang-gliding accident.", false),
		new Card("Accidental video posts.", false),
		new Card("Alpha/Beta/Omega.", false),
		new Card("Amatomnes.", false),
		new Card("An awful fandom OC who's married to the main character.", false),
		new Card("Anonfailing.", false),
		new Card("Another boring wank about f/f.", false),
		new Card("Another fucking TFLN meme.", false),
		new Card("App revisions.", false),
		new Card("Ataraxion.", false),
		new Card("Autistic gypsies.", false),
		new Card("Baby penis.", false),
		new Card("Bakerstreet.", false),
		new Card("Begging for asspats.", false),
		new Card("Being really passive-aggressive because you ", false),
		new Card("Being soulbonded to a Homestuck character.", false),
		new Card("Broccoli trees.", false),
		new Card("Butthurt.", false),
		new Card("Calling long-distance to demand tags from your RP partner.", false),
		new Card("Cape and Cowl.", false),
		new Card("Changed.", false),
		new Card("Chronic Lyme disease.", false),
		new Card("Circlejerking.", false),
		new Card("City of Ariel.", false),
		new Card("Cloud being eaten by a chocobo.", false),
		new Card("Cockhopping.", false),
		new Card("Constructive criticism.", false),
		new Card("Dangan Ronpa's crazy fandom.", false),
		new Card("Dean/Goku.", false),
		new Card("Dear Mun.", false),
		new Card("Discedo.", false),
		new Card("Drama Drama Duck.", false),
		new Card("Dropping the thread after two tags because it sucks.", false),
		new Card("ECATS? CAT DESK? WE SCAT?", false),
		new Card("An incest ship.", false),
		new Card("Entranceway.", false),
		new Card("Everyone turning into ponies.", false),
		new Card("Exit Void.", false),
		new Card("Exsilium.", false),
		new Card("FACT IT!", false),
		new Card("Fad fandoms.", false),
		new Card("Falling in love with your RP partner.", false),
		new Card("Feeling like the only one.", false),
		new Card("Flouncing. The more dramatic, the better.", false),
		new Card("Fucking that chicken.", false),
		new Card("Generic white male actor PBs.", false),
		new Card("Haven.", false),
		new Card("Hellion.", false),
		new Card("Hetalia's annoying fandom.", false),
		new Card("High Seas.", false),
		new Card("Highlandering.", false),
		new Card("Hitting the cervix with your dick.", false),
		new Card("Holly Heights.", false),
		new Card("Homestuck's insane fandom.", false),
		new Card("Icon elitism.", false),
		new Card("Icons that aren't 100x100.", false),
		new Card("Kink shaming.", false),
		new Card("Legbeards.", false),
		new Card("Literally shaking and crying.", false),
		new Card("lol so randumb!!!!111 XD", false),
		new Card("Lovingly describing your character's throbbing cock.", false),
		new Card("Luceti.", false),
		new Card("Mpreg.", false),
		new Card("Musedumping.", false),
		new Card("Neckbeards.", false),
		new Card("Needing to lei down.", false),
		new Card("Not posting deets.", false),
		new Card("Nymphomanic werewolf Rei Ayanami. On rollerskates.", false),
		new Card("One-pixel borders.", false),
		new Card("One-word replies.", false),
		new Card("Paradisa.", false),
		new Card("Passive-aggressive editing.", false),
		new Card("Pigeon superpowers.", false),
		new Card("Pillow queens.", false),
		new Card("Only playing for ships.", false),
		new Card("Polychromatic.", false),
		new Card("Posting to Wankgate logged in.", false),
		new Card("Pregnancy plots.", false),
		new Card("Pretentious, illegible formatting.", false),
		new Card("Queefing on someone's dick.", false),
		new Card("Rebutle.", false),
		new Card("Renne.", false),
		new Card("Replying to everyone on ATP because you're just that desperate.", false),
		new Card("Reserving a popular character and never apping.", false),
		new Card("Roleplaying One Direction slash.", false),
		new Card("Route 29.", false),
		new Card("Roxanne Ritchie's vagina.", false),
		new Card("RPAnons.", false),
		new Card("Ruby City.", false),
		new Card("Rushing to dear_mun to post about the latest global tragedy in-character.", false),
		new Card("St-stuttered t-typing.", false),
		new Card("Obviously sameanoning.", false),
		new Card("Sample prompts.", false),
		new Card("Save The Earth.", false),
		new Card("Scathing anonymous criticism.", false),
		new Card("Scrambling to pass AC at the last minute.", false),
		new Card("Shounen retards.", false),
		new Card("Signal boosting an obvious hoax.", false),
		new Card("Slacktivism.", false),
		new Card("Social justice warriors.", false),
		new Card("Sora and Emperor Palpatine in an awkward, skeezy relationship.", false),
		new Card("Springing rape scenarios on people without asking.", false),
		new Card("Stormy's latest alias.", false),
		new Card("Superwholockvengers.", false),
		new Card("Surprise futa.", false),
		new Card("Tag nirvana.", false),
		new Card("Tentabulge headcanons.", false),
		new Card("Terminal Tokyo.", false),
		new Card("That Kronk.", false),
		new Card("That Patchouli.", false),
		new Card("The Box.", false),
		new Card("The dominate one.", false),
		new Card("The Love Hotel.", false),
		new Card("The medium divide.", false),
		new Card("The myriad of songs you associate with your OTP.", false),
		new Card("The paid account fairy.", false),
		new Card("The Royal Baby.", false),
		new Card("The Salkia Island award.", false),
		new Card("The whole game jumping on the villain before they have a chance to be villainous.", false),
		new Card("TL;DR.", false),
		new Card("TMI public plurks.", false),
		new Card("Touhou lesbians nobody wants to play with.", false),
		new Card("Tower of Animus.", false),
		new Card("Tryhards.", false),
		new Card("Tittybabies.", false),
		new Card("Tumblrinas.", false),
		new Card("Two lonely neckbeards playing out futa together because nobody else will.", false),
		new Card("Two years' worth of semen.", false),
		new Card("tYPING LIKE THIS???????? oH MY GKFOODODD??????", false),
		new Card("Unironically using the word ", false),
		new Card("Username elitism.", false),
		new Card("Username squatting.", false),
		new Card("Vatheon.", false),
		new Card("Viewing anoncomms in flat-view like a heathen.", false),
		new Card("Visualosities.", false),
		new Card("Wank terriers.", false),
		new Card("Wankgate.", false),
		new Card("Wanking about games you aren't in.", false),
		new Card("Wanking about a private musebox.", false),
		new Card("wgar.", false),
		new Card("Whiteknighting.", false),
		new Card("Whoremongers.", false),
		new Card("Wrapping your hands around a penis and twisting in opposite directions.", false),
		new Card("Yaoi.", false),
		new Card("Zodion.", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] RPAnons";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Anons";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}