package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckVidya extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("Why are you making chocolate pudding at 4 in the morning?", true),
		new Card("The newest feature of the Xbox One is ____.", true),
		new Card("PS3: It only does  ____.", true),
		new Card("The new TF2 promo items are based on ____.", true),
		new Card("If Gordon Freeman spoke, what would he talk about?", true),
		new Card("&gt;tfw when ____.", true),
		new Card("All you had to do was follow the damn ____, CJ!", true),
		new Card("Liquid! How can you still be alive?", true),
		new Card("What can change the nature of a man?", true),
		new Card(" Microsoft revealed that the Xbox One's demos had actually been running on ____ ", true),
		new Card("What if ____ was a girl?", true),
		new Card("What did I preorder at gamestop?", true),
		new Card("____ confirmed for Super Smash Bros!", true),
		new Card("Based ____.", true),
		new Card("The newest IP from Nintendo, Super ____ Bros. ", true),
		new Card("____ only, no items, Final Destination. ", true),
		new Card("Enjoy ____ while you play your Xbox one!", true),
		new Card("The future of gaming lies with the ____.", true),
		new Card("The best way to be comfy when playing video games is with ____.", true),
		new Card("____ has no games.", true),
		new Card("PC gamers have made a petition to get ____ on their platform.", true),
		new Card("The new Nintendo ____ is a big gimmick. ", true),
		new Card("&gt;implying you aren't ____", true),
		new Card("WHAT IS A MAN?", true),
		new Card("What is a ___ but a ____?", true),
		new Card("WE WILL DRAG THIS ___ INTO THE 21ST CENTURY.", true),
		new Card("Wake up, Mr. Freeman. Wake up and ____.", true),
		new Card("I'm in ur base, ____", true),
		new Card("Pop Quiz: Beatles Song- ___ terday.", true),
		new Card(" ___ would like to play.", true),
		new Card("A mod of doom was made that was based off of ____.", true),
		new Card("I really didn't like what they did with the ____ Movie adaption.", true),
		new Card("HEY, GOLLEN PALACE? HOW U SAY ____ IN CHINESE?', 0, 1, ", true),
		new Card("Pumpkin doesn't want this.", true),
		new Card("NEXT TIME ON GAME GRUMPS: ____.", true),
		new Card("I used to be an adventurer like you, until ____.", true),
		new Card("Yeah, well, my dad works for ____.", true),
		new Card("Kotaku addresses sexism in ____ in their latest article.", true),
		new Card("Get double XP for Halo 3 with purchase of ____.", true),
		new Card("LoL stole their new character design off of ____.", true),
		new Card("____ is the cancer killing video games.", true),
		new Card("Suffer, like ____ did.", true),
		new Card("It's like ____ with guns!", true),
		new Card("Is a man not entitiled to ____?", true),
		new Card("____ has changed.", true),
		new Card("But you can call me ____ the ____. Has a nice ring to it dontcha think?", true),
		new Card("Objective: ____", true),
		new Card("EA Sports! It's ____.", true),
		new Card("____ is waiting for your challenge!", true),
		new Card("____ sappin' my sentry. ", true),
		new Card("I'm here to ____ and chew bubble gum, and I'm all out of gum.", true),
		new Card("I've covered ____, you know.", true),
		new Card("It's dangerous to go alone! Take this:", true),
		new Card("You were almost a ____ sandwich!", true),
		new Card("That's the second biggest ____ I've ever seen!", true),
		new Card("____. ____ never changes.", true),
		new Card("____ has changed. ", true),
		new Card("You have been banned. Reason: ____.", true),
		new Card("The newest trope against women in video games: ____.", true),
		new Card("Fans started a kickstarter for a new ____ game. ", true),
		new Card("Huh? What was that noise?", true),
		new Card("Viral marketers are trying to push the new ____.", true),
		new Card("I wouldn't call it a Battlestation, more like a ____.", true),
		new Card("____: Gotta go fast!", true),
		new Card("The best final fantasy game was ____.", true),
		new Card("I love the ____, it's so bad", true),
		new Card("Valve is going to make ____ 2 before they release HL3.", true),
		new Card("____ is a pretty cool guy", true),
		new Card("Ah! Your rival! What was his name again?", true),
		new Card("What's in the box, /v/?", true),
		new Card("Why is the ____ fandom the worst?", true),
		new Card("Achievement Unlocked: ____ !", true),
		new Card("I'm ____ under the table right now!", true),
		new Card("brb guys, ____ break", true),
		new Card("OH MY GOD JC, A ____", true),
		new Card("wooooooow, it took all 3 of you to ____", true),
		new Card("Rev up those ____, because I am sure hungry for one- HELP! HELP!", true),
		new Card("____ is 2deep and edgy for you.", true),
		new Card("Only casuals like ____.", true),
		new Card("The princess is in another ____", true),
		new Card("I have the bigger ____.", true),
		new Card("____ TEAM RULES!!", true),
		new Card("When you see it... you don't see ____.", true),
		new Card("HEY, GOLLEN PALACE? HOW U SAY ____ IN CHINESE?", true),
		new Card("WHAT THE FUCK DID YOU SAY ABOUT ME YOU ____?", true),
		new Card("This will be the 6th time we've posted ____; we've become increasingly efficient at it.", true),
		new Card("appealing to a larger audience", true),
		new Card("we must embrace ____ and burn it as fuel for out journey.", true),
		new Card("In Kingdom Hearts, Donald Duck will be replaced with ____ .", true),
		new Card("&gt;walk into gamestop<br>&gt;see ____<br>&gt;walk out", true),
		new Card("Because of the lastest school shooting, ____ is being blamed for making kids too violent.", true),
		new Card("Here lies ____: peperony and chease", true),
		new Card("Throwaway round: Get rid of those shit cards you don't want. Thanks for all the suggestions, /v/", true),
		new Card("The president has been kidnapped by ____. Are you a bad enough dude to rescue the president?", true),
		new Card("We ____ now.", true),
		new Card("What is the new mustard paste?", true),
		new Card("&gt;____<br>&gt;____<br>&gt;2011<br>&gt;ISHYGDDT", true),
		new Card("All you had to do was ____ the damn ____!", true),
		new Card("The new ititeration in the Call of Duty franchise has players fighting off ____ deep in the jungles of ____ ", true),
		new Card("Check your privilege, you ____ ____.", true),
		new Card("Jill, here's a ____. It might come in handy if you, the master of ____, take it with you. ", true),
		new Card("____ is a pretty cool guy, eh ____ and doesn't afraid of anything.", true),
		new Card("It's like ____with ____!", true),
		new Card("Ironic ____ is still ____.<br><br>(same in both blanks)", true),
	}, responseCards = new Card[]{
		new Card("the 8 million jews.", false),
		new Card("Honk! Honk!", false),
		new Card("Hideo Kojima", false),
		new Card("Alright", false),
		new Card("LIQUID!", false),
		new Card("BROTHER!", false),
		new Card("Gaben", false),
		new Card("Kirby's Air Ride", false),
		new Card("Yume Nikki", false),
		new Card("HL3 confirmed!", false),
		new Card("That feel", false),
		new Card("Tim Buckley", false),
		new Card("Bum Tickley", false),
		new Card("Star Wars: Battlefront", false),
		new Card("Silent Hill", false),
		new Card("Harry Mason", false),
		new Card("James Sunderland", false),
		new Card("the plot of MGS4", false),
		new Card("Kramer", false),
		new Card("no games", false),
		new Card("Words, Words, Words", false),
		new Card("Le /v/ culture", false),
		new Card("Mods", false),
		new Card("Furfags", false),
		new Card("My waifu", false),
		new Card("Jews", false),
		new Card("Max Payne", false),
		new Card("L.A. Noire", false),
		new Card("Call of Duty 4", false),
		new Card("Cowadooty Franchise", false),
		new Card("Master Chef", false),
		new Card("Samus Aran", false),
		new Card("Kamiya", false),
		new Card("The red ring of death", false),
		new Card("Toady", false),
		new Card("the mustard race", false),
		new Card("Klonies", false),
		new Card("Valve", false),
		new Card("source engine", false),
		new Card("Wii-tier graphics", false),
		new Card("brown and bloom", false),
		new Card("FUCKING GAMESTOP", false),
		new Card("Doritoes", false),
		new Card("Dante, but you an call him Dante the demon killer", false),
		new Card("FUCK YOU", false),
		new Card("Princess Peach", false),
		new Card("Ronnie", false),
		new Card("Wreck-It Ralph", false),
		new Card("Destroy-It Dan", false),
		new Card("Rape-It Randy", false),
		new Card("Bayonetta", false),
		new Card("Fifa 2014", false),
		new Card("Superman 64", false),
		new Card("E.T. for Atari", false),
		new Card("Dark Souls", false),
		new Card("Devil May Cry", false),
		new Card("Wubs", false),
		new Card("a custom built PC", false),
		new Card("making an email to gabe newell one post at a time", false),
		new Card("Warioware", false),
		new Card("Earthbound", false),
		new Card("Pikmen", false),
		new Card("Egoraptor", false),
		new Card("Cory in the House", false),
		new Card("Katawa Shoujio", false),
		new Card("Donte", false),
		new Card("/pol/", false),
		new Card("/a/", false),
		new Card("Traps", false),
		new Card("Capitan Falcon", false),
		new Card("knowing that feel", false),
		new Card("my sides", false),
		new Card("wagglan", false),
		new Card("playing vidya", false),
		new Card("being a casual fuck", false),
		new Card("JonTron", false),
		new Card("Two Best Friends", false),
		new Card("Tropes vs Women in Video Games", false),
		new Card("Anita", false),
		new Card("Wiimote", false),
		new Card("Xbox Hueg", false),
		new Card("Japan Time", false),
		new Card("the orignal Xbox controller", false),
		new Card("Solid Snake's Ass", false),
		new Card("Big Boss", false),
		new Card("Kirby", false),
		new Card("Waluigi", false),
		new Card("Geno", false),
		new Card("Ridley", false),
		new Card("GLaDOS", false),
		new Card("Shigeru Miyamoto", false),
		new Card("Mother 3", false),
		new Card("Shigesato Itoi", false),
		new Card("Alexey Pajinov", false),
		new Card("Sam & Max", false),
		new Card("Banjo-Kazooie", false),
		new Card("Hank Hill", false),
		new Card("Pheonix Wright", false),
		new Card("the orange gem from Bejeweled&trade;", false),
		new Card("thowing bottles of holy water in the original Castlevania", false),
		new Card("using your PC as a heater in the winter", false),
		new Card("Wii Fit Trainer", false),
		new Card("Nanomachines, son", false),
		new Card("Creating a LttP vs Majora's Mask", false),
		new Card("Following the damn train", false),
		new Card("Kotaku", false),
		new Card("checking your privledge", false),
		new Card("having fun", false),
		new Card("Sanic", false),
		new Card("Sanic Adventure 2", false),
		new Card("Civillization IV", false),
		new Card("League of Legends", false),
		new Card("DoTA 2", false),
		new Card("HoN", false),
		new Card("asking br? when joining a server", false),
		new Card("Geralt", false),
		new Card("Halo", false),
		new Card("Doomguy", false),
		new Card("Regginator", false),
		new Card("tfw no qt gf", false),
		new Card("Atelier", false),
		new Card("Asura", false),
		new Card("Obsidrones", false),
		new Card("Nintenyearolds", false),
		new Card("Xbots", false),
		new Card("Sonyggers", false),
		new Card("Hitscan", false),
		new Card("xX420blazeitXx", false),
		new Card("Sakurai", false),
		new Card("blowing into a catridge", false),
		new Card("Dragon Dildos", false),
		new Card("Nintendo", false),
		new Card("Sony", false),
		new Card("Microsoft", false),
		new Card("Sega", false),
		new Card("Konami", false),
		new Card("Game Freak", false),
		new Card("Fez", false),
		new Card("Cave Story", false),
		new Card("Wololololololololo", false),
		new Card("pirating games because you hate the government", false),
		new Card("New Super Luigi Bros", false),
		new Card("the Demoman (who takes skill)", false),
		new Card("the Pyro (who takes skill)", false),
		new Card("on disk DLC", false),
		new Card("sports games the come out year after year", false),
		new Card("Ass Creed", false),
		new Card("playing counterstrike too seriously", false),
		new Card("Minecraft", false),
		new Card("Notch", false),
		new Card("Buzzwords", false),
		new Card("OFF by Mortis Ghost", false),
		new Card("an indie dev that no one knows about", false),
		new Card("the Secret of Monkey Island", false),
		new Card("watching let's plays on youtube", false),
		new Card("grumpy dumpies", false),
		new Card("Spaghetti", false),
		new Card("the best Final Fantasy game", false),
		new Card("Grayson Hunt", false),
		new Card("not completing all the side quests", false),
		new Card("artificial difficulty", false),
		new Card("padding", false),
		new Card("artificial fun", false),
		new Card("Matt and Pat", false),
		new Card("Hamberger Helper", false),
		new Card("Yahtzee", false),
		new Card("iJustine", false),
		new Card("Jack Thompson", false),
		new Card("rebbit", false),
		new Card("The /v/idya gaem awards", false),
		new Card("Emi (from Katawa Shoujo)", false),
		new Card("Rin (from Katawa Shuojo)", false),
		new Card("Lilly (from Katawa Shuojo)", false),
		new Card("Hanako (from Katawa Shuojo)", false),
		new Card("Shizune (from Katawa Shuojo)", false),
		new Card("Misha (from Katawa Shuojo)", false),
		new Card("Kenji (from Katawa Shuojo)", false),
		new Card("The Last of Us", false),
		new Card("/v/", false),
		new Card("Video Games", false),
		new Card("NSA", false),
		new Card("Christopher Robin", false),
		new Card("The Master Race", false),
		new Card("/mlp/", false),
		new Card("Bronies", false),
		new Card("/vg/", false),
		new Card("/vr/", false),
		new Card("/vp/", false),
		new Card("p2w", false),
		new Card("the delay time of Duke Nukem Forever", false),
		new Card("Duke Nukem", false),
		new Card("WoW", false),
		new Card("Worth the Weight", false),
		new Card("anything but video games", false),
		new Card("Tom Preston", false),
		new Card("Andrew Dobson", false),
		new Card("nogames", false),
		new Card("2spooky", false),
		new Card("599 US Dollars ", false),
		new Card("Eight Point Eight", false),
		new Card("RAGE", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Vidya";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Vidya";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}