package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckRPAnons extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("_ doesn't need to be judged right now."),
		new Card("_ is a terrible thing to do to the _!"),
		new Card("_ &amp; _: Worst mods ever."),
		new Card("/_ all over this post."),
		new Card("/_ delicately from the butt."),
		new Card("/slides hand up your _."),
		new Card("_ is not an island."),
		new Card("_ runs into the forest, screaming."),
		new Card("_ was better before the anon meme."),
		new Card("We'd love to have you at _ Island!"),
		new Card("Bad news guys, my parents found that thread involving _."),
		new Card("But what are your thoughts on _?"),
		new Card("Chaos ensued when Wankgate banned _."),
		new Card("Cute, fun and _."),
		new Card("Does anyone _? I feel like the only one."),
		new Card("Excuse me, but I identify as _."),
		new Card("Great, another _ event."),
		new Card("How can there be a group of people more _ than us?"),
		new Card("How's my driving?"),
		new Card("I can only _ if I feel a deep emotional connection."),
		new Card("I can't believe we just spent a whole page wanking about _."),
		new Card("I have a PHD in _."),
		new Card("I just benchpressed, like, 14 _."),
		new Card("I need deets on _, stat."),
		new Card("I predict _ will close by the end of the year."),
		new Card("I randomly began to _ and _ came galloping up the stairs."),
		new Card("I see Wankgate's bitching about _ again."),
		new Card("I'm literally shaking and _ right now."),
		new Card("I'm married to _ on the astral plane."),
		new Card("I'm really into _, so please don't kinkshame."),
		new Card("I'm sad we lost _ in the exodus from LJ to DW."),
		new Card("I'm starting a game where the characters are stuck in _."),
		new Card("I'm taking commissions for _!"),
		new Card("How dare you not warn for _! Don't you know how triggering that is?"),
		new Card("In this world, sexual roles are divided into three categories: the _, the _, and the _"),
		new Card("It's _ o'clock."),
		new Card("ITT: _."),
		new Card("Join my new game about _!"),
		new Card("Keep fucking that _."),
		new Card("Let me tell you about _."),
		new Card("Log in and _."),
		new Card("My favorite thread is the one where _ has kinky sex with _."),
		new Card("My headcanon is that _ is _."),
		new Card("My OTP: _ x _."),
		new Card("New game idea! You're kidnapped by _ and forced into _."),
		new Card("no actually i don't care at all, i don't even _. :))))"),
		new Card("OMG you guys I have so many feels about _!"),
		new Card("Only _ would play from _."),
		new Card("Raising money for _! Please replurk!"),
		new Card("RPAnons made me _."),
		new Card("SHUT UP ABOUT YOUR _."),
		new Card("Signal boosting for _!"),
		new Card("Since _ is on hiatus, fans have migrated to _."),
		new Card("Someone just stuck their head out of the window and screamed "),
		new Card("Someone left a _ out in the rain."),
		new Card("That _. You know, *that* one."),
		new Card("The _ is happy."),
		new Card("The perfect username for my next character: _."),
		new Card("The thing I hate most about RP is _."),
		new Card("Their _ are of age."),
		new Card("There are too many memes about _."),
		new Card("There is no _ in Holly Heights."),
		new Card("We need a new post. This one smells like _."),
		new Card("Why was I asked for app revisions?"),
		new Card("Why was I banned?"),
		new Card("Who apps _ to a sex game?"),
		new Card("Who should I play next?"),
		new Card("You can't fist _."),
		new Card("You sound _, tbh.")
	}, responseCards = new Card[]{
		new Card("Rule 63."),
		new Card("'The' Hateboner."),
		new Card("(I glances.)"),
		new Card("(unsure)."),
		new Card("Too rad to be cis."),
		new Card("A 'shopped vendetta."),
		new Card("A 5-page-long kink list."),
		new Card("A bouquet of dicks."),
		new Card("A creepy Corruption of Champions OC."),
		new Card("A funny name for Benedict Cumberbatch."),
		new Card("A genderswapped vampire AU Cloud Strife."),
		new Card("A glopping noise."),
		new Card("A misfire."),
		new Card("A paid account full of nothing but terrible fanart icons."),
		new Card("A penis approximately the size and shape of a Guinness can."),
		new Card("A shitty urban fantasy OC."),
		new Card("A spooky jamjar."),
		new Card("A tag so boring it makes you want to delete all of your journals."),
		new Card("A tragic Christmas hang-gliding accident."),
		new Card("Accidental video posts."),
		new Card("Alpha/Beta/Omega."),
		new Card("Amatomnes."),
		new Card("An awful fandom OC who's married to the main character."),
		new Card("Anonfailing."),
		new Card("Another boring wank about f/f."),
		new Card("Another fucking TFLN meme."),
		new Card("App revisions."),
		new Card("Ataraxion."),
		new Card("Autistic gypsies."),
		new Card("Baby penis."),
		new Card("Bakerstreet."),
		new Card("Begging for asspats."),
		new Card("Being really passive-aggressive because you "),
		new Card("Being soulbonded to a Homestuck character."),
		new Card("Broccoli trees."),
		new Card("Butthurt."),
		new Card("Calling long-distance to demand tags from your RP partner."),
		new Card("Cape and Cowl."),
		new Card("Changed."),
		new Card("Chronic Lyme disease."),
		new Card("Circlejerking."),
		new Card("City of Ariel."),
		new Card("Cloud being eaten by a chocobo."),
		new Card("Cockhopping."),
		new Card("Constructive criticism."),
		new Card("Dangan Ronpa's crazy fandom."),
		new Card("Dean/Goku."),
		new Card("Dear Mun."),
		new Card("Discedo."),
		new Card("Drama Drama Duck."),
		new Card("Dropping the thread after two tags because it sucks."),
		new Card("ECATS? CAT DESK? WE SCAT?"),
		new Card("An incest ship."),
		new Card("Entranceway."),
		new Card("Everyone turning into ponies."),
		new Card("Exit Void."),
		new Card("Exsilium."),
		new Card("FACT IT!"),
		new Card("Fad fandoms."),
		new Card("Falling in love with your RP partner."),
		new Card("Feeling like the only one."),
		new Card("Flouncing. The more dramatic, the better."),
		new Card("Fucking that chicken."),
		new Card("Generic white male actor PBs."),
		new Card("Haven."),
		new Card("Hellion."),
		new Card("Hetalia's annoying fandom."),
		new Card("High Seas."),
		new Card("Highlandering."),
		new Card("Hitting the cervix with your dick."),
		new Card("Holly Heights."),
		new Card("Homestuck's insane fandom."),
		new Card("Icon elitism."),
		new Card("Icons that aren't 100x100."),
		new Card("Kink shaming."),
		new Card("Legbeards."),
		new Card("Literally shaking and crying."),
		new Card("lol so randumb!!!!111 XD"),
		new Card("Lovingly describing your character's throbbing cock."),
		new Card("Luceti."),
		new Card("Mpreg."),
		new Card("Musedumping."),
		new Card("Neckbeards."),
		new Card("Needing to lei down."),
		new Card("Not posting deets."),
		new Card("Nymphomanic werewolf Rei Ayanami. On rollerskates."),
		new Card("One-pixel borders."),
		new Card("One-word replies."),
		new Card("Paradisa."),
		new Card("Passive-aggressive editing."),
		new Card("Pigeon superpowers."),
		new Card("Pillow queens."),
		new Card("Only playing for ships."),
		new Card("Polychromatic."),
		new Card("Posting to Wankgate logged in."),
		new Card("Pregnancy plots."),
		new Card("Pretentious, illegible formatting."),
		new Card("Queefing on someone's dick."),
		new Card("Rebutle."),
		new Card("Renne."),
		new Card("Replying to everyone on ATP because you're just that desperate."),
		new Card("Reserving a popular character and never apping."),
		new Card("Roleplaying One Direction slash."),
		new Card("Route 29."),
		new Card("Roxanne Ritchie's vagina."),
		new Card("RPAnons."),
		new Card("Ruby City."),
		new Card("Rushing to dear_mun to post about the latest global tragedy in-character."),
		new Card("St-stuttered t-typing."),
		new Card("Obviously sameanoning."),
		new Card("Sample prompts."),
		new Card("Save The Earth."),
		new Card("Scathing anonymous criticism."),
		new Card("Scrambling to pass AC at the last minute."),
		new Card("Shounen retards."),
		new Card("Signal boosting an obvious hoax."),
		new Card("Slacktivism."),
		new Card("Social justice warriors."),
		new Card("Sora and Emperor Palpatine in an awkward, skeezy relationship."),
		new Card("Springing rape scenarios on people without asking."),
		new Card("Stormy's latest alias."),
		new Card("Superwholockvengers."),
		new Card("Surprise futa."),
		new Card("Tag nirvana."),
		new Card("Tentabulge headcanons."),
		new Card("Terminal Tokyo."),
		new Card("That Kronk."),
		new Card("That Patchouli."),
		new Card("The Box."),
		new Card("The dominate one."),
		new Card("The Love Hotel."),
		new Card("The medium divide."),
		new Card("The myriad of songs you associate with your OTP."),
		new Card("The paid account fairy."),
		new Card("The Royal Baby."),
		new Card("The Salkia Island award."),
		new Card("The whole game jumping on the villain before they have a chance to be villainous."),
		new Card("TL;DR."),
		new Card("TMI public plurks."),
		new Card("Touhou lesbians nobody wants to play with."),
		new Card("Tower of Animus."),
		new Card("Tryhards."),
		new Card("Tittybabies."),
		new Card("Tumblrinas."),
		new Card("Two lonely neckbeards playing out futa together because nobody else will."),
		new Card("Two years' worth of semen."),
		new Card("tYPING LIKE THIS???????? oH MY GKFOODODD??????"),
		new Card("Unironically using the word "),
		new Card("Username elitism."),
		new Card("Username squatting."),
		new Card("Vatheon."),
		new Card("Viewing anoncomms in flat-view like a heathen."),
		new Card("Visualosities."),
		new Card("Wank terriers."),
		new Card("Wankgate."),
		new Card("Wanking about games you aren't in."),
		new Card("Wanking about a private musebox."),
		new Card("wgar."),
		new Card("Whiteknighting."),
		new Card("Whoremongers."),
		new Card("Wrapping your hands around a penis and twisting in opposite directions."),
		new Card("Yaoi."),
		new Card("Zodion.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] RPAnons";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Anons";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}