package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckVidya extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("Why are you making chocolate pudding at 4 in the morning?"),
		new Card("The newest feature of the Xbox One is _."),
		new Card("PS3: It only does  _."),
		new Card("The new TF2 promo items are based on _."),
		new Card("If Gordon Freeman spoke, what would he talk about?"),
		new Card("&gt;tfw when _."),
		new Card("All you had to do was follow the damn _, CJ!"),
		new Card("Liquid! How can you still be alive?"),
		new Card("What can change the nature of a man?"),
		new Card(" Microsoft revealed that the Xbox One's demos had actually been running on _ "),
		new Card("What if _ was a girl?"),
		new Card("What did I preorder at gamestop?"),
		new Card("_ confirmed for Super Smash Bros!"),
		new Card("Based _."),
		new Card("The newest IP from Nintendo, Super _ Bros. "),
		new Card("_ only, no items, Final Destination. "),
		new Card("Enjoy _ while you play your Xbox one!"),
		new Card("The future of gaming lies with the _."),
		new Card("The best way to be comfy when playing video games is with _."),
		new Card("_ has no games."),
		new Card("PC gamers have made a petition to get _ on their platform."),
		new Card("The new Nintendo _ is a big gimmick. "),
		new Card("&gt;implying you aren't _"),
		new Card("WHAT IS A MAN?"),
		new Card("What is a ___ but a _?"),
		new Card("WE WILL DRAG THIS ___ INTO THE 21ST CENTURY."),
		new Card("Wake up, Mr. Freeman. Wake up and _."),
		new Card("I'm in ur base, _"),
		new Card("Pop Quiz: Beatles Song- ___ terday."),
		new Card(" ___ would like to play."),
		new Card("A mod of doom was made that was based off of _."),
		new Card("I really didn't like what they did with the _ Movie adaption."),
		new Card("HEY, GOLLEN PALACE? HOW U SAY _ IN CHINESE?', 0, 1, "),
		new Card("Pumpkin doesn't want this."),
		new Card("NEXT TIME ON GAME GRUMPS: _."),
		new Card("I used to be an adventurer like you, until _."),
		new Card("Yeah, well, my dad works for _."),
		new Card("Kotaku addresses sexism in _ in their latest article."),
		new Card("Get double XP for Halo 3 with purchase of _."),
		new Card("LoL stole their new character design off of _."),
		new Card("_ is the cancer killing video games."),
		new Card("Suffer, like _ did."),
		new Card("It's like _ with guns!"),
		new Card("Is a man not entitiled to _?"),
		new Card("_ has changed."),
		new Card("But you can call me _ the _. Has a nice ring to it dontcha think?"),
		new Card("Objective: _"),
		new Card("EA Sports! It's _."),
		new Card("_ is waiting for your challenge!"),
		new Card("_ sappin' my sentry. "),
		new Card("I'm here to _ and chew bubble gum, and I'm all out of gum."),
		new Card("I've covered _, you know."),
		new Card("It's dangerous to go alone! Take this:"),
		new Card("You were almost a _ sandwich!"),
		new Card("That's the second biggest _ I've ever seen!"),
		new Card("_. _ never changes."),
		new Card("_ has changed. "),
		new Card("You have been banned. Reason: _."),
		new Card("The newest trope against women in video games: _."),
		new Card("Fans started a kickstarter for a new _ game. "),
		new Card("Huh? What was that noise?"),
		new Card("Viral marketers are trying to push the new _."),
		new Card("I wouldn't call it a Battlestation, more like a _."),
		new Card("_: Gotta go fast!"),
		new Card("The best final fantasy game was _."),
		new Card("I love the _, it's so bad"),
		new Card("Valve is going to make _ 2 before they release HL3."),
		new Card("_ is a pretty cool guy"),
		new Card("Ah! Your rival! What was his name again?"),
		new Card("What's in the box, /v/?"),
		new Card("Why is the _ fandom the worst?"),
		new Card("Achievement Unlocked: _ !"),
		new Card("I'm _ under the table right now!"),
		new Card("brb guys, _ break"),
		new Card("OH MY GOD JC, A _"),
		new Card("wooooooow, it took all 3 of you to _"),
		new Card("Rev up those _, because I am sure hungry for one- HELP! HELP!"),
		new Card("_ is 2deep and edgy for you."),
		new Card("Only casuals like _."),
		new Card("The princess is in another _"),
		new Card("I have the bigger _."),
		new Card("_ TEAM RULES!!"),
		new Card("When you see it... you don't see _."),
		new Card("HEY, GOLLEN PALACE? HOW U SAY _ IN CHINESE?"),
		new Card("WHAT THE FUCK DID YOU SAY ABOUT ME YOU _?"),
		new Card("This will be the 6th time we've posted _; we've become increasingly efficient at it."),
		new Card("appealing to a larger audience"),
		new Card("we must embrace _ and burn it as fuel for out journey."),
		new Card("In Kingdom Hearts, Donald Duck will be replaced with _ ."),
		new Card("&gt;walk into gamestop<br>&gt;see _<br>&gt;walk out"),
		new Card("Because of the lastest school shooting, _ is being blamed for making kids too violent."),
		new Card("Here lies _: peperony and chease"),
		new Card("Throwaway round: Get rid of those shit cards you don't want. Thanks for all the suggestions, /v/"),
		new Card("The president has been kidnapped by _. Are you a bad enough dude to rescue the president?"),
		new Card("We _ now."),
		new Card("What is the new mustard paste?"),
		new Card("&gt;_<br>&gt;_<br>&gt;2011<br>&gt;ISHYGDDT"),
		new Card("All you had to do was _ the damn _!"),
		new Card("The new ititeration in the Call of Duty franchise has players fighting off _ deep in the jungles of _ "),
		new Card("Check your privilege, you _ _."),
		new Card("Jill, here's a _. It might come in handy if you, the master of _, take it with you. "),
		new Card("_ is a pretty cool guy, eh _ and doesn't afraid of anything."),
		new Card("It's like ____with _!"),
		new Card("Ironic _ is still _.<br><br>(same in both blanks)")
	}, responseCards = new Card[]{
		new Card("the 8 million jews."),
		new Card("Honk! Honk!"),
		new Card("Hideo Kojima"),
		new Card("Alright"),
		new Card("LIQUID!"),
		new Card("BROTHER!"),
		new Card("Gaben"),
		new Card("Kirby's Air Ride"),
		new Card("Yume Nikki"),
		new Card("HL3 confirmed!"),
		new Card("That feel"),
		new Card("Tim Buckley"),
		new Card("Bum Tickley"),
		new Card("Star Wars: Battlefront"),
		new Card("Silent Hill"),
		new Card("Harry Mason"),
		new Card("James Sunderland"),
		new Card("the plot of MGS4"),
		new Card("Kramer"),
		new Card("no games"),
		new Card("Words, Words, Words"),
		new Card("Le /v/ culture"),
		new Card("Mods"),
		new Card("Furfags"),
		new Card("My waifu"),
		new Card("Jews"),
		new Card("Max Payne"),
		new Card("L.A. Noire"),
		new Card("Call of Duty 4"),
		new Card("Cowadooty Franchise"),
		new Card("Master Chef"),
		new Card("Samus Aran"),
		new Card("Kamiya"),
		new Card("The red ring of death"),
		new Card("Toady"),
		new Card("the mustard race"),
		new Card("Klonies"),
		new Card("Valve"),
		new Card("source engine"),
		new Card("Wii-tier graphics"),
		new Card("brown and bloom"),
		new Card("FUCKING GAMESTOP"),
		new Card("Doritoes"),
		new Card("Dante, but you an call him Dante the demon killer"),
		new Card("FUCK YOU"),
		new Card("Princess Peach"),
		new Card("Ronnie"),
		new Card("Wreck-It Ralph"),
		new Card("Destroy-It Dan"),
		new Card("Rape-It Randy"),
		new Card("Bayonetta"),
		new Card("Fifa 2014"),
		new Card("Superman 64"),
		new Card("E.T. for Atari"),
		new Card("Dark Souls"),
		new Card("Devil May Cry"),
		new Card("Wubs"),
		new Card("a custom built PC"),
		new Card("making an email to gabe newell one post at a time"),
		new Card("Warioware"),
		new Card("Earthbound"),
		new Card("Pikmen"),
		new Card("Egoraptor"),
		new Card("Cory in the House"),
		new Card("Katawa Shoujio"),
		new Card("Donte"),
		new Card("/pol/"),
		new Card("/a/"),
		new Card("Traps"),
		new Card("Capitan Falcon"),
		new Card("knowing that feel"),
		new Card("my sides"),
		new Card("wagglan"),
		new Card("playing vidya"),
		new Card("being a casual fuck"),
		new Card("JonTron"),
		new Card("Two Best Friends"),
		new Card("Tropes vs Women in Video Games"),
		new Card("Anita"),
		new Card("Wiimote"),
		new Card("Xbox Hueg"),
		new Card("Japan Time"),
		new Card("the orignal Xbox controller"),
		new Card("Solid Snake's Ass"),
		new Card("Big Boss"),
		new Card("Kirby"),
		new Card("Waluigi"),
		new Card("Geno"),
		new Card("Ridley"),
		new Card("GLaDOS"),
		new Card("Shigeru Miyamoto"),
		new Card("Mother 3"),
		new Card("Shigesato Itoi"),
		new Card("Alexey Pajinov"),
		new Card("Sam & Max"),
		new Card("Banjo-Kazooie"),
		new Card("Hank Hill"),
		new Card("Pheonix Wright"),
		new Card("the orange gem from Bejeweled&trade;"),
		new Card("thowing bottles of holy water in the original Castlevania"),
		new Card("using your PC as a heater in the winter"),
		new Card("Wii Fit Trainer"),
		new Card("Nanomachines, son"),
		new Card("Creating a LttP vs Majora's Mask"),
		new Card("Following the damn train"),
		new Card("Kotaku"),
		new Card("checking your privledge"),
		new Card("having fun"),
		new Card("Sanic"),
		new Card("Sanic Adventure 2"),
		new Card("Civillization IV"),
		new Card("League of Legends"),
		new Card("DoTA 2"),
		new Card("HoN"),
		new Card("asking br? when joining a server"),
		new Card("Geralt"),
		new Card("Halo"),
		new Card("Doomguy"),
		new Card("Regginator"),
		new Card("tfw no qt gf"),
		new Card("Atelier"),
		new Card("Asura"),
		new Card("Obsidrones"),
		new Card("Nintenyearolds"),
		new Card("Xbots"),
		new Card("Sonyggers"),
		new Card("Hitscan"),
		new Card("xX420blazeitXx"),
		new Card("Sakurai"),
		new Card("blowing into a catridge"),
		new Card("Dragon Dildos"),
		new Card("Nintendo"),
		new Card("Sony"),
		new Card("Microsoft"),
		new Card("Sega"),
		new Card("Konami"),
		new Card("Game Freak"),
		new Card("Fez"),
		new Card("Cave Story"),
		new Card("Wololololololololo"),
		new Card("pirating games because you hate the government"),
		new Card("New Super Luigi Bros"),
		new Card("the Demoman (who takes skill)"),
		new Card("the Pyro (who takes skill)"),
		new Card("on disk DLC"),
		new Card("sports games the come out year after year"),
		new Card("Ass Creed"),
		new Card("playing counterstrike too seriously"),
		new Card("Minecraft"),
		new Card("Notch"),
		new Card("Buzzwords"),
		new Card("OFF by Mortis Ghost"),
		new Card("an indie dev that no one knows about"),
		new Card("the Secret of Monkey Island"),
		new Card("watching let's plays on youtube"),
		new Card("grumpy dumpies"),
		new Card("Spaghetti"),
		new Card("the best Final Fantasy game"),
		new Card("Grayson Hunt"),
		new Card("not completing all the side quests"),
		new Card("artificial difficulty"),
		new Card("padding"),
		new Card("artificial fun"),
		new Card("Matt and Pat"),
		new Card("Hamberger Helper"),
		new Card("Yahtzee"),
		new Card("iJustine"),
		new Card("Jack Thompson"),
		new Card("rebbit"),
		new Card("The /v/idya gaem awards"),
		new Card("Emi (from Katawa Shoujo)"),
		new Card("Rin (from Katawa Shuojo)"),
		new Card("Lilly (from Katawa Shuojo)"),
		new Card("Hanako (from Katawa Shuojo)"),
		new Card("Shizune (from Katawa Shuojo)"),
		new Card("Misha (from Katawa Shuojo)"),
		new Card("Kenji (from Katawa Shuojo)"),
		new Card("The Last of Us"),
		new Card("/v/"),
		new Card("Video Games"),
		new Card("NSA"),
		new Card("Christopher Robin"),
		new Card("The Master Race"),
		new Card("/mlp/"),
		new Card("Bronies"),
		new Card("/vg/"),
		new Card("/vr/"),
		new Card("/vp/"),
		new Card("p2w"),
		new Card("the delay time of Duke Nukem Forever"),
		new Card("Duke Nukem"),
		new Card("WoW"),
		new Card("Worth the Weight"),
		new Card("anything but video games"),
		new Card("Tom Preston"),
		new Card("Andrew Dobson"),
		new Card("nogames"),
		new Card("2spooky"),
		new Card("599 US Dollars "),
		new Card("Eight Point Eight"),
		new Card("RAGE")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Vidya";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Vidya";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}