package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckFurryPack extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("Personals ad: Seeking a female who doesn't mind _, might also be willing to try a male if they're _."),
		new Card("I tell everyone I'm not a furry, but I've drawn a lot of _."),
		new Card("My original species combines _ and _. It's called _."),
		new Card("_. And now I'm bleeding."),
		new Card("Suck my _."),
		new Card("I also take _ as payment for commissions."),
		new Card("_ looks pretty in all the art, but have you seen one in real life?"),
		new Card("Don't knock _ until you've tried it."),
		new Card("Once I started roleplaying _, it was all downhill from there."),
		new Card("_ are so goddamn cool."),
		new Card("_, by Bad Dragon™."),
		new Card("No, look, you don't understand. I REALLY like _."),
		new Card("I don't think my parents will ever accept that the real me is _."),
		new Card("You can try to justify _ all you want, but you don't have to be _ to realize it's just plain wrong."),
		new Card("I've been waiting all year for _."),
		new Card("I can't wait to meet up with my internet friends for _."),
		new Card("Most cats are _."),
		new Card("Taking pride in one's collection of _."),
		new Card("Did you hear about the guy that smuggled _ into the hotel?"),
		new Card("The panel I'm looking forward to most at AC this year is..."),
		new Card("My Original Character's name is _."),
		new Card("My secret tumblr account where I post nothing but _."),
		new Card("Only my internet friends know that I fantasize about _."),
		new Card("Everyone really just goes to the cons for _."),
		new Card("It all started with _."),
		new Card("I'll roleplay _, you can be _."),
		new Card("I'm no longer allowed near _ after the incident with _."),
		new Card("I've been into _ since before I hit puberty, I just didn't know what it meant."),
		new Card("Realizing, too late, the implications of your interest in _ as a child."),
		new Card("Whoa, I might fantasize about _, but I'd never actually go that far in real life."),
		new Card("I realized they were a furry when they mentioned _."),
		new Card("Everyone on this site has such strong opinions about _."),
		new Card("My landlord had a lot of uncomfortable questions for me when when he found _ in my bedroom while I was at work."),
		new Card("I'm not even aroused by normal porn anymore, I can only get off to _ or _."),
		new Card("_? Oh, yeah, I could get my mouth around that."),
		new Card("What wouldn't I fuck?"),
		new Card("When I thought I couldn't go any lower, I realized I would probably fuck _."),
		new Card("I knew my boyfriend was a keeper when he said he'd try _, just for me."),
		new Card("Fuck _, get _."),
		new Card("I would bend over for _."),
		new Card("I think having horns would make _ complicated."),
		new Card("In my past life, I was _."),
		new Card("_ is my spirit animal."),
		new Card("_. This is what my life has come to."),
		new Card("I'm not even sad that I devote at least six hours of each day to _."),
		new Card("I never felt more accomplished than when I realized I could fit _ into my ass."),
		new Card("Yeah, I know I have a lot of _ in my favorites, but I'm just here for the art."),
		new Card("I'm not a "),
		new Card("Okay, _? Pretty much the cutest thing ever."),
		new Card("_. Yeah, that's a pretty interesting way to die."),
		new Card("I didn't believe the rumors about _, until I saw the videos."),
		new Card("I knew I needed to leave the fandom when I realized I was _."),
		new Card("After being a furry for so long, I can never see _ without getting a little aroused."),
		new Card("It's really hard not to laugh at _."),
		new Card("If my parents ever found _, I'd probably be disowned."),
		new Card("_ ruined the fandom."),
		new Card("The most recent item in my search history."),
		new Card("Is it weird that I want to rub my face on _?"),
		new Card("_? Oh murr."),
		new Card("I never thought I'd be comfortable with _, but now it's pretty much the only thing I masturbate to."),
		new Card("My next fursuit will have _."),
		new Card("I'm writing a porn comic about _ and _. "),
		new Card("I tell everyone that I make my money off "),
		new Card("Oh, you're an artist? Could you draw _ for me?"),
		new Card("Everyone thinks they're so great, but the only thing they're good at drawing is _."),
		new Card("They're just going to spend all that money on _."),
		new Card("While everyone else seems to have a deep, instinctual fear of _, it just turns me on."),
		new Card("Lying about having _ to get donations, which you spend on _."),
		new Card("It's not bestiality, it's _."),
		new Card("Everyone thinks that because I'm a furry, I'm into _. Unfortunately, they're right."),
		new Card("I'm only gay for _."),
		new Card("Excuse you, I'm a were-_."),
		new Card("If you like it, then you should put _ on it."),
		new Card("My girlfriend won't let me do _."),
		new Card("The most pleasant surprise I've had this year."),
		new Card("I knew I had a problem when I had to sell _ to pay for _."),
		new Card("I'm about 50% _."),
		new Card("_: Horrible tragedy, or sexual opportunity?"),
		new Card("It's a little worrying that I have to compare the size of _ to beverage containers."),
		new Card("Hey, you guys wanna come back to my place? I've got _ and _."),
		new Card("Jizzing all over _."),
		new Card("It's just that much creepier when 40-year-old men are into _."),
		new Card("_ is no substitute for social skills, but it's a start."),
		new Card("The real reason I got into the fandom? _."),
		new Card("_ are definitely the new huskies."),
		new Card("I remember when _ was just getting started."),
		new Card("When no one else is around, sometimes I consider doing things with _."),
		new Card("Actually coming inside _."),
		new Card("I don't know how we got on the subject of dragon cocks, but it probably started with _."),
		new Card("_ is a shining example of what those with autism can really do."),
		new Card("It is my dream to be covered with _."),
		new Card("_ fucking _. Now that's hot."),
		new Card("Would you rather suck _, or get dicked by _?"),
		new Card("It never fails to liven up the workplace when you ask your coworkers if they'd rather have sex with _ or _."),
		new Card("HELLO FURRIEND, HOWL ARE YOU DOING?"),
		new Card("What are the two worst cards in your hand right now?"),
		new Card("Nobody believes me when I tell that one story about walking in on _."),
		new Card("You don't know who _ is? They're the one that draws _."),
		new Card("You sometimes wish you'd encounter _ while all alone, in the woods. With a bottle of lube."),
		new Card("I used to avoid talking about _, but now it's just a part of normal conversation with my friends.")
	}, responseCards = new Card[]{
		new Card("Dragon dildos."),
		new Card("Adam Wan."),
		new Card("Non-consensual sex with Zaush."),
		new Card("My tailhole."),
		new Card("Adoptables with visible genitalia."),
		new Card("An embarrassingly long F-List profile."),
		new Card("Catching STDs at conventions."),
		new Card("Fursuit adventures."),
		new Card("A semen-stained fursuit."),
		new Card("Fake furry girls."),
		new Card("That one straight guy at the party."),
		new Card("An apartment full of internet-obsessed losers."),
		new Card("People who cosplay at furry conventions."),
		new Card("Fursuiters at anime conventions."),
		new Card("Embarrassing craigslist ads."),
		new Card("Pounced.org."),
		new Card("A large, flared Chance."),
		new Card("Stretching your anus in preparation for horse cock."),
		new Card("A hermaphrodite foxtaur."),
		new Card("Babyfurs."),
		new Card("Uncomfortably attractive animals."),
		new Card("Confusing feelings about cartoon characters."),
		new Card("Krystal, the fox."),
		new Card("Bowser's sweaty balls."),
		new Card("A furpile."),
		new Card("The stench of half a dozen unwashed bronies."),
		new Card("Intimacy with the family dog."),
		new Card("Horses."),
		new Card("Fursecution."),
		new Card("Chakats."),
		new Card("Otherkin."),
		new Card("Heated debates about human genitalia versus animal genitalia."),
		new Card("Taking the knot."),
		new Card("Really, really liking Disney's Robin Hood."),
		new Card("Applying your obscure, unrealistic fetishes to 90's cartoon characters."),
		new Card("The texture and color of raw meat."),
		new Card("An oversized clitoris that acts as a functional penis."),
		new Card("A hermaphrodite snow leopard."),
		new Card("Drawing furry porn."),
		new Card("Lovingly rendered dragon anus."),
		new Card("Cloaca."),
		new Card("Animal genitalia."),
		new Card("Motherfucking wolves."),
		new Card("Christian furries."),
		new Card("Barbed penises."),
		new Card("Two knots."),
		new Card("A really attractive wolf."),
		new Card("A slutty gay fox."),
		new Card("A surprisingly attractive anteater."),
		new Card("FUCK YOU, I'M A DRAGON."),
		new Card("Tumbles, the Stair Dragon."),
		new Card("Furry Weekend Atlanta."),
		new Card("Further Confusion."),
		new Card("AnthroCon."),
		new Card("Literally a bucket of semen."),
		new Card("Sexual interest in pretty much anything with a hole."),
		new Card("Attraction to pretty much anything with a penis."),
		new Card("Transformation porn."),
		new Card("Anatomically incorrect genitalia."),
		new Card("When you catch yourself glancing at the crotches of animated characters."),
		new Card("Belly rubs leading to awkward boners."),
		new Card("Scritches."),
		new Card("Lifting your tail."),
		new Card("Experimenting with fisting."),
		new Card("Bad decisions."),
		new Card("A little bitch."),
		new Card("A lime Citra."),
		new Card("Sergals."),
		new Card("An autistic knife fight."),
		new Card("The noises red pandas make during sex."),
		new Card("About 16 ounces of horse semen."),
		new Card("Dog cum."),
		new Card("Oral knotting."),
		new Card("Leaving your orifices bloody and sore."),
		new Card("Rubbing peanut butter on your genitals."),
		new Card("Bad Dragon&trade; cumlube."),
		new Card("Piss."),
		new Card("Smells."),
		new Card("When "),
		new Card("Forgetting which set of fursuit paws you use for handjobs."),
		new Card("A strategically placed hole."),
		new Card("Shitting on my face."),
		new Card("Barking at strangers."),
		new Card("Sitting on your face."),
		new Card("Spending more money on commissions than food in a given week."),
		new Card("A dick so big you have to give it a hugjob."),
		new Card("The fine line between feral and outright bestiality."),
		new Card("Anal training."),
		new Card("Discovering monster porn."),
		new Card("Realizing that rimming is pretty cool."),
		new Card("Endearing social ineptitude."),
		new Card("All this lube."),
		new Card("That thing that gives your dick a knot IRL."),
		new Card("Gay."),
		new Card("Really, truly heterosexual."),
		new Card("Drenching your fursuit in Febreeze."),
		new Card("That time you let your dog go a little further than just sniffing your crotch."),
		new Card("Poodles with afros."),
		new Card("Offensively stereotyped African animals."),
		new Card("A sassy lioness."),
		new Card("Surprise hermaphrodites."),
		new Card("Taking special interest in nature documentaries."),
		new Card("Becoming a veterinarian for all the wrong reasons."),
		new Card("The premise of every furry comic ever."),
		new Card("Anal sex you didn't know you wanted."),
		new Card("The incredibly satisfying sound it makes when you pull it out."),
		new Card("Bear tits."),
		new Card("Big cute paws."),
		new Card("Paws."),
		new Card("Furry porn, shamelessly taped to the walls."),
		new Card("Grabby-paws."),
		new Card("Masturbating, with claws."),
		new Card("Pawing-off."),
		new Card("Tail-sex."),
		new Card("Mary, the anthro mare."),
		new Card("Natascha, the anthro husky."),
		new Card("Nipple buffet."),
		new Card("Crotch-tits."),
		new Card("The tailstar tango."),
		new Card("Furries in heat."),
		new Card("Fantasizing about sex with just about every monster you encounter in your video game."),
		new Card("Impure thoughts about Kobolds."),
		new Card("Erotic roleplay."),
		new Card("Monsters with bedroom eyes."),
		new Card("Accurate avian anatomy."),
		new Card("Getting fur stuck in your teeth."),
		new Card("Getting feathers stuck in your teeth."),
		new Card("Ignoring a person's faults because their character is hot."),
		new Card("Discovering that it's never just a big vagina."),
		new Card("Dragoneer."),
		new Card("A horny dragon."),
		new Card("A sexually frustrated griffon."),
		new Card("Species stereotypes."),
		new Card("HELLO FURRIEND, HOWL ARE YOU DOING."),
		new Card("Convention sluts."),
		new Card("Horns and hooves."),
		new Card("Being 'prison gay.'"),
		new Card("Microwaving diapers."),
		new Card("Adorable dog people."),
		new Card("Sexy the Cat."),
		new Card("SecondLife."),
		new Card("The Gay Yiffy Club."),
		new Card("Hyper-endowed squirrels."),
		new Card("A spider furry who isn't even into bondage."),
		new Card("Being really, really into monsters."),
		new Card("Sexual arousal from children's cartoons."),
		new Card("No males, no herms, no cuntboys, no shemales, no trannys, no furries, no aliens, no vampires, and no werewolves. ONLY STRAIGHT OR BI HUMAN FEMALES."),
		new Card("Overcompensating with a huge horse penis."),
		new Card("A fedora enthusiast."),
		new Card("A tongue-beast."),
		new Card("Frisky tentacles."),
		new Card("A very steampunk rat."),
		new Card("Canine superiority."),
		new Card("Oviposition."),
		new Card("Flares."),
		new Card("Dogs wearing panties."),
		new Card("Monster boys in lingerie."),
		new Card("Power bottoms."),
		new Card("Sheath licking."),
		new Card("Sex with Pok&eacute;mon."),
		new Card("Making out with dogs."),
		new Card("YouTube videos of horse breeding."),
		new Card("Pissing on your significant other to show ownership."),
		new Card("Being able to recognize your friends by the scent of their asses."),
		new Card("A notebook full of embarrassing niche porn sketches."),
		new Card("Cockvore."),
		new Card("A prehensile penis."),
		new Card("Puns involving the word 'knot.'"),
		new Card("Jerking off on an unconscious friend's feet."),
		new Card("CrusaderCat."),
		new Card("Your Character Here.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Sodomy Dog's Furry Pack";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Furry";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}