package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckNorthernlion extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("____ caused Northernlion to take stupid damage.", true),
		new Card("____ Is the best item in The Binding of Isaac.", true),
		new Card("____ is the worst item in The Binding of Isaac.", true),
		new Card("____ is/are Northernlion's worst nightmare.", true),
		new Card("____: The Northernlion Story.", true),
		new Card("____? Well, I won't look a gift horse in the mouth on that one.", true),
		new Card("'Hey everybody and welcome to Let's Look At ____!'", true),
		new Card("As always, I will ____ you next time!", true),
		new Card("But that ____ has sailed.", true),
		new Card("Even ____ is/are better at video games than Northernlion.", true),
		new Card("Everything's coming up ____.", true),
		new Card("Finding something like ____ would turn this run around.", true),
		new Card("Fuck the haters, this is ____.", true),
		new Card("Get in my ____ zone.", true),
		new Card("I can do ____ and die immediately afterward.", true),
		new Card("I don't even see ____ anymore; all I see are blondes, brunettes, redheads...", true),
		new Card("I'm in the permanent ____ state.", true),
		new Card("If sloth ____ are wrong I don’t want to be right.", true),
		new Card("Invaded the world of ____.", true),
		new Card("It's ____, ya dangus!", true),
		new Card("JSmithOTI: Total ____.", true),
		new Card("Legend has it, the Thug of Porn was arrested for ____.", true),
		new Card("Let's Look At: ____.", true),
		new Card("Northernlion's latest novelty Twitter account is @____.", true),
		new Card("More like the Duke of ____, right?", true),
		new Card("No one man should have all that ____.", true),
		new Card("Northernlion has been facing ridicule for calling ____ a rogue-like.", true),
		new Card("Northernlion always forgets the name of ____.", true),
		new Card("Northernlion's refusal to Let's Play ____ was probably a good call.", true),
		new Card("Of all the things that Ryan and Josh have in common, they bond together through their mutual love of ____.", true),
		new Card("One thing Northernlion was right about was ____.", true),
		new Card("Praise the ____!", true),
		new Card("Recently, Northernlion has felt woefully insecure due to ____.", true),
		new Card("Roguelike? How about ___-like.", true),
		new Card("Sometimes, a man's just gotta ____.", true),
		new Card("The hero of the stream was ____.", true),
		new Card("The stream was going well until ____.", true),
		new Card("The Youtube chat proved ineffective, so instead we had to communicate via ____.", true),
		new Card("This new game is an interesting ____-like-like.", true),
		new Card("We're rolling in ____!", true),
		new Card("Whenever I ___, take a drink.", true),
		new Card("Today's trivia topic is ____.", true),
		new Card("What do you give to the CEO of Youtube as a gift?", true),
		new Card("The only way NL is ever going to make it to Hell in Spelunky is by using ____.", true),
		new Card("Welcome back to The Binding of Isaac. Today's challenge run will be based on  ____.", true),
		new Card("Well there's nothing wrong with ____ by any stretch of the imagination.", true),
		new Card("I'd sacrifice ____ at the Altar.", true),
		new Card("Fox would still be here if not for ____.", true),
		new Card("I wasn't even that drunk! I just had some ____, ____, and ____.", true),
		new Card("____ was indicted on account of ____.", true),
		new Card("____: The ____ Story.", true),
		new Card("Hello everybody, welcome to a new episode of ____ plays ____.", true),
		new Card("I beat Blue Baby with only ____ and ____!", true),
		new Card("Northernlion has alienated fans of ____ by calling them ____.", true),
		new Card("Northernlion was fired from his teaching job and had to flee South Korea after an incident involving  ____ and ____.", true),
		new Card("Northernlion's doctor diagnosed him today with ____, an unfortunate condition that would lead to ____.", true),
		new Card("And now we're going to be fighting ____ on ____.", true),
		new Card("Dang it, ____!", true),
		new Card("____ was full of leeches.", true),
		new Card("Pimp your ___!", true),
		new Card("My apologies to the ____ estate.", true),
		new Card("What interrupted the #NLSS?", true),
		new Card("Travel by ____.", true),
		new Card("The stream broke when Ryuka stepped on the ____ key.", true),
		new Card("Say that to my face one more time and I'll start ____.", true),
		new Card("Oh my god, he's using ____ magic!", true),
		new Card("Krazy Mike lost to ____!", true),
		new Card("What would you do if Ohm really did just die?", true),
		new Card("____ has invaded!", true),
		new Card("We're having technical difficulties due to ____.", true),
		new Card("JSmithOTI is referred to as a Scumlord, but his friends call him ____.", true),
		new Card("Ohmwrecker is known for his MLG online play. What people don't know is that he's also MLG at ____.", true),
		new Card("Follow MichaelALFox on Twitter and you can see pictures of ____.", true),
		new Card("After Mars, ____ is the next furthest planet from the sun.", true),
		new Card("What would Ohm do?", true),
		new Card("The next movie reading will be of ____.", true),
		new Card("How did Northernlion unite Scotland?", true),
		new Card("Green loves the new Paranautical Activity item ____, but keeps comparing it to the crossbow.", true),
		new Card("____ is really essential to completing the game.", true),
		new Card("My channel is youtube.com/____.", true),
		new Card("Northernlion's cat Ryuka is known for ____ while he records.", true),
		new Card("What gave Ohmwrecker his gaming powers?", true),
		new Card("Hello anybody, I am ____Patrol.", true),
		new Card("I have ____, can you ____ me?", true),
		new Card("____! Get off the ____!", true),
		new Card("My name is ____ and today we'll be checking out ____.", true),
		new Card("It's true that Green9090 is ____, but we must all admit that Ohm is better at ____", true),
		new Card("That's the way ____ did it, that's the way ____ does it, and it''s worked out pretty well so far.", true),
		new Card("Today on Crusader Kings 2, NL plays King ____ the ____.", true),
		new Card("After winning yet another race, Josh made ____ tweet about ____.", true),
		new Card("This time on ____ vs. ____, we're playing ____.", true),
	}, responseCards = new Card[]{
		new Card("Steven Docking.", false),
		new Card("/r/Letsplay.", false),
		new Card("/r/sloths.", false),
		new Card("#Krazymike.", false),
		new Card("A Bane impression.", false),
		new Card("A bunch of jabronies.", false),
		new Card("A docking sleeve.", false),
		new Card("A little bit of added defense.", false),
		new Card("An old man carrying a box of glass down stairs.", false),
		new Card("Anything from http://www.thenorthernlionstory.com/.", false),
		new Card("Beating it on camera.", false),
		new Card("Being terrible at games.", false),
		new Card("Bejeweed.", false),
		new Card("Big Hat Logan.", false),
		new Card("Blondes, brunettes, and redheads.", false),
		new Card("Blue Baby.", false),
		new Card("BOOYAH!", false),
		new Card("Bow to your sensei!", false),
		new Card("Brimstone.", false),
		new Card("Butt meat.", false),
		new Card("Checking the wiki.", false),
		new Card("Cheeseysaurus Rex.", false),
		new Card("Classic Northernlion.", false),
		new Card("Coming on Milhouse.", false),
		new Card("Corner fucking.", false),
		new Card("Crazy Mike.", false),
		new Card("Cross-dimensional fucking.", false),
		new Card("Dark holes.", false),
		new Card("Detroit Dock City.", false),
		new Card("Docking.", false),
		new Card("DockLeeSmile.", false),
		new Card("Dung pies.", false),
		new Card("Dying in a hang gliding accident. ", false),
		new Card("Excuse me?", false),
		new Card("Eyeless ooze guys.", false),
		new Card("Falling down the stairs with a bag full of glass.", false),
		new Card("Fat Robert Downey Jr.", false),
		new Card("Feline eugenics.", false),
		new Card("Fuck tables.", false),
		new Card("Fucking during a Diphtheria epidemic.", false),
		new Card("Garglebutts.", false),
		new Card("Getting corner fucked.", false),
		new Card("Getting wood.", false),
		new Card("Greed.", false),
		new Card("Harry Potter and the Chamber of a Salty Surprise.", false),
		new Card("Hookers, blow, and JSmithOTI.", false),
		new Card("Infomercials.", false),
		new Card("JSmithOTI.", false),
		new Card("Kate's Mario Party skills.", false),
		new Card("Krazy Mike doing a backflip, throwing a talking nut, and chanting 'Hello!'", false),
		new Card("Krazy Mike.", false),
		new Card("Like you, but not rogue-like you.", false),
		new Card("Losing to Monstro after 300 hours of experience.", false),
		new Card("The backroom casting couch.", false),
		new Card("The fuck zone.", false),
		new Card("Losing to Quelaag 12 times in 72 minutes.", false),
		new Card("Michael Caine's spider collection.", false),
		new Card("Michaelalfox.", false),
		new Card("Michaelalfox's love of cheese.", false),
		new Card("Michaelalfox's muscles.", false),
		new Card("Milking the poop for red hearts.", false),
		new Card("Mom's knife.", false),
		new Card("Mom's pad.", false),
		new Card("Monty.", false),
		new Card("A motherfucker.", false),
		new Card("Motherfucking.", false),
		new Card("Nipple hair.", false),
		new Card("Northernlion.", false),
		new Card("Northernlion's cancelled Assassin's Creed II let's play.", false),
		new Card("Northernlion's coffee maker.", false),
		new Card("Northernlion's hair.", false),
		new Card("Northernlion's pooping album.", false),
		new Card("Not Satan, I promise.", false),
		new Card("Permanent Polaroid invincibility.", false),
		new Card("Poison Mushroom.", false),
		new Card("Poutine-induced diabetes.", false),
		new Card("Pretending youtube let's playing is a real job.", false),
		new Card("Projectile annoyance.", false),
		new Card("Putting your balls in her butt.", false),
		new Card("Puzzle platformers with rogue-like elements.", false),
		new Card("Quelaag's Furysword.", false),
		new Card("Residue.", false),
		new Card("RockLeeSmile.", false),
		new Card("Rogue-like likes.", false),
		new Card("Roll Fizzlebeef.", false),
		new Card("Ronald McDonald.", false),
		new Card("Shit happens.", false),
		new Card("Shooting the poop.", false),
		new Card("Solaire of Astora.", false),
		new Card("Stream lag.", false),
		new Card("Stupid damage.", false),
		new Card("A tactical backflip.", false),
		new Card("The Northernlion Story.", false),
		new Card("Whispering sweet nothings into your rear.", false),
		new Card("The notorious Grey's Anatomy let's play.", false),
		new Card("The Binding of Isaac wiki.", false),
		new Card("Thornforg.", false),
		new Card("When you fuck a dog in the ass and it shits all over your dick.", false),
		new Card("The USS Buttfucker.", false),
		new Card("Vaginal silk worms.", false),
		new Card("The Anor Londo Archers.", false),
		new Card("The saga of Krazy Mike.", false),
		new Card("A urination break.", false),
		new Card("The World Docking Champion.", false),
		new Card("The Thug of Porn.", false),
		new Card("That damned HDPVR.", false),
		new Card("The NLSS: drawing unwanted attention from the actual docking community.", false),
		new Card("Patrick Dempsey thrusting violently into my midsection.", false),
		new Card("Well, what is it?", false),
		new Card("The Four Horsemen of The Apocolypse.", false),
		new Card("Talking nuts.", false),
		new Card("The Ozymandias head.", false),
		new Card("A total scumbag.", false),
		new Card("Striking fear into the hearts of your enemies.", false),
		new Card("Using the tears of an abused toddler to conquer my foes.", false),
		new Card("A beef swarm.", false),
		new Card("A butt pooping upwards an egg.", false),
		new Card("JSmith's salty nuts.", false),
		new Card("#ShotsFired.", false),
		new Card("Banana bread.", false),
		new Card("Butterjail.", false),
		new Card("A DraculaFetus animation.", false),
		new Card("A profile pic that looks like a dick and balls.", false),
		new Card("Spy Party racism.", false),
		new Card("The ghost of Ohmwrecker.", false),
		new Card("Shooting the black guy.", false),
		new Card("Ohm's mindgames.", false),
		new Card("Magic: The Gathering.", false),
		new Card("A failed challenge run.", false),
		new Card("Setting the world on fire.", false),
		new Card("Pot magic.", false),
		new Card("Josh's washing machine.", false),
		new Card("Dang it, Bobby!", false),
		new Card("Up in the air like a George Clooney movie.", false),
		new Card("A lemon mishap.", false),
		new Card("This cat, I swear to god.", false),
		new Card("Ohmwrecker.", false),
		new Card("youtube.com/Ohmwrecker.", false),
		new Card("Drinkable fire.", false),
		new Card("Ohmsdrawings.tumblr.com.", false),
		new Card("Soul level 1 invasions.", false),
		new Card("Ryuka.", false),
		new Card("The blue candle.", false),
		new Card("JSmith's laundry.", false),
		new Card("Mount Your Friends: Docking Edition.", false),
		new Card("Childlike bukakke.", false),
		new Card("A water supply full of leeches.", false),
		new Card("Travelling by bones.", false),
		new Card("AlpacaPatrol.", false),
		new Card("Zen.", false),
		new Card("Green9090.", false),
		new Card("#MikeBithell.", false),
		new Card("RedPandaGamer.", false),
		new Card("Ohm, our god.", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Northernlion";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Lion";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}