package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckAnime extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("_. BELIEVE IT!"),
		new Card("Make a contract with me, and become _!"),
		new Card("You guys are so wrong. Obviously, _ is best waifu."),
		new Card("In the latest chapter of Toriko, our hero hunts down, kills, and eats a creature made entirely of _."),
		new Card("THIS _ HAS BEEN PASSED DOWN THE ARMSTRONG FAMILY LINE FOR GENERATIONS!!!"),
		new Card("My favorite episode of _ is the one with _."),
		new Card("Make a yaoi shipping."),
		new Card("This doujinshi I just bought has _ and _ getting it on, hardcore."),
		new Card("On the next episode of Dragon Ball Z, _ is forced to do the fusion dance with _."),
		new Card("You are already _."),
		new Card("_. YOU SHOULD BE WATCHING."),
		new Card("Fresh from Japan: The new smash hit single by _ titled _."),
		new Card("_ vs. _. BEST. FIGHT. EVER."),
		new Card("When it comes to hentai, nothing gets me hotter than _."),
		new Card("S-Shut up!! I-It's not like I'm _ or anything."),
		new Card("The English dub of _ sucks worse than _."),
		new Card("What is moÉ?"),
		new Card("Hayao Miyazaki's latest family film is about a young boy befriending _."),
		new Card("Congratulations, _."),
		new Card("By far the best panel at any anime convention is the one for _."),
		new Card("One thing you almost never see in anime is _."),
		new Card("The rarest Pok&eacute;mon in my collection is _."),
		new Card("What do I hate most about anime?"),
		new Card("Mamoru Oshii's latest film is a slow-paced, two hour-long cerebral piece about the horrors of _."),
		new Card("What do I love most about anime?"),
		new Card("This morning, hundreds of Japanese otaku lined up outside their favorite store to buy the limited collector's edition of _."),
		new Card("Every now and then, I like to participate in the time-honored Japanese tradition of _."),
		new Card("Watch it! Or I'll take your _."),
		new Card("New from Studio GAINAX: _ the Animation."),
		new Card("Using my power of Geass, I command you to do... THIS!"),
		new Card("Chicks. Dig. _."),
		new Card("The next big Tokusatsu show: 'Super Sentai _ Ranger!'"),
		new Card("In the name of the moon, I will punish _!"),
		new Card("Don't worry, he's okay! He survived thanks to _."),
		new Card("In the latest chapter of Golgo 13, he kills his target with _."),
		new Card("Welcome home, Master! Is there anything your servant girl can bring you today?"),
		new Card("In the latest episode of Case Closed, Conan deduces that it was _ who killed _ because of _."),
		new Card("Take this! My love, my anger, and all of my _!"),
		new Card("Karaoke night! I'm totally gonna sing my favorite song, _."),
		new Card("Now! Face my ultimate attack!"),
		new Card("Behold the name of my Zanpakuto, _!"),
		new Card("From the twisted mind of Nabeshin: An anime about _, _, and _."),
		new Card("_. Only on Toonami"),
		new Card("I am in despair! _ has left me in despair!"),
		new Card("The new manga from _ is about a highschool girl discovering _."),
		new Card("To save the world, you must collect all 7 _."),
		new Card("Sasuke has _ implants."),
		new Card("In truth, the EVA units are actually powered by the souls of _."),
		new Card("Dreaming! Don't give it up _! Dreaming! Don't give it up _! Dreaming! Don't give it up _!"),
		new Card("Lupin the III's latest caper involves him trying to steal _."),
		new Card("The new Gurren Lagann blurays from Aniplex will literally cost you _."),
		new Card("The most overused anime cliche is _."),
		new Card("The inspiration behind the latest hit show is _."),
		new Card("While writing Dragon Ball, Akira Toriyama would occasionally take a break from working to enjoy _."),
		new Card("The show was great, until _ showed up."),
		new Card("Nothing ruins a good anime faster than _."),
		new Card("I want to be the very best, like no one ever was! _ is my real test, _ is my cause!"),
		new Card("Who are you callin' _ so short he can't see over his own _?!?!"),
		new Card("If you ask me, there need to be more shows about _."),
		new Card("_. That is the kind of man I was."),
		new Card("I'm sorry! I'm sorry! I didn't mean to accidentally walk in on you while you were _!"),
		new Card("After a long, arduous battle, _ finally met their end by _."),
		new Card("This is our final battle. Mark my words, I will defeat you, _!"),
		new Card("You used _. It's super effective!"),
		new Card("The best English dub I've ever heard is the one for _."),
		new Card("I know of opinions and all that, but I just don't understand how anyone could actually enjoy _."),
		new Card("_. HE DED."),
		new Card("She'll thaw out if you try _."),
		new Card("You see, I'm simply _."),
		new Card("Yoko Kanno's latest musical score features a song sung entirely by _."),
		new Card("This year, I totally lucked out and found _ in the dealer's room."),
		new Card("How did I avoid your attack? Simple. By _."),
		new Card("If I was a magical girl, my cute mascot sidekick would be _."),
		new Card("From the creators of Tiger &amp; Bunny: _ &amp; _!!"),
		new Card("In the future of 199X, the barrier between our world and the demon world is broken, and thousands of monsters invade our realm to feed upon _."),
		new Card("Animation studio _ is perhaps best known for _."),
		new Card("_. So kawaii!! <3 <3"),
		new Card("The most annoying kind of anime fans are _."),
		new Card("Cooking is so fun! Cooking is so fun! Now it's time to take a break and see what we have done! _. YAY! IT'S READY!!"),
		new Card("My favorite hentai is the one where _ is held down and violated by _."),
		new Card("This year, I'm totally gonna cosplay as _."),
		new Card("Coming to Neon Alley: _, completely UNCUT &amp; UNCENSORED."),
		new Card("No matter how many times I see it, _ always brings a tear to my eye."),
		new Card("Who placed first in the most recent Shonen Jump popularity poll?"),
		new Card("Someday when I have kids, I want to share with them the joys of _."),
		new Card("So, what have you learned from all of this?"),
		new Card("In this episode of Master Keaton, Keaton builds _ out of _ and _."),
		new Card("The World Line was changed when I sent a D-mail to myself about _."),
		new Card("My _ will pierce the heavens!!"),
		new Card("After years of searching, the crew of the Thousand Sunny finally found out that the One Piece is actually _."),
		new Card("When I found all 7 Dragon Balls, Shenron granted me my wish for _."),
		new Card("The best part of my _ costume is _."),
		new Card("Cards Against Anime: It's more fun than _!"),
		new Card("On the mean streets of Tokyo, everyone knows that _ is the leader of the _ Gang."),
		new Card("He might just save the universe, if he only had some _!"),
		new Card("So just who is this Henry Goto fellow, anyway?"),
		new Card("When Henry Goto is alone and thinks that no one's looking, he secretly enjoys _."),
		new Card("Dr. Black Jack, please hurry! The patient is suffering from a terminal case of _!"),
		new Card("Make a love triangle. _ + _ + _"),
		new Card("This _ of mine glows with an awesome power! Its _ tells me to defeat you!"),
		new Card("Yo-Ho-Ho! He took a bite of _.")
	}, responseCards = new Card[]{
		new Card("Kyubey."),
		new Card("Weeaboos."),
		new Card("Aniplex of America."),
		new Card("Steve Motherfuckin' Blum."),
		new Card("Norio Wakamoto."),
		new Card("Eating an entire box of Pocky in a single bite."),
		new Card("Lolis."),
		new Card("Hot-blooded shonen protagonists."),
		new Card("Crispin Freeman."),
		new Card("A big-breasted 14-year-old wearing a bikini and sucking on a popsicle."),
		new Card("Henry Goto being savagely raped by a bear."),
		new Card("Yet another goddamn Goku vs. Superman argument."),
		new Card("FANSERVICE!!!"),
		new Card("Gen Fukunaga counting his money."),
		new Card("Hatsune Miku."),
		new Card("Strangling hardcore otaku nerds with razor wire."),
		new Card("Bukkake."),
		new Card("Little Kuriboh."),
		new Card("Bulma's panties."),
		new Card("Mami getting her head bitten off."),
		new Card("A Captain Harlock body pillow."),
		new Card("Onii-chan."),
		new Card("MAWNING LESCUE!!!"),
		new Card("Christopher R. Sabat."),
		new Card("PASTAAAAA!!!!"),
		new Card("Johnny Yong Bosch."),
		new Card("$300 anime bluray boxsets."),
		new Card("Man-Faye."),
		new Card("DAN GREEN."),
		new Card("WE UNDERSTAND ANIME FAN WANTS!!', "),
		new Card("Dio Brando."),
		new Card("Hokuto! Hyakurestu-ken!"),
		new Card("Vic Micderpaderp."),
		new Card("Goku."),
		new Card("Soldier A."),
		new Card("Red-headed tsunderes."),
		new Card("That sound effect in every hentai when the guy ejaculates."),
		new Card("Edward Wong Hau Pepelu Tivruski IV."),
		new Card("Bang.', "),
		new Card("Prof's legs."),
		new Card("Wendee Lee."),
		new Card("Rice balls."),
		new Card("Monkey D. Luffy."),
		new Card("JesuOtaku's ginormous lips."),
		new Card("Princess Tutu."),
		new Card("Fujiko's boobs."),
		new Card("Shinji being a whiny little bitch."),
		new Card("Third Impact."),
		new Card("Kenshiro."),
		new Card("Puella Magi Madoka Magica."),
		new Card("Taking a potato chip... and EATING IT."),
		new Card("Unreasonably long transformation sequences."),
		new Card("Ass dance!! Ass dance!!"),
		new Card("Stupid fucking Kululu."),
		new Card("CENTURY SOOOOUUUP!!!!!"),
		new Card("The Gripper."),
		new Card("Thinking Misty from Pok&eacute;mon is... kinda sexy."),
		new Card("Garzey's Wing."),
		new Card("Reverse harems."),
		new Card("Sir Integra Fairbrook Wingates Hellsing."),
		new Card("Wearing panties on the head."),
		new Card("Brina Palencia as an angsty teenage boy, Monica Rial as his bratty little sister, and Shelley Calene-Black as their hot mom."),
		new Card("CARD GAMES ON MOTORCYCLES."),
		new Card("Nice boat."),
		new Card("Boku no Pico."),
		new Card("The One Piece rap."),
		new Card("A Bleach hentai doujin where Rukia rapes Ichigo."),
		new Card("Walpurgisnacht."),
		new Card("Bludgeoning Haruhi Suzumiya to death with a tire iron."),
		new Card("Girls with glasses."),
		new Card("Eating the wrong end of a chocolate cornet."),
		new Card("Casca's hairy unshaven vag."),
		new Card("Tits on your hand."),
		new Card("That little fat kid from Accel World."),
		new Card("A "),
		new Card("Giant robots."),
		new Card("Osamu Tezuka."),
		new Card("Studio Ghibli."),
		new Card("Masa! <3"),
		new Card("THE MAN-POLE OF DOOOOOOOOOM!!!"),
		new Card("Ladd Russo."),
		new Card("Home For Infinite Losers (HFIL)."),
		new Card("Moe Moe Kyun!"),
		new Card("El Psy Congroo."),
		new Card("Sailor Moon and the 7 Ballz."),
		new Card("Gratuitous panty shots."),
		new Card("Sucking Kyle Hebert's dick for hamburgers."),
		new Card("Cartoon buttholes."),
		new Card("Muscle-bound shirtless MEN."),
		new Card("Recap episodes."),
		new Card("An overly defensive fanbase."),
		new Card("Fuckin' Bronies."),
		new Card("Groping strangers on a train."),
		new Card("My Cresta."),
		new Card("Nerdy kids in Speedos."),
		new Card("Bad K-on! fanart."),
		new Card("That stupid opening song from Steel Angel Kurumi getting stuck in your head."),
		new Card("Mamoru Miyano."),
		new Card("TETSUOOOOOO!!!"),
		new Card("Wibble."),
		new Card("Black cosplayers."),
		new Card("Fake Nendoroids."),
		new Card("Eating ramen noodles for a month because you HAD to have that out of print Macross boxset."),
		new Card("Showing Serial Experiments Lain to toddlers."),
		new Card("A puppy being beaten to death with a flower pot."),
		new Card("Gantz. Just.... Gantz."),
		new Card("Snapping the nipple off of a prostitute's breast and eating it."),
		new Card("Panty & Stocking with Garterbelt."),
		new Card("Punching a man so hard his clothes fly off."),
		new Card("Banana sushi."),
		new Card("Oro?"),
		new Card("Creamy Mami."),
		new Card("Whatever the hell the Utena movie was about."),
		new Card("Carl Macek."),
		new Card("The ungodly abomination that is Robotech."),
		new Card("Kira worshippers."),
		new Card("The thousands upon thousands of women that Golgo 13 has slept with."),
		new Card("Uguu..."),
		new Card("Old man dragon dick."),
		new Card("Apocalypse Zero."),
		new Card("Ikki Tousen."),
		new Card("The inevitable beach episode."),
		new Card("A Japanese schoolgirl covered head-to-toe in semen."),
		new Card("Satoshi Kon."),
		new Card("Kigurumi."),
		new Card("Good ol' fashioned Japanese sexism."),
		new Card("Guro."),
		new Card("Dr. Who fans showing up at anime cons despite not being invited."),
		new Card("Plot armor."),
		new Card("Nekomimi."),
		new Card("Pure grade-A opium."),
		new Card("Banging 1,000 dudes."),
		new Card("A drunken Japanese businessman."),
		new Card("Maid cafes."),
		new Card("Host clubs."),
		new Card("Shooting out nearly an entire liter of cum."),
		new Card("Shining Finger!"),
		new Card("The inkvasion."),
		new Card("School swimsuits."),
		new Card("Underpants. Underpants. Underpants. Underpants. Under-"),
		new Card("Acidic breast milk."),
		new Card("Kamen Rider."),
		new Card("The Major's hips and bust."),
		new Card("Captain Bravo."),
		new Card("Kirino's ass."),
		new Card("Crystal Boy's creepy smile."),
		new Card("Gackt."),
		new Card("Used panty vending machines."),
		new Card("Butt sniffing."),
		new Card("Vegeta's sweet goatee."),
		new Card("Sub-only releases."),
		new Card("Getting drunk on sake."),
		new Card("Flying Vortex of Fear."),
		new Card("Fishcake."),
		new Card("Go Nagai sideburns."),
		new Card("CHIIIIIIIIN."),
		new Card("Getting the bad ending of a visual novel."),
		new Card("The Tsukihime anime."),
		new Card("Jacuzzi Splot."),
		new Card("Juvijuvibro."),
		new Card("Bear punching, tiger chopping, shark suplexing, &amp; helicopter bodyslamming."),
		new Card("Stupid sexy Johan."),
		new Card("Naoki Urasawa."),
		new Card("Tachikoma-kun."),
		new Card("Dancin' on the Planet Dance."),
		new Card("Super Milk-chan."),
		new Card("You dumbass!"),
		new Card("Being the uke."),
		new Card("The power of friendship."),
		new Card("An arm and a leg."),
		new Card("The entire cast of School Days."),
		new Card("Giant naked Rei."),
		new Card("Masturbating over Asuka's comatose body."),
		new Card("Let's Fighting Love!"),
		new Card("Making someone's head explode."),
		new Card("Michelle Ru-<br>er, I mean... 'Sophie Roberts.'"),
		new Card("Calling out the name of your attack."),
		new Card("Multi-episode fights."),
		new Card("M.D. Geist."),
		new Card("Blue Water Studios."),
		new Card("Darrel Guilbeau trying to act."),
		new Card("Highschool of the Dead."),
		new Card("Girls with guns."),
		new Card("The goddamn Maho."),
		new Card("Fat, sweaty otaku."),
		new Card("Ganguro girls."),
		new Card("Magical girls."),
		new Card("Hot female bass players."),
		new Card("Goku, Luffy, Toriko, and Lina Inverse in an eating contest."),
		new Card("Blackï‚«Star"),
		new Card("KING!!! KING!!! KING GAINER!!! *does the Monkey*"),
		new Card("You cactus bastard!"),
		new Card("Underwater Ray Romano."),
		new Card("Sexy schoolteacher types."),
		new Card("Tig ol' bitties."),
		new Card("Lesbian subtext."),
		new Card("Inspector Zenigata."),
		new Card("Pure fighting spirit."),
		new Card("The GARtender."),
		new Card("Mad Bull 34."),
		new Card("Freddie riding to school on a wild black stallion."),
		new Card("Whatever turns you on, big guy."),
		new Card("I'LL ANSWER THE PHONE FROM NOW ON, LILY!!"),
		new Card("KITTEH. :3"),
		new Card("Manly tears of manliness."),
		new Card("Zetman."),
		new Card("Giant mutant cockroaches."),
		new Card("Bible Black."),
		new Card("Rape fantasies."),
		new Card("Keith David's voice."),
		new Card("Scott McNeil."),
		new Card("The eternal pervert, Eric Vale."),
		new Card("The Irresponsible Captain Tylor."),
		new Card("Birdy the Mighty."),
		new Card("Prying SpacemanHardy's Master Keaton boxset from his cold, dead hands."),
		new Card("Satan worshipping Christians."),
		new Card("Hunting down every single copy of Ninja Resurrection and setting them on fire."),
		new Card("R-R-R-R-R-REDLINE!!!"),
		new Card("Badass 15-year-olds."),
		new Card("Losing 20 gallons of blood... and surviving."),
		new Card("One HELL of a butler."),
		new Card("Being beaten to a bloody pulp by a middle school student."),
		new Card("Anime News Network."),
		new Card("Having blackmail sex with your teacher."),
		new Card("A large paper fan."),
		new Card("The Shikon Jewel."),
		new Card("INUYASHA!!"),
		new Card("Sneaking a peek at the girls' open bath."),
		new Card("Revy Two-Hands."),
		new Card("A Claymore swimsuit issue."),
		new Card("A samurai terminator."),
		new Card("Physics."),
		new Card("Gangnam Style."),
		new Card("MUNGLE!! *shakes fist*"),
		new Card("A talking motorcycle."),
		new Card("Rie Kugimiya."),
		new Card("The Animatrix."),
		new Card("Franky's awesome Speedo dance."),
		new Card("Soul traveling."),
		new Card("Production I.G."),
		new Card("GONZO."),
		new Card("Really shitty CGI effects."),
		new Card("The hot buttered sex voice of Patrick Seitz."),
		new Card("Sticking a chopstick in your pee-hole."),
		new Card("A copy of Trigun signed by Micah Solusod."),
		new Card("Gilgamesh."),
		new Card("That one guy who always dresses up as the Red Ranger."),
		new Card("Madhouse."),
		new Card("ARMS."),
		new Card("Mr. Tadakichi."),
		new Card("Showing episodes of Toriko to starving children."),
		new Card("Governor Ishihara."),
		new Card("Shrine maidens."),
		new Card("Taking a shit in the shrine's donation box."),
		new Card("Farting... tadpoles?"),
		new Card("Heavily-tattooed yakuza henchmen."),
		new Card("The life-sized Gundam statue."),
		new Card("Forcing someone to watch every episode of Dragon Ball GT."),
		new Card("ZA WARUDO."),
		new Card("Eating a banana all sexy-like."),
		new Card("Awesome Prussia."),
		new Card("Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora! Ora!"),
		new Card("A shitload of yen."),
		new Card("Johannes Krauser II."),
		new Card("Raccoon testicles."),
		new Card("Beautiful bishonen boys."),
		new Card("Rule 63'd Death the Kid."),
		new Card("Hetalia porn."),
		new Card("1,000 years of pain."),
		new Card("Rally Vincent firing a gun in her underwear."),
		new Card("A Maka Chop."),
		new Card("Broken-ass Aizen."),
		new Card("The Garden of Sinners."),
		new Card("Romi Paku."),
		new Card("My Johnny!"),
		new Card("Petite Princess Yucie."),
		new Card("Ice cold water<br>(and it's only a dollar)."),
		new Card("Me wearing a penguin suit."),
		new Card("Farting on your cat."),
		new Card("Combat afros."),
		new Card("A brand new, mint condition copy of JoJo's Bizarre Adventure vol. 4, still in shrinkwrap."),
		new Card("Grave of the Fireflies."),
		new Card("Strapping hand grenades to your pubes."),
		new Card("Toilet worship."),
		new Card("My badass numchucks."),
		new Card("Trying to get your die-cast Gundam model through airport security."),
		new Card("Black&#x2605;Star"),
		new Card("Octopus balls."),
		new Card("Getting in a fistfight with an earthquake."),
		new Card("WcDonald's."),
		new Card("Undead body-swapping space vampire teens."),
		new Card("The alpha bitch."),
		new Card("Eating someone else's drool."),
		new Card("My hot zombie girlfriend.."),
		new Card("Puppets made from the skin of children."),
		new Card("Swallowing an entire carton of cigarettes before barfing them back up."),
		new Card("Giving a girl an orgasm using only your shoulderpads."),
		new Card("Being accidentally turned into a girl by aliens."),
		new Card("Ghosts that come out of your asscrack."),
		new Card("#DesuDes4Life."),
		new Card("Fucking a nun."),
		new Card("Raping Tokyo Tower."),
		new Card("A succubus living inside your testes."),
		new Card("Saber Starblast."),
		new Card("An argument lasting over an hour about what mo&eacute; really is."),
		new Card("Kotetsu T. Kaburagi, aka. 'The D.I.L.F.'"),
		new Card("Japanese Spider-Man."),
		new Card("A bass guitar straight to the face."),
		new Card("Sonny Strait's manly parts."),
		new Card("Guts."),
		new Card("Finger nigiri."),
		new Card("Dragon Balls."),
		new Card("Suplexing your teacher."),
		new Card("A leopard print fundoshi."),
		new Card("Breast envy."),
		new Card("The entire last episode of Blood-C."),
		new Card("Origami sex toys."),
		new Card("ALL OF THE HOMO!"),
		new Card("Japanese rope bondage."),
		new Card("Griffith's mysterious disappearing penis."),
		new Card("Naughty geishas."),
		new Card("Ninjas!"),
		new Card("Pubic hair needle attack."),
		new Card("Sexy jutsu."),
		new Card("Getting your fingernails ripped out."),
		new Card("Shinichiro Watanabe single-handedly curing cancer, ending world hunger, and bringing peace to the Middle East."),
		new Card("Love Machine."),
		new Card("Rapping samurai."),
		new Card("Putting all the condiments on your steak. ALL OF THEM."),
		new Card("Naga's extremely annoying laugh."),
		new Card("A dolphin in a mech suit."),
		new Card("Flying Nimbus."),
		new Card("Strikeman and his "),
		new Card("A busty, blonde, blue-eyed, dumb-as-rocks American."),
		new Card("Running during the credits."),
		new Card("Red bean paste."),
		new Card("Gender-swapped Oda Nobunaga."),
		new Card("Cutting off a finger to restore your honor."),
		new Card("Robots with tits."),
		new Card("Henry Goto."),
		new Card("Henry Goto having an accident in his pants during the live Aniplex of America panel."),
		new Card("Henry Goto's massive peyote &amp; wine cooler addiction."),
		new Card("Henry Goto, John Sirabella, and Stu Levy in a three man fight to the death."),
		new Card("Henry Goto fapping to a photograph of himself."),
		new Card("Henry Goto being eaten by a group of backwoods hillbilly cannibals."),
		new Card("Henry Goto ending up homeless on the streets and sucking dick for coke."),
		new Card("Two gallons of elephant shit being dropped on Henry Goto's desk."),
		new Card("Henry Goto falling down the stairs, receiving a massive head injury, and believing he's really Sailor Moon."),
		new Card("A Henry Goto joke that no one will laugh at other than SpacemanHardy."),
		new Card("Henry Goto bleeding profusely from his groin after having his penis bitten off by a 15-year-old Vietnamese prostitute."),
		new Card("A 30-year-old man who's obsessed with K-on!"),
		new Card("LAZAR!"),
		new Card("I AM AWESOME!!"),
		new Card("Getting kicked in the nuts by a mermaid.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Anime";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Anime";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}