package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckVersion3 extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("What's that smell?"),
		new Card("What's that sound?"),
		new Card("What ended my last relationship?"),
		new Card("What is Batman's guilty pleasure?"),
		new Card("What's a girl's best friend?"),
		new Card("What does Dick Cheney prefer?"),
		new Card("What's the most emo?"),
		new Card("What are my parents hiding from me?"),
		new Card("What will always get you laid?"),
		new Card("What did I bring back from Mexico?"),
		new Card("What will I bring back in time to convince people that I am a powerful wizard?"),
		new Card("How am I maintaining my relationship status?"),
		new Card("What gives me uncontrollable gas?"),
		new Card("What do old people smell like? "),
		new Card("What's my secret power?"),
		new Card("What's there a ton of in heaven?"),
		new Card("What would grandma find disturbing, yet oddly charming?"),
		new Card("What did the U.S. airdrop to the children of Afghanistan?"),
		new Card("What helps Obama unwind?"),
		new Card("What did Vin Diesel eat for dinner?"),
		new Card("Why am I sticky?"),
		new Card("What gets better with age?"),
		new Card("What's Teach for America using to inspire inner city students to succeed?"),
		new Card("Make a haiku."),
		new Card("Why do I hurt all over?"),
		new Card("What am I giving up for Lent?"),
		new Card("What's my anti-drug?"),
		new Card("What never fails to liven up the party?"),
		new Card("What's the new fad diet?"),
		new Card("I got 99 problems but _ ain't one."),
		new Card("TSA guidelines now prohibit _ on airplanes."),
		new Card("MTV's new reality show features eight washed-up celebrities living with _."),
		new Card("I drink to forget _."),
		new Card("I'm sorry, Professor, but I couldn't complete my homework because of _."),
		new Card("Alternative medicine is now embracing the curative powers of _."),
		new Card("It's a pity that kids these days are all getting involved with _."),
		new Card("_. That's how I want to die."),
		new Card("In the new Disney Channel Original Movie, Hannah Montana struggles with _ for the first time."),
		new Card("Instead of coal, Santa now gives the bad children _."),
		new Card("A romantic, candlelit dinner would be incomplete without _."),
		new Card("Next from J.K. Rowling: Harry Potter and the Chamber of _."),
		new Card("_. Betcha can't have just one!"),
		new Card("White people like _."),
		new Card("_. High five, bro."),
		new Card("During sex, I like to think about _."),
		new Card("BILLY MAYS HERE FOR _."),
		new Card("When I am the President of the United States, I will create the Department of _."),
		new Card("Major League Baseball has banned _ for giving players an unfair advantage."),
		new Card("When I am a billionare, I shall erect a 50-foot statue to commemorate _."),
		new Card("_. It's a trap!"),
		new Card("Coming to Broadway this season, _: The Musical."),
		new Card("But before I kill you, Mr. Bond, I must show you _."),
		new Card("When Pharaoh remained unmoved, Moses called down a plague of _."),
		new Card("The class field trip was completely ruined by _."),
		new Card("In Michael Jackson's final moments, he thought about _."),
		new Card("Studies show that lab rats navigate mazes 50% faster after being exposed to _."),
		new Card("I do not know with which weapons World War III will be fought, but World War IV will be fought with _."),
		new Card("_: Good to the last drop."),
		new Card("_: kid-tested, mother-approved."),
		new Card("And the Academy Award for _ goes to _."),
		new Card("For my next trick, I will pull _ out of _."),
		new Card("_ is a slippery slope that leads to _."),
		new Card("In M. Night Shyamalan's new movie, Bruce Willis discovers that _ had really been _ all along."),
		new Card("In a world ravaged by _, our only solace is _."),
		new Card("I never truly understood _ until I encountered _."),
		new Card("When I was tripping on acid, _ turned into _."),
		new Card("That's right, I killed _. How, you ask? _."),
		new Card("What's the next superhero/sidekick duo?"),
		new Card("Daddy, why is Mommy crying?"),
		new Card("Maybe she's born with it. Maybe it's _."),
		new Card("In L.A. County Jail, word is you can trade 200 cigarettes for _."),
		new Card("After the earthquake, Sean Penn brought _ to the people of Haiti."),
		new Card("Next on ESPN2, the World Series of _."),
		new Card("Step 1: _. Step 2: _. Step 3: Profit."),
		new Card("Life for American Indians was forever changed when the White Man introduced them to _."),
		new Card("What's the next Happy Meal&reg; toy?"),
		new Card("Lifetime&reg; presents _, the story of _."),
		new Card("Dear Abby,<br><br>I'm having some trouble with _ and would like your advice."),
		new Card("While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _."),
		new Card("How did I lose my virginity?"),
		new Card("Here is the church<br>Here is the steeple<br>Open the doors<br>And there is _."),
		new Card("During his childhood, Salvador Dal&iacute; produced hundreds of paintings of _."),
		new Card("This is the way the world ends / This is the way the world ends / Not with a bang but with _."),
		new Card("In 1,000 years, when paper money is a distant memory, how will we pay for goods and services?"),
		new Card("War!\rWhat is it good for?"),
		new Card("What don't you want to find in your Kung Pao chicken?"),
		new Card("Rumor has it that Vladimir Putin's favorite delicacy is _ stuffed with _."),
		new Card("The Smithsonian Museum of Natural History has just opened an exhibit on _.")
	}, responseCards = new Card[]{
		new Card("Michelle Obama's arms."),
		new Card("White people."),
		new Card("An erection that lasts longer than four hours."),
		new Card("Panda sex."),
		new Card("A middle-aged man on roller skates."),
		new Card("Coat hanger abortions."),
		new Card("Scrubbing under the folds."),
		new Card("Wearing underwear inside-out to avoid doing laundry."),
		new Card("Getting naked and watching Nickelodeon."),
		new Card("Morgan Freeman's voice."),
		new Card("Breaking out into song and dance."),
		new Card("Soup that is too hot."),
		new Card("Unfathomable stupidity."),
		new Card("Horrifying laser hair removal accidents."),
		new Card("Boogers."),
		new Card("Expecting a burp and vomiting on the floor."),
		new Card("A defective condom."),
		new Card("Teenage pregnancy."),
		new Card("Hot cheese."),
		new Card("A mopey zoo lion."),
		new Card("Shapeshifters."),
		new Card("The Care Bear Stare."),
		new Card("Erectile dysfunction."),
		new Card("The chronic."),
		new Card("Firing a rifle into the air while balls deep in a squealing hog."),
		new Card("Nicolas Cage."),
		new Card("Dropping a chandelier on your enemies and riding the rope up."),
		new Card("Public ridicule."),
		new Card("A snapping turtle biting the tip of your penis."),
		new Card("Vehicular manslaughter."),
		new Card("The token minority."),
		new Card("A gentle caress of the inner thigh."),
		new Card("Poor life choices."),
		new Card("Embryonic stem cells."),
		new Card("The Little Engine That Could."),
		new Card("A death ray."),
		new Card("Vigilante justice."),
		new Card("Exactly what you'd expect."),
		new Card("Natural male enhancement."),
		new Card("Passive-aggressive Post-it notes."),
		new Card("Inappropriate yodeling."),
		new Card("A homoerotic volleyball montage."),
		new Card("Actually taking candy from a baby."),
		new Card("Crystal meth."),
		new Card("My inner demons."),
		new Card("Pac-Man uncontrollably guzzling cum."),
		new Card("My vagina."),
		new Card("The true meaning of Christmas."),
		new Card("Flying sex snakes."),
		new Card("German dungeon porn."),
		new Card("Praying the gay away."),
		new Card("Dying."),
		new Card("Same-sex ice dancing."),
		new Card("Dying of dysentery."),
		new Card("Roofies."),
		new Card("The Big Bang."),
		new Card("Amputees."),
		new Card("Men."),
		new Card("Concealing a boner."),
		new Card("Agriculture."),
		new Card("Making a pouty face."),
		new Card("YOU MUST CONSTRUCT ADDITIONAL PYLONS."),
		new Card("Hormone injections."),
		new Card("Tom Cruise."),
		new Card("Object permanence."),
		new Card("Being marginalized."),
		new Card("The profoundly handicapped."),
		new Card("Nickelback."),
		new Card("Doing the right thing."),
		new Card("The invisible hand."),
		new Card("Heteronormativity."),
		new Card("Cuddling."),
		new Card("Raptor attacks."),
		new Card("Fear itself."),
		new Card("Sniffing glue."),
		new Card("An icepick lobotomy."),
		new Card("Being rich."),
		new Card("The clitoris."),
		new Card("Sexy pillow fights."),
		new Card("Sexting."),
		new Card("Horse meat."),
		new Card("Sunshine and rainbows."),
		new Card("Goblins."),
		new Card("Spectacular abs."),
		new Card("The Three-Fifths compromise."),
		new Card("Vigorous jazz hands."),
		new Card("Skeletor."),
		new Card("Vikings."),
		new Card("Genital piercings."),
		new Card("A really cool hat."),
		new Card("An Oedipus complex."),
		new Card("The Underground Railroad."),
		new Card("Heartwarming orphans."),
		new Card("Cheating in the Special Olympics."),
		new Card("Sharing needles."),
		new Card("Ethnic cleansing."),
		new Card("Eating all of the cookies before the AIDS bake-sale."),
		new Card("My humps."),
		new Card("The violation of our most basic human rights."),
		new Card("Fingering."),
		new Card("The placenta."),
		new Card("Flightless birds."),
		new Card("Stranger danger."),
		new Card("Sean Penn."),
		new Card("A sad handjob."),
		new Card("Self-loathing."),
		new Card("A falcon with a cap on its head."),
		new Card("Historically black colleges."),
		new Card("Aaron Burr."),
		new Card("Former President George W. Bush."),
		new Card("Geese."),
		new Card("Mutually-assured destruction."),
		new Card("Bling."),
		new Card("Smegma."),
		new Card("The South."),
		new Card("Pretending to care."),
		new Card("A sausage festival."),
		new Card("Foreskin."),
		new Card("Being a dick to children."),
		new Card("Chainsaws for hands."),
		new Card("The Pope."),
		new Card("A balanced breakfast."),
		new Card("Elderly Japanese men."),
		new Card("Pictures of boobs."),
		new Card("Science."),
		new Card("A bleached asshole."),
		new Card("Autocannibalism."),
		new Card("William Shatner."),
		new Card("A micropenis."),
		new Card("Bingeing and purging."),
		new Card("Man meat."),
		new Card("Laying an egg."),
		new Card("The terrorists."),
		new Card("A bitch slap."),
		new Card("One trillion dollars."),
		new Card("Chunks of dead prostitute."),
		new Card("The entire Mormon Tabernacle Choir."),
		new Card("The female orgasm."),
		new Card("Extremely tight pants."),
		new Card("Stormtroopers."),
		new Card("The Boy Scouts of America."),
		new Card("Throwing a virgin into a volcano."),
		new Card("Passive-agression."),
		new Card("Guys who don't call."),
		new Card("The Rapture."),
		new Card("Eugenics."),
		new Card("Taking off your shirt."),
		new Card("Ronald Reagan."),
		new Card("Jewish fraternities."),
		new Card("All-you-can-eat shrimp for $4.99."),
		new Card("Scalping."),
		new Card("Edible underpants."),
		new Card("Figgy pudding."),
		new Card("The American Dream."),
		new Card("Testicular torsion."),
		new Card("The folly of man."),
		new Card("The KKK."),
		new Card("The taint; the grundle; the fleshy fun-bridge."),
		new Card("Saxophone solos."),
		new Card("That thing that electrocutes your abs."),
		new Card("Friends with benefits."),
		new Card("Teaching a robot to love."),
		new Card("Me time."),
		new Card("The heart of a child."),
		new Card("Smallpox blankets."),
		new Card("Yeast."),
		new Card("Full frontal nudity."),
		new Card("Authentic Mexican cuisine."),
		new Card("Licking things to claim them as your own."),
		new Card("Genghis Khan."),
		new Card("The hardworking Mexican."),
		new Card("RoboCop."),
		new Card("Spontaneous human combustion."),
		new Card("Natural selection."),
		new Card("A good sniff."),
		new Card("Nipple blades."),
		new Card("Leaving an awkward voicemail."),
		new Card("Assless chaps."),
		new Card("Sweet, sweet vengeance."),
		new Card("Necrophilia."),
		new Card("Toni Morrison's vagina."),
		new Card("Preteens."),
		new Card("A cooler full of organs."),
		new Card("Keanu Reeves."),
		new Card("A thermonuclear detonation."),
		new Card("Catapults."),
		new Card("Emotions."),
		new Card("Balls."),
		new Card("Homeless people."),
		new Card("Old-people smell."),
		new Card("Farting and walking away."),
		new Card("The inevitable heat death of the universe."),
		new Card("The Rev. Dr. Martin Luther King, Jr."),
		new Card("Sperm whales."),
		new Card("A murder most foul."),
		new Card("Daddy issues."),
		new Card("Britney Spears at 55."),
		new Card("Natalie Portman."),
		new Card("The Holy Bible."),
		new Card("Pulling out."),
		new Card("Pixelated bukkake."),
		new Card("Waiting 'til marriage."),
		new Card("The World of Warcraft."),
		new Card("World peace."),
		new Card("A can of whoop-ass."),
		new Card("A zesty breakfast burrito."),
		new Card("Picking up girls at the abortion clinic."),
		new Card("Land mines."),
		new Card("A time travel paradox."),
		new Card("Waking up half-naked in a Denny's parking lot."),
		new Card("Christopher Walken."),
		new Card("Gloryholes."),
		new Card("A tiny horse."),
		new Card("A sassy black woman."),
		new Card("Penis envy."),
		new Card("Drinking alone."),
		new Card("Hulk Hogan."),
		new Card("Whipping it out."),
		new Card("Dental dams."),
		new Card("God."),
		new Card("Friction."),
		new Card("A sea of troubles."),
		new Card("Poor people."),
		new Card("Flesh-eating bacteria."),
		new Card("Dick Cheney."),
		new Card("Lockjaw."),
		new Card("Take-backsies."),
		new Card("Opposable thumbs."),
		new Card("The homosexual agenda."),
		new Card("Fiery poops."),
		new Card("Cards Against Humanity."),
		new Card("Sean Connery."),
		new Card("The milk man."),
		new Card("The Chinese gymnastics team."),
		new Card("Eating the last known bison."),
		new Card("Giving 110%."),
		new Card("Friendly fire."),
		new Card("Count Chocula."),
		new Card("Feeding Rosie O'Donnell."),
		new Card("Being a motherfucking sorcerer."),
		new Card("African children."),
		new Card("Crippling debt."),
		new Card("A disappointing birthday party."),
		new Card("Puppies!"),
		new Card("A windmill full of corpses."),
		new Card("Being on fire."),
		new Card("A lifetime of sadness."),
		new Card("Republicans."),
		new Card("A salty surprise."),
		new Card("The Jews."),
		new Card("Incest."),
		new Card("Nazis."),
		new Card("Repression."),
		new Card("Attitude."),
		new Card("Passable transvestites."),
		new Card("Puberty."),
		new Card("Swooping."),
		new Card("Lactation."),
		new Card("Pabst Blue Ribbon."),
		new Card("The gays."),
		new Card("A foul mouth."),
		new Card("A hot mess."),
		new Card("My collection of high-tech sex toys."),
		new Card("Bees?"),
		new Card("Getting drunk on mouthwash."),
		new Card("The glass ceiling."),
		new Card("Sarah Palin."),
		new Card("Frolicking."),
		new Card("Not giving a shit about the Third World."),
		new Card("My relationship status."),
		new Card("Barack Obama."),
		new Card("Mouth herpes."),
		new Card("Wiping her butt."),
		new Card("Pedophiles."),
		new Card("Doin' it in the butt."),
		new Card("Being fabulous."),
		new Card("An M. Night Shyamalan plot twist."),
		new Card("A bag of magic beans."),
		new Card("Dead parents."),
		new Card("My sex life."),
		new Card("Riding off into the sunset."),
		new Card("Dick fingers."),
		new Card("The Virginia Tech Massacre."),
		new Card("Queefing."),
		new Card("Tangled Slinkys."),
		new Card("Civilian casualties."),
		new Card("Leprosy."),
		new Card("Grave robbing."),
		new Card("Tentacle porn."),
		new Card("Bill Nye the Science Guy."),
		new Card("New Age music."),
		new Card("72 virgins."),
		new Card("Hope."),
		new Card("Passing a kidney stone."),
		new Card("A mime having a stroke."),
		new Card("Classist undertones."),
		new Card("A mating display."),
		new Card("The Kool-Aid Man."),
		new Card("Not reciprocating oral sex."),
		new Card("Italians."),
		new Card("My soul."),
		new Card("A stray pube."),
		new Card("Jerking off into a pool of children's tears."),
		new Card("Getting really high."),
		new Card("Overcompensation."),
		new Card("Free samples."),
		new Card("Shaquille O'Neal's acting career."),
		new Card("Half-assed foreplay."),
		new Card("Explosions."),
		new Card("White privilege."),
		new Card("Road head."),
		new Card("Poorly-timed Holocaust jokes."),
		new Card("8 oz. of sweet Mexican black-tar heroin."),
		new Card("Judge Judy."),
		new Card("Altar boys."),
		new Card("Scientology."),
		new Card("Justin Bieber."),
		new Card("Alcoholism."),
		new Card("My genitals."),
		new Card("Winking at old people."),
		new Card("Golden showers."),
		new Card("Racism."),
		new Card("Kids with ass cancer."),
		new Card("Hurricane Katrina."),
		new Card("Lumberjack fantasies."),
		new Card("An asymmetric boob job."),
		new Card("Asians who aren't good at math."),
		new Card("The Blood of Christ."),
		new Card("A brain tumor."),
		new Card("Prancing."),
		new Card("The Hamburglar."),
		new Card("Police brutality."),
		new Card("A robust mongoloid."),
		new Card("Pooping back and forth. Forever."),
		new Card("Bitches."),
		new Card("Stephen Hawking talking dirty."),
		new Card("Getting so angry that you pop a boner."),
		new Card("Tasteful sideboob."),
		new Card("Two midgets shitting into a bucket."),
		new Card("Racially-biased SAT questions."),
		new Card("Anal beads."),
		new Card("Surprise sex!"),
		new Card("Dead babies."),
		new Card("Masturbation."),
		new Card("The Hustle."),
		new Card("Obesity."),
		new Card("Child beauty pageants."),
		new Card("Kamikaze pilots."),
		new Card("Powerful thighs."),
		new Card("Women's suffrage."),
		new Card("John Wilkes Booth."),
		new Card("Parting the Red Sea."),
		new Card("Harry Potter erotica."),
		new Card("Grandma."),
		new Card("Porn stars."),
		new Card("A monkey smoking a cigar."),
		new Card("Lance Armstrong's missing testicle."),
		new Card("Children on leashes."),
		new Card("Multiple stab wounds."),
		new Card("Oompa-Loompas."),
		new Card("Peeing a little bit."),
		new Card("The miracle of childbirth."),
		new Card("Another goddamn vampire movie."),
		new Card("Active listening."),
		new Card("A gassy antelope."),
		new Card("BATMAN!!!"),
		new Card("Black people."),
		new Card("Serfdom."),
		new Card("The Trail of Tears."),
		new Card("Ghosts."),
		new Card("The Dance of the Sugar Plum Fairy."),
		new Card("Finger painting."),
		new Card("Robert Downey, Jr."),
		new Card("Muhammed (Praise Be Unto Him)."),
		new Card("Famine."),
		new Card("AXE Body Spray."),
		new Card("The Force."),
		new Card("Cybernetic enhancements."),
		new Card("Mr. Clean, right behind you."),
		new Card("Third base."),
		new Card("A fetus."),
		new Card("Women in yogurt commercials."),
		new Card("Copping a feel."),
		new Card("Sexual tension."),
		new Card("Dry heaving."),
		new Card("Centaurs."),
		new Card("Wifely duties."),
		new Card("Hot people."),
		new Card("Kanye West."),
		new Card("The Amish."),
		new Card("When you fart and a little bit comes out."),
		new Card("Viagra&reg;."),
		new Card("Five-Dollar Footlongs&trade;."),
		new Card("The Tempur-Pedic&reg; Swedish Sleep System&trade;."),
		new Card("Fancy Feast&reg;."),
		new Card("Hot Pockets&reg;."),
		new Card("Domino's&trade; Oreo&trade; Dessert Pizza."),
		new Card("The &Uuml;bermensch."),
		new Card("Adderall&trade;."),
		new Card("GoGurt&reg;."),
		new Card("A Super Soaker&trade; full of cat pee."),
		new Card("Lunchables&trade;."),
		new Card("The Make-A-Wish&reg; Foundation."),
		new Card("A Bop It&trade;."),
		new Card("Home video of Oprah sobbing into a Lean Cuisine&reg;."),
		new Card("Switching to Geico&reg;."),
		new Card("Advice from a wise, old black man."),
		new Card("The Devil himself."),
		new Card("The art of seduction."),
		new Card("Funky fresh rhymes."),
		new Card("The light of a billion suns."),
		new Card("Destroying the evidence."),
		new Card("Silence."),
		new Card("Growing a pair."),
		new Card("Synergistic management solutions."),
		new Card("Wet dreams."),
		new Card("A live studio audience."),
		new Card("The Great Depression."),
		new Card("An M16 assault rifle."),
		new Card("Poopy diapers."),
		new Card("Tickling Sean Hannity, even after he tells you to stop."),
		new Card("Stalin."),
		new Card("A spastic nerd."),
		new Card("Rush Limbaugh's soft, shitty body."),
		new Card("Capturing Newt Gingrich and forcing him to dance in a monkey suit."),
		new Card("Battlefield amputations."),
		new Card("Brown people."),
		new Card("Rehab."),
		new Card("An ugly face."),
		new Card("Menstrual rage."),
		new Card("An uppercut."),
		new Card("Shiny objects."),
		new Card("50,000 volts straight to the nipples."),
		new Card("A bucket of fish heads."),
		new Card("Hospice care."),
		new Card("Being fat and stupid."),
		new Card("Getting married, having a few kids, buying some stuff, retiring to Florida, and dying."),
		new Card("A pyramid of severed heads."),
		new Card("Crucifixion."),
		new Card("A subscription to Men's Fitness."),
		new Card("Some god-damn peace and quiet."),
		new Card("A micropig wearing a tiny raincoat and booties."),
		new Card("Used panties."),
		new Card("The penny whistle solo from 'My Heart Will Go On.'"),
		new Card("A tribe of warrior women."),
		new Card("An oversized lollipop."),
		new Card("Helplessly giggling at the mention of Hutus and Tutsis."),
		new Card("Not wearing pants."),
		new Card("Consensual sex."),
		new Card("Her Majesty, Queen Elizabeth II.")
	};
	
	@Override
	public String getDeckName()
	{
		return "Third Version";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "3.0";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}