package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckGameGrumps extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("Welcome back to _."),
		new Card("Welcome to Sonic Team! We make _, I think!"),
		new Card("What am I willing to put up with today?"),
		new Card("What can be found in Arin's chins?"),
		new Card("What do Mumbo's magic words mean?"),
		new Card("What is the boopinest shit?"),
		new Card("WHAT THE FUCK IS A _?!"),
		new Card("What's better than Skyward Sword?"),
		new Card("What's the real reason Jon left?"),
		new Card("When I look in the mirror I see _."),
		new Card("Who replaced Jon when he left GameGrumps?"),
		new Card("Why is Steam Train so controversial?"),
		new Card("WOOP WOOP WOOP I'M A _!"),
		new Card("You know what fan mail makes me the happiest every time I see it? It's the ones where people are like, "),
		new Card("You're ruining my integrity! _ won't hire me now!"),
		new Card("I've been _ again!"),
		new Card("Rolling around at the speed of _!"),
		new Card("This time on Guest Grumps, we have _."),
		new Card("Top five games, go! 1? Mega Man X. 2-5? _."),
		new Card("Use your _!"),
		new Card("Look at this guy, he's like _."),
		new Card("Look, it's _!"),
		new Card("Next time on Game Grumps, _!"),
		new Card("Nightshade: The Claws of _."),
		new Card("Number one! With a bullet! Zoom in on the _!"),
		new Card("Oh, it's _!"),
		new Card("One slice of _ please."),
		new Card("Pikachu, use your _ attack!"),
		new Card("Put a hole in that _!"),
		new Card("Real talk? _."),
		new Card("Jon's mom called him to tell him about _."),
		new Card("Kirby has two iconic abilities: suck and _."),
		new Card("Listen to the _ on this shit."),
		new Card("Jon believes that the most important part of any video game is _."),
		new Card("Jon can't get enough of _."),
		new Card("Jon can't survive air travel without _."),
		new Card("Jon just wants to touch _."),
		new Card("Is there anything to gain from this?"),
		new Card("It's no use! Take _!"),
		new Card("Jon and Arin suck at _."),
		new Card("Jon and Arin win! They realize _ is more important."),
		new Card("If the _ wasn't there, I would do. But it's there, so it's not."),
		new Card("How many _ does Mega Man get?"),
		new Card("How many nose hairs does _ have?"),
		new Card("I certainly can't do it without you, and I know you can't do it without _!"),
		new Card("I tell you once, I tell you twice! _ is good for economy!"),
		new Card("I wanna put my _ in her!"),
		new Card("I'm not even SELLING _!"),
		new Card("Do you remember the episode where Ash caught a _?"),
		new Card("Don't throw _! It's expensive to somebody!"),
		new Card("Dude, real talk? _."),
		new Card("Eat your _, son."),
		new Card("Egoraptor's fiancee is actually a _."),
		new Card("Everybody wants to know about me, but they don't know about my _."),
		new Card("Fool me once, I'm mad. Fool me twice? How could you. Fool me three times, you're officially _."),
		new Card("For my first attack, I will juggle _ to impress you."),
		new Card("Fuck, I found a _."),
		new Card("Game Grumps: sponsored by _."),
		new Card("Give _ a chance! He'll grow on you!"),
		new Card("_? Ten-outta-ten!"),
		new Card("_. I AAAAAAIN’T HAVIN’ THAT SHIT!"),
		new Card("_. It's no use!"),
		new Card("_. MILLIONS ARE DEAD!!!"),
		new Card("_. Put that in, Barry."),
		new Card("_. This is like one of my Japanese animes!"),
		new Card("...What the bloody hell are you two talking about?!"),
		new Card("These new _ t-shirts are gonna change some lives, Arin.', 0, 1, "),
		new Card("You want cheese pizza?"),
		new Card("And then, as a fuckin' goof, I'd put a hole in _."),
		new Card("And there it was...Kirby had finally met the _ of the lost city."),
		new Card("Arin believes that the most important part of any video game is _."),
		new Card("Arin has an adverse reaction to _."),
		new Card("Barry entertains himself by watching old episodes of _."),
		new Card("Barry, add _ into the video!"),
		new Card("Barry, we need a replay on _."),
		new Card("BARRY! SHOW _ AGAIN!"),
		new Card("Barry's sheer skill at _ is unmatched."),
		new Card("I don't like the _ flavor."),
		new Card("_ don't even cost this less!"),
		new Card("_ Grumps!"),
		new Card("_ has aged really well."),
		new Card("_ is GREAT GREAT GREAT!"),
		new Card("_ is Jon's favorite video game of all time."),
		new Card("_ is not Jon's strong suit."),
		new Card("_ Train!"),
		new Card("_ WINS!"),
		new Card("_: Better than deer shit!"),
		new Card("Welcome back to _ _!"),
		new Card("Real talk? Is that _ _?"),
		new Card("Look at that _-ass _!"),
		new Card("JON'S _, SHOW US YOUR _."),
		new Card("The Grumps' latest silly player names are _ and _."),
		new Card("If you don't know what _ is, you can't go to _."),
		new Card("In this corner, _; in the other corner, _; it's Game Grumps VS!"),
		new Card("IF I CAN'T BE _, I SURE AS HELL CAN BE _!!"),
		new Card("COME ON AND _, AND WELCOME TO THE _!"),
		new Card("If _ evolved from _, why the fuck is there still _, dude?!"),
		new Card("_? Pretty smart. _? Pretty fuckin' smart. _? FUCKING GENIUS!!!!")
	}, responseCards = new Card[]{
		new Card("...Metal Gear?!"),
		new Card("A humanlike bat with tits."),
		new Card("A little dingle-dang."),
		new Card("A replay from Barry."),
		new Card("A Scottish bloke that talks too fast."),
		new Card("A Sonic."),
		new Card("A whale making a seal noise."),
		new Card("Accidentally resetting a video game."),
		new Card("Anne Frank doing a striptease."),
		new Card("Arin actually winning a Game Grumps VS."),
		new Card("Arin Hanson / Egoraptor."),
		new Card("Arin's big floppy penis."),
		new Card("Arin's dicksaber."),
		new Card("Arin's voice acting."),
		new Card("Barry Kramer."),
		new Card("Barry's censorship noises."),
		new Card("Becoming a vegetarian, then becoming clinically depressed."),
		new Card("Being forced to replay the same section of the game over and over."),
		new Card("Birdemic."),
		new Card("Borderline narcissism."),
		new Card("Breaking a basketball net's back board."),
		new Card("Breaking into song."),
		new Card("Brian / Frank / Steve / Willard / Jonathan / Michael IV / Michael III / Michael Jordan / Scott."),
		new Card("Bumping butts."),
		new Card("Buying chicken fingers for homeless people."),
		new Card("Carefully escorting Anna."),
		new Card("Catharsis."),
		new Card("Cheese pizza."),
		new Card("Chu Chu Rocket."),
		new Card("Chulip."),
		new Card("Comparing someone to a trainwreck."),
		new Card("Completely missing the tutorials and instructions."),
		new Card("Cumfaggots."),
		new Card("Dan getting some action with one of Egoraptor's action figures."),
		new Card("Danny Sexbang."),
		new Card("Danny's crippling Skittles addiction."),
		new Card("Dipping your balls in the sand."),
		new Card("Dixon."),
		new Card("Donkey-ass Kong."),
		new Card("Drakkhen's realistic fight sequences."),
		new Card("Drawing the line in the fucking sand."),
		new Card("Eating the Holocaust."),
		new Card("Eating your peas."),
		new Card("Egofaptor."),
		new Card("Ending an episode on 'Heil Hitler!'"),
		new Card("The eyeless girl demographic."),
		new Card("Fast-forwarding."),
		new Card("Fighting Iblis for the hundredth time."),
		new Card("Fooling me three times."),
		new Card("Fuckin' Larry."),
		new Card("FUCKING LEGO CARS!!?!"),
		new Card("Game feel."),
		new Card("Game Grumps remixes."),
		new Card("Game Grumps VS."),
		new Card("Game Grumps."),
		new Card("Garshstostoles."),
		new Card("GeorgLopez."),
		new Card("Getting censored by a stampede of elephants."),
		new Card("Getting diddled again."),
		new Card("Getting fucking ganked."),
		new Card("Getting horribly diarrhea'd on by an owl."),
		new Card("Getting killed by a motherfucking paralyzed Taillow."),
		new Card("Getting stuck on the ceiling for no explicable reason."),
		new Card("Getting violently sick at MAGfest."),
		new Card("Goof Troop."),
		new Card("Goofy masturbating in the fields."),
		new Card("Grade A meat."),
		new Card("Grant Kirkhope."),
		new Card("Grant Kirkhope’s knackers."),
		new Card("GREAT! GREAT! GREAT!"),
		new Card("Grep."),
		new Card("Grumping it."),
		new Card("Güf Troop."),
		new Card("Half the deal for twice the price!"),
		new Card("Having a cough that lasts forever."),
		new Card("Helicopter tits."),
		new Card("Hepatitis Sea."),
		new Card("Hitting a Nightshade cartridge with Thor’s Hammer only to break the hammer."),
		new Card("Homoerotic subtext between two grown men playing video games."),
		new Card("Ice hair."),
		new Card("Incriminating footage of Jon."),
		new Card("Insta-killing your partner with the Select button."),
		new Card("It being no use."),
		new Card("Jacques."),
		new Card("JonTron."),
		new Card("Jon winning. AS USUAL."),
		new Card("Jon's soulful singing."),
		new Card("Jon/Arin slash fiction."),
		new Card("JonTron’s musical theater voice."),
		new Card("Js'keep goin'."),
		new Card("Killing zombies by typing on a keyboard-gun."),
		new Card("Kirby."),
		new Card("Kitty Cat Dance Party."),
		new Card("Learning that your son is dead, but not caring because you didn't want him anyway."),
		new Card("Lemon and Bill."),
		new Card("Lightsaber Fightsaber."),
		new Card("Mediocrity, as a power."),
		new Card("Mega Man."),
		new Card("Mike Tyson."),
		new Card("Mispronouncing Duran Duran."),
		new Card("Mister Mosquito."),
		new Card("MomTron."),
		new Card("Moundo."),
		new Card("Naughty Bear."),
		new Card("Nazi von Killyou."),
		new Card("Ninja Sex Party."),
		new Card("Nixon."),
		new Card("NO JON NO."),
		new Card("NOT FUCKING THIS!"),
		new Card("Not knowing the controls to Nickelodeon GUTS."),
		new Card("Not reading the game's instructions."),
		new Card("Obeying Protoman and burning down a forest."),
		new Card("Pause balls."),
		new Card("Pelistorm."),
		new Card("Playing a terrible game for more than a hundred episodes."),
		new Card("Playing slaps to break a tie."),
		new Card("PONY.MOV."),
		new Card("Poopy butt."),
		new Card("Poppy Bros."),
		new Card("Princess Elise's octopus face."),
		new Card("Punching a hole in a gingerbread house."),
		new Card("Queefing bombs out of your vagina."),
		new Card("Racial slurs."),
		new Card("RIDIN’ ON CARS!!!"),
		new Card("Robots ordering cheese pizza."),
		new Card("Rocket. To the moon."),
		new Card("Rolling around at the speed of sound."),
		new Card("RubberRoss."),
		new Card("Rouge's gross bat face."),
		new Card("Screaming out Whitney Houston’s “I Will Always Love You�? in primal agony."),
		new Card("Sequelitis."),
		new Card("Seven asses."),
		new Card("Signing and destroying a copy of Sonic '06."),
		new Card("Silver the Hedgehog."),
		new Card("Sneaking dirty British humour into an unassuming video game about a bear and a bird."),
		new Card("Snow white shit."),
		new Card("Snowboarding uphill"),
		new Card("Solid Snake."),
		new Card("Sonic '06."),
		new Card("Spice World."),
		new Card("Spraying compressed air with a bittering agent in your face, and subsequently vomiting."),
		new Card("Stairfax Temperatures."),
		new Card("Staring at a menu while Ross stuffs his disgusting face with candy."),
		new Card("Stasis-ing the drill."),
		new Card("Steam Train."),
		new Card("Sticky sap."),
		new Card("Stretch Panic."),
		new Card("STRGG."),
		new Card("Struggling to fight Silver the Hedgehog."),
		new Card("Sucking blood from a Japanese girl's tits."),
		new Card("Suzy the Goose."),
		new Card("TENOUTTATEN."),
		new Card("That guy."),
		new Card("The Awesome Series."),
		new Card("The band Egoraptor."),
		new Card("The Chinless Wonder."),
		new Card("The Goshdangodon."),
		new Card("The Higgs Boson."),
		new Card("The Knuckles wall glitch."),
		new Card("The rarest form of Arin having fun."),
		new Card("The realization that friendship is more important."),
		new Card("Three big feet of pleasure."),
		new Card("Tonguing up."),
		new Card("Typing 'C D PLAYER' and getting 'MODEL CAR.'"),
		new Card("WAAAAAAAVE LAAAAZEEEEEEER."),
		new Card("Walking around in my banana shoes."),
		new Card("World Dick Barf Syndrome.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Game Grumps";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "GG";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}