package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckTGWTG extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("To top One More Day, future comic writers will use ____ to break up a relationship.", true),
		new Card("The real reason MAGFest was ruined was ____.", true),
		new Card("The reason Linkara doesn't like milk in his cereal is ____.", true),
		new Card("The secret of Linkara's magic gun is ____.", true),
		new Card("For the next Anniversary event, the TGWTG producers must battle ____ to get ____.", true),
		new Card("If a dog and a dolphin can get along, why not ____ and ____?", true),
		new Card("If I wanted to see ____, I'll stick with ____, thank you very much.", true),
		new Card("I asked Linkara to retweet ____, but instead, he retweeted ____.", true),
		new Card("Next time on Obscurus Lupa Presents: ", true),
		new Card("Todd in the Shadows broke the Not a Rhyme button when the singer tried to rhyme ____ with ____.", true),
		new Card("Welshy is to ____ as Sad Panda is to ____.", true),
		new Card("Linkara's next story arc will involve him defeating ____ with the power of  ____.", true),
		new Card("Rock and Roll is nothing but ____ and the rage of ____!", true),
		new Card("Being fed up with reviewing lamps, what obscure topic did Linkara review next?", true),
		new Card("What did the commenters bitch about next to Doug?", true),
		new Card("The next crossover will have ____ and ____ review ____.", true),
		new Card("We all made a mistake when we ate ____ at MAGFest.", true),
		new Card("Kyle's next student film will focus on ____.", true),
		new Card("The RDA chat knew Nash was trolling them when he played ____.", true),
		new Card("Why does Linkara have all of those Cybermats?", true),
		new Card("____ will be the subject of the next TGWTG panel at MAGFest.", true),
		new Card("At his next con appearance, Linkara will cosplay as ____.", true),
		new Card("WAIT!  I have an idea!  It involves using ____!", true),
		new Card("What does Linkara eat with his chicken strips?", true),
		new Card("Why was Radio Dead Air shut down this time?", true),
		new Card("If you value your life, never mention ____ around Oancitizen.", true),
		new Card("Arlo P. Arlo's newest weapon combines ____ and ____!", true),
		new Card("____ and ____ are in the worst comic Linkara ever read.", true),
		new Card("____ is only on the site because of ____.", true),
		new Card("The newest fanfic trend is turning ____ into ____.", true),
		new Card("____ is the reason Linkara doesn't like to swear.", true),
		new Card("____ was completely avoidable!", true),
		new Card("____ will live!", true),
		new Card("____ is something else Diamanda Hagan has to live with every day.", true),
		new Card("____ should be on TGWTG.", true),
		new Card("____ was the first thing to go when Hagan took over the world.", true),
		new Card("____! What are you doing here?", true),
		new Card("I love ____. It's so bad.", true),
		new Card("____. With onions.", true),
		new Card("____ is the theme of this year's anniversary crossover.", true),
		new Card("A ____ Credit Card!?", true),
		new Card("Blip checks are way smaller in January so I'll spend the month riffing on ____ to gain more views.", true),
		new Card("Brad Tries ____.", true),
		new Card("Doug still regrets the day he decided to do a Let's Play video for 'Bart Simpson's ____ Adventure'.", true),
		new Card("Enemies of Diamanda Hagan have been known to receive strange packages filled with  ____.", true),
		new Card("High and away on a wing and a prayer, who could it be? Believe it or not, it's just ____.", true),
		new Card("What broke Nash this week?", true),
		new Card("I ____ so you don't have to.", true),
		new Card("I AM THE VOICELESS. THE NEVER SHOULD. I AM ____.", true),
		new Card("I prefer for MY exploitation films to have ____, thank you very much.", true),
		new Card("I'm looking forward to Jesuotaku's playthrough of Fire Emblem: ____.", true),
		new Card("In his latest review, Phelous was killed by ____.", true),
		new Card("It was all going well until they found ____.", true),
		new Card("JW confirms, you can play ____,", true),
		new Card("Next January, the Nostalgia Critic is doing ____ Month.", true),
		new Card("Of Course! Don't you know anything about ____?", true),
		new Card("On the other side of the Plot Hole, the Nostalgia Critic found ____.", true),
		new Card("Reactions were mixed when ____ joined TGWTG.", true),
		new Card("Sage has presented JO with the new ecchi series ____.", true),
		new Card("Sean got his head stuck in ____.", true),
		new Card("The invasion of Molassia was tragically thwarted by ____.", true),
		new Card("The newest reviewer addition to the site specializes in ____.", true),
		new Card("The next person to leave Channel Awesome will announce their departure via ____.", true),
		new Card("The next Renegade Cut is about ____ in a beloved children's movie.", true),
		new Card("The Nostalgia Critic will NEVER review ____.", true),
		new Card("The only thing Linkara would sell his soul for is ____.", true),
		new Card("What is the real reason Demo Reel failed?", true),
		new Card("This weekend, the nation of Haganistan will once again commence its annual celebration of ____.  ", true),
		new Card("To troll the RDA chat this time, Todd requested a song by ____.", true),
		new Card("Todd knew he didn't have a chance after trying to seduce Lupa with ____.", true),
		new Card("Turns out, that wasn't tea in MikeJ's cup, it was ____.", true),
		new Card("Viewers were shocked when Paw declared ____ the best song of the movie.", true),
		new Card("WE WERE FIGHTING LIKE ____.", true),
		new Card("Well, I've read enough fanfic about ____ and Lupa to last a lifetime.", true),
		new Card("What does Nash like to sing about?", true),
		new Card("What does Todd look like under his mask?", true),
		new Card("What doesn't go there?", true),
		new Card("What else does Diamanda Hagan have to live with every day?", true),
		new Card("What is in Sci Fi Guy's vest?", true),
		new Card("What will Tara name her next hippo?", true),
		new Card("What's holding up the site redesign?", true),
		new Card("What's really inside the Plot Hole?", true),
		new Card("What's the real reason nobody has ever played the TGWTG Panel Drinking Game?", true),
		new Card("What's up next on WTFIWWY?", true),
		new Card("When the JesuOtaku stream got to the ", true),
		new Card("Why can't Film Brain stop extending his final vowels?", true),
		new Card("90's Kid's favorite comic is ____.", true),
		new Card("Because poor literacy is ____.", true),
		new Card("He is a glitch. He is missing. He is ____.", true),
		new Card("In a surprise twist, the villain of Linkara's next story arc turned out to be ____.", true),
		new Card("Linkara now prefers to say ____ in lieu of ", true),
		new Card("Of course!  Don't you know anything about ___?", true),
		new Card("Snowflame feels no ____.", true),
		new Card("Snowflame found a new love besides cocaine. What is it?", true),
		new Card("So let's dig into ____ #1.", true),
		new Card("Where'd he purchase that?", true),
		new Card("When is the next History of Power Rangers coming out?", true),
		new Card("What is as low as the standards of the 90's Kid?", true),
		new Card("What delayed the next History of Power Rangers?", true),
		new Card("A piece of ____ is missing.", true),
		new Card("What do Brad and Floyd like to do after a long day?", true),
		new Card("At least he didn't fuck ____.", true),
		new Card("Hello, and welcome to Atop ____, where ____ burns.", true),
		new Card("Hello, I'm the Nostalgia Critic. I remember ____ so you don't have to!", true),
		new Card("If you are able to deflect ____ with ____, we refer to it as ", true),
		new Card("In her newest review, Diamanda Hagan finds herself in the body of ____.", true),
		new Card("Last time I took bath salts, I ended up ____ in ____.", true),
		new Card("Tara taught me that if you're going to engage in ____, then ____ isn't a good idea.", true),
		new Card("The website was almost called ", true),
		new Card("They even took ____! Who does that?!", true),
		new Card("You may be a robot, but I AM ____!", true),
		new Card("____ didn't make it onto the first AT4W DVD.", true),
		new Card("____ is part of the WTFIWWY wheelhouse.", true),
		new Card("____ is the subject of the Critic's newest review.", true),
		new Card("____ is the subject of the missing short from The Uncanny Valley.", true),
		new Card("____ needs more gay.", true),
		new Card("____ will be Linkara's next cosplay.", true),
		new Card("____ wound up in this week's top WTFIWWY story.", true),
		new Card("After getting snowed in at MAGfest, the reviewers were stuck with ____.", true),
		new Card("ALL OF ____.", true),
		new Card("An intervention was staged for Linkara after ____ was discovered in his hat.", true),
		new Card("As a way of apologizing for a poorly received episode, E Rod promised to review ____.", true),
		new Card("Being done with My Little Pony, 8-Bit Mickey has moved onto ____.", true),
		new Card("Birdemic 3: ____", true),
		new Card("E Rod has a new dance move called ____.", true),
		new Card("Even Kyle thinks ____ is pretentious.", true),
		new Card("Florida's new crazy is about ____.", true),
		new Card("Hello, I'm a ____.", true),
		new Card("Here There Be ____.", true),
		new Card("Hey kids, I'm Nash, and I couldn't make ____ up if I tried.", true),
		new Card("Hey Nash, whatcha playin'?", true),
		new Card("How is Bennett going to creep out Ask That Guy this time? ", true),
		new Card("In his most recent Avatar vlog, Doug's favorite thing about the episode was ____.", true),
		new Card("In the newest Cheap Damage, CR looks at the trading card game version of ____.", true),
		new Card("IT'S NOT ____!", true),
		new Card("It's not nudity if there's ____.", true),
		new Card("Leon Thomas almost named his show Renegade ____.", true),
		new Card("Linkara was shocked when he found out Insano was secretly ____.", true),
		new Card("Linkara's Yu-Gi-Oh deck is built up with nothing but ____.", true),
		new Card("Luke Mochrie proved he was still part of the site by____.", true),
		new Card("MikeJ's next sexual conquest is ____.", true),
		new Card("Nash had a long day at work, so tonight he'll stream ____.", true),
		new Card("Nash rejected yet another RDA request for ____.", true),
		new Card("Nash's recent rant about Microsoft led to ____.", true),
		new Card("Nash's Reviewer Spotlight featured ____.", true),
		new Card("New rule in the RDA Drinking Game:  Every time ____ happens, take a shot!", true),
		new Card("On the next WTFIWWY, Nash will give us a brief history of ____.", true),
		new Card("The best Bad Movie Beatdown sketch is where Film Brain ropes Lordhebe into ____.", true),
		new Card("The controversy over ad-blocking could be easily solved by ____.", true),
		new Card("The easiest way to counteract a DMCA takedown notice is with ____.", true),
		new Card("The last time Welshy and Film Brain were in a room together, they ended up ____.", true),
		new Card("The new site that will overtake TGWTG is ____.", true),
		new Card("The newest Rap Libs makes extensive use of the phrase '____.'", true),
		new Card("The theme of this week's WTFIWWY is ____.", true),
		new Card("This week, Nash's beer is made with ____.", true),
		new Card("What did Doug bring to the set of To Boldly Flee?", true),
		new Card("What does Ven have to do now?", true),
		new Card("What hot, trendy new dance will feature in Paw's next Dance Spectacular?", true),
		new Card("What is hidden in Linkara's hat?", true),
		new Card("What is literally the only thing tastier than a dragon's soul?", true),
		new Card("What is Snowflame's only known weakness?", true),
		new Card("What is the name of the next new Channel Awesome contributor?", true),
		new Card("What killed Harvey Finevoice's son?", true),
		new Card("What made Dodger ban someone from the RDA chat this week?", true),
		new Card("What new upgrade did Nash give Laura?", true),
		new Card("What was the first sign that Linkara was turning evil?", true),
		new Card("What will Nash try to kill next with his hammer?", true),
		new Card("When Arlo The Orc turns into a werewolf, he likes to snack on ____.", true),
		new Card("When interviewing Linkara, be sure to ask him about ____!", true),
		new Card("When not reviewing or ruling Haganistan with an iron fist, Hagan's hobby is ____.", true),
		new Card("Who REALLY called Oancitizen to help him snap out of his ennui?", true),
		new Card("Whose ass did Zodann kick this time?", true),
		new Card("Why did Nash go to Chicago?", true),
		new Card("Why doesn't Doug ever attend MAGFest?", true),
		new Card("Why doesn't Film Brain have an actual reviewer costume?", true),
		new Card("The MAGFest Nerf War took a dark turn when ____ was waylaid by ____.", true),
		new Card("For a late night snack, Nash made a sandwich of ____ and ____.", true),
		new Card("The next TGWTG porn spoof?  ____ with ____!", true),
		new Card("Putting ____ in ____? That doesn't go there!", true),
		new Card("In trying to ban ____, Florida accidentally banned ____.", true),
		new Card("If ____ got to direct an Uncanny Valley short, it would have featured ____.", true),
		new Card("At ConBravo, ____ will be hosting a panel on ____.", true),
		new Card("At MAGFest, ____ will host a panel focusing on ____.", true),
		new Card("'Greetings, dear listeners.  Won't you join ____ for ____?'", true),
		new Card("Sad Panda is actually ____ and  ____.", true),
		new Card("I'm going to die watching ____ review ____.", true),
		new Card("In a new latest announcement video, ____ has announced an appearance at ____.", true),
		new Card("After ____, Phelous regenerated into ____. ", true),
		new Card("____ and ____ would make awesome siblings.", true),
		new Card("Some fangirls lay awake all night thinking of ____ and ____ together.", true),
		new Card("In my new show, I review ____ while dressed like ____.", true),
		new Card("Luke's newest character is ____, the Inner ____.", true),
		new Card("Good evening! I am ____ of  ____.", true),
		new Card("____ is the reason that ____ picked 'AIDS.'", true),
		new Card("Nash's newest made-up curse word is ____-____-____!", true),
		new Card("Using alchemy, combine ____ and ____ to make ____!", true),
		new Card("Write Linkara's next storyline as a haiku.", true),
		new Card("Nash will build his next contraption with just ____, ____, and ____.", true),
		new Card(" ____  did ____ to avoid ____.", true),
		new Card("Make a WTFIWWY story.", true),
	}, responseCards = new Card[]{
		new Card("Rob Liefeld.", false),
		new Card("Literally drinking bottled fangirl tears.", false),
		new Card("LordKaT's used nipple tassles.", false),
		new Card("Luke's curly hair.", false),
		new Card("Lupa's brand of hair dye.", false),
		new Card("Ma-Ti being castrated and having his balls shipped to Oancitizen in the mail by Diamanda Hagan.", false),
		new Card("Magical fairy sex.", false),
		new Card("Making angry love to a DVD copy of ", false),
		new Card("Mako.", false),
		new Card("Malachite's Hand.", false),
		new Card("Maven's secret sparkling vampire dildo.", false),
		new Card("Melvin, brother of the Joker.", false),
		new Card("Naked crazy.", false),
		new Card("Nash breaking his ass.", false),
		new Card("Nash dressed in drag.", false),
		new Card("Nash in a gimp suit.", false),
		new Card("Nash popping a blood vessel over Florida.", false),
		new Card("Nash.", false),
		new Card("Nash's long, long hair.", false),
		new Card("Newborn porn.", false),
		new Card("Nun fuckery.", false),
		new Card("Oancitizen.", false),
		new Card("Over-intrusive fanboys.", false),
		new Card("Having sex at a screening of Mr. Popper's Penguins.", false),
		new Card("Phelous making love to his Turtles collection.", false),
		new Card("Poop, as a plan.", false),
		new Card("Punching your foe in the stomach and screaming 'I AM A MAN!'", false),
		new Card("PushingUpRoses' bird tattoos.", false),
		new Card("Putting sexy pantyhose on your dog.", false),
		new Card("Radio Dead Air.", false),
		new Card("Reading fan fiction on a live stream.", false),
		new Card("Reading the comments.", false),
		new Card("Requesting John Cage's 4'33 on Radio Dead Air.", false),
		new Card("Reviewer dibs.", false),
		new Card("Robotic sex slaves that are made to feel sadness.", false),
		new Card("Rule 34 of Linkara and a lamp.", false),
		new Card("Sad Panda.", false),
		new Card("Santa Christ's raging boner.", false),
		new Card("Sharkleberry Finn-flavored Kool-Aid.", false),
		new Card("Shooting colored corn syrup up your nose.", false),
		new Card("Slightly creepy comments about Tara's hair.", false),
		new Card("Smoking kittens.", false),
		new Card("Snowdicking.", false),
		new Card("Snowflame, feeling no pain.", false),
		new Card("Sodomizing a loved one with a baseball bat.", false),
		new Card("Space Guy.", false),
		new Card("Spoony's fans.", false),
		new Card("Stickboy.", false),
		new Card("Storing your dead friend's ashes into a Quaker Oats can.", false),
		new Card("Suggestively eating a banana at the sight of David Bowie.", false),
		new Card("SYMBOLISM!", false),
		new Card("Taking someone by the shoulders, throwing them on the bed and riding them like a stallion.", false),
		new Card("That Aussie Guy.", false),
		new Card("That goddamned Colossus roar.", false),
		new Card("That one guy with snails.", false),
		new Card("The Blockbuster Buster.", false),
		new Card("The Cinema Snob Movie DVD.", false),
		new Card("THE COCK.", false),
		new Card("The Continuity Alarm.", false),
		new Card("The Film Renegado.", false),
		new Card("The five months when the Nostalgia Critic was dead.", false),
		new Card("The LAAAAAAAAAAAAAAAAAAAAAW!", false),
		new Card("The Makeover Fairy.", false),
		new Card("The pig fucking movie.", false),
		new Card("The plot hole.", false),
		new Card("The RDA drinking game.", false),
		new Card("The RDA IRC channel.", false),
		new Card("The Spocker.", false),
		new Card("The TGWTG site redesign.", false),
		new Card("The Wunder Boner.", false),
		new Card("This fecal matter you call ", false),
		new Card("Throwing a Baby Tumbles Surprise down a staircase.", false),
		new Card("Timing.", false),
		new Card("Todd's unmasked visage.", false),
		new Card("Using Crystal Pepsi as a substitute for lube.", false),
		new Card("Using your underwear to shoplift raw meat from your local Wal-Mart.", false),
		new Card("Vigorously shagging your sister while holding a mug of warm tea.", false),
		new Card("Welshy.", false),
		new Card("Whatever the hell Barfiesta was supposed to be.", false),
		new Card("Yet another Thunderdome reference.", false),
		new Card("Zodan The Unbouncable.", false),
		new Card("90's Kid's comic collection.", false),
		new Card("A Linkara cameo.", false),
		new Card("A plushie cybermat.", false),
		new Card("ALL THE COCAINE!!!", false),
		new Card("Harvey Finevoice's fine voice.", false),
		new Card("Killing clowns.", false),
		new Card("Linkara crying in his Gatorade made of cybermat tears.", false),
		new Card("Linkara stalking Gail Simone on Twitter.", false),
		new Card("Linkara's cybermat invasion force.", false),
		new Card("Linkara's fangirl support group.", false),
		new Card("Linkara's magic gun.", false),
		new Card("Linkara's masculine arms.", false),
		new Card("MAGfest.", false),
		new Card("Marzkara fanfiction.", false),
		new Card("Mechakara's phallic drill.", false),
		new Card("Reviews of $20 lamps.", false),
		new Card("A bat credit card.", false),
		new Card("A big long pink ding dong penis.", false),
		new Card("A Blip check.", false),
		new Card("A bootleg ninja turtle action figure possessed by Satan.", false),
		new Card("A car landing on a roof.", false),
		new Card("A case of disappearing bears.", false),
		new Card("A Chia-Child.", false),
		new Card("A congregation of bums.", false),
		new Card("A Crystal Pepsi&reg;-flavored enema.", false),
		new Card("A drugged Oancitizen in a schoolgirl outfit.", false),
		new Card("A greased-up meth guy.", false),
		new Card("A mexican car wash.", false),
		new Card("A misguided Tumblr activism campaign.", false),
		new Card("A mobile meth lab in your pants.", false),
		new Card("A novelty slot machine.", false),
		new Card("A Pan-Galactic Gargle Blaster.", false),
		new Card("A poorly-written ugly mess.", false),
		new Card("A really pimped out DeLorean.", false),
		new Card("A talking snail in a suit.", false),
		new Card("A titanic, undead, six-headed space dragon spewing bubbles.", false),
		new Card("Accidentally punching your cohost in the face.", false),
		new Card("ALL OF THE DICKS.", false),
		new Card("Almost dying at Sesame Street.", false),
		new Card("An art film Kyle's reviewed.", false),
		new Card("An autoclitorodectomy.", false),
		new Card("Andrew Dickman.", false),
		new Card("Angrily playing piano.", false),
		new Card("Ash.", false),
		new Card("Ash and Checkers.", false),
		new Card("Ask That Guy raped by Ma-Ti live.", false),
		new Card("ASS ASS ASS ASS ASS ASS ASS ASS.", false),
		new Card("Ass demons.", false),
		new Card("Awkward pity sex with a sparkly teenage Cthulu.", false),
		new Card("Because no one wants to see your dick.", false),
		new Card("Because the Kool-Aid Man is red.", false),
		new Card("Because there's nothing sexy at the Wal-Mart.", false),
		new Card("Beppo the Invisible Monkey.", false),
		new Card("BETRAYAL!", false),
		new Card("Big Jim Slade.", false),
		new Card("Blockbuster Buster busting a nut.", false),
		new Card("Breaking someone's spine by fucking.", false),
		new Card("Carl Copenhagen.", false),
		new Card("Casper.", false),
		new Card("Confusing The Last Angry Geek and Linkara.", false),
		new Card("CR's collection of My Little Pony pins.", false),
		new Card("Creepy fans at cons buying expensive stuff for MarzGurl.", false),
		new Card("Creepy guys in the RDA chat hitting on Tara.", false),
		new Card("Nash's creepy face.", false),
		new Card("Crying your eyes out at a bunch of online reviewers.", false),
		new Card("Crystal Pepsi&reg;.", false),
		new Card("Dark Nella.", false),
		new Card("David Bowie's package.", false),
		new Card("Diamanda Hagan's sexbot.", false),
		new Card("Diamanda's copy of Cockhammer.", false),
		new Card("Disney's Anne Frank.", false),
		new Card("Dogs wearing pantyhose.", false),
		new Card("Dolphin rape.", false),
		new Card("A douchequake.", false),
		new Card("Dr. Insano.", false),
		new Card("Dr. Wiki.", false),
		new Card("Explosively masturbating with Malachite's Hand.", false),
		new Card("Ferdinand Von Turrell.", false),
		new Card("Film Brain's lovely accent.", false),
		new Card("Finding out that ", false),
		new Card("Firing a blue shell at the opposing house ship.", false),
		new Card("Florida.", false),
		new Card("Florida Man.", false),
		new Card("Flying sex snakes in monocles and bow ties.", false),
		new Card("Fort Super-Awesome.", false),
		new Card("FOUR HOURS?!", false),
		new Card("Fuck yeah, SPARKLE SPARKLE SPARKLE!", false),
		new Card("Fucking bubbles.", false),
		new Card("Getting buggered by a giant hamster.", false),
		new Card("Going through the effort to build a wall in your back yard just to bash your head into it over and over again.", false),
		new Card("Gooby.", false),
		new Card("Hagan's dictator tendencies.", false),
		new Card("Hagan's make up artist.", false),
		new Card("Hagan's masturbating minion.", false),
		new Card("Hippo Queen Tara.", false),
		new Card("Hitler without the mustache.", false),
		new Card("Humping a can of trash.", false),
		new Card("I AM A MAN!", false),
		new Card("Invading a micronation in Nevada and making it your own.", false),
		new Card("JewWario's solar penis.", false),
		new Card("Kickassia.", false),
		new Card("Kitler.", false),
		new Card("Kyle humping a trashcan.", false),
		new Card("Linkara's 'special' comic books.", false),
		new Card("Linkara's hat.", false),
		new Card("Superboy Prime.", false),
		new Card("The Entity.", false),
		new Card("The legendary MAGFest orgy.", false),
		new Card("The most important job, reviewing a crappy comic book.", false),
		new Card("The next History of Power Rangers.", false),
		new Card("Youngblood's disease.", false),
		new Card("Twin clones of Hitler.", false),
		new Card("A disembodied orgasm hippo.", false),
		new Card("A doppelganger in black leather with a sword.", false),
		new Card("A guest appearance by Giovanni Jones, the talking lobster.", false),
		new Card("A naked rampage.", false),
		new Card("Bath salts.", false),
		new Card("Diamanda Hagan.", false),
		new Card("Frying the Coke.", false),
		new Card("Rapidly pounding themselves in the face with a hammer.", false),
		new Card("Sci-Fi Guy's ponytail.", false),
		new Card("Angry Joe.", false),
		new Card("Marzgurl.", false),
		new Card("Chester A. Bum.", false),
		new Card("Ask That Guy With The Glasses.", false),
		new Card("Dominic the Bartender.", false),
		new Card("Obscurus Lupa.", false),
		new Card("ChaosD1.", false),
		new Card("Skitch.", false),
		new Card("Y Ruler Of Time.", false),
		new Card("Linkara.", false),
		new Card("Mechakara.", false),
		new Card("Lord Vyce.", false),
		new Card("90's Kid.", false),
		new Card("Corporate Commander.", false),
		new Card("JewWario.", false),
		new Card("A demonic Teddy Ruxpin doll.", false),
		new Card("Luke.", false),
		new Card("Luke's inners.", false),
		new Card("PhelousD1.", false),
		new Card("Phelous.", false),
		new Card("Filmbrain.", false),
		new Card("Iron Liz.", false),
		new Card("Malachite.", false),
		new Card("Zodd.", false),
		new Card("The Executor.", false),
		new Card("PhilBuni.", false),
		new Card("Ven Gethenian.", false),
		new Card("That Sci-Fi Guy.", false),
		new Card("Black Lantern Spoony.", false),
		new Card("The Trousers Cosmic.", false),
		new Card("Nash's folksy, velvety voice.", false),
		new Card("Australia, Florida of the Pacific.", false),
		new Card("Angrily eating lettuce.", false),
		new Card("Mary Sewage.", false),
		new Card("A legion of mechawolves.", false),
		new Card("Linkara's futon.", false),
		new Card("The Gooby Curse.", false),
		new Card("ANCIENT EGYPT!", false),
		new Card("An obligatory cameo.", false),
		new Card("Dodger of Zion.", false),
		new Card("An elevator party.", false),
		new Card("Pants that need to be darkened.", false),
		new Card("Only being on the site because of the influence of famous acquaintences.", false),
		new Card("Enoby Dark'ness Dementia Raven TARA Way.", false),
		new Card("A legion of spiders.", false),
		new Card("A secret goat porn stash.", false),
		new Card("____.", false),
		new Card("*liveshot*.", false),
		new Card("8-Bit Mickey on an unstoppable merry-go-round.", false),
		new Card("80's Dan.", false),
		new Card("A Blip ad for the most embarrassing reality show ever.", false),
		new Card("A Brad Jones impersonation.", false),
		new Card("A crossover.", false),
		new Card("A Cybermat in a bow tie.", false),
		new Card("A delicious fried chicken holocaust.", false),
		new Card("A DMCA takedown notice.", false),
		new Card("A fan artist.", false),
		new Card("A FUCKING PONCHO!", false),
		new Card("A giant go-fuck-yourself spider.", false),
		new Card("A half naked, fencing JewWario.", false),
		new Card("A hand-basket of lobsters.", false),
		new Card("A Mr. T Trading Card.", false),
		new Card("A pile of skulls.", false),
		new Card("A pink tutu.", false),
		new Card("A plushie TARDIS.", false),
		new Card("A poorly made knockoff action figure.", false),
		new Card("A REALLY big hoopla about nothing.", false),
		new Card("A Serbian Film.", false),
		new Card("A smoking, muscled ice cream cone shooting guns and eye lasers.", false),
		new Card("A speeding NERF dart to the junk.", false),
		new Card("A squadron of attack Corgis.", false),
		new Card("A squadron of line-dancing hippos.", false),
		new Card("A strip-tease from the Nostalgia Critic.", false),
		new Card("A tauntaun puppy.", false),
		new Card("A very serious hat.", false),
		new Card("Ambiguously nude Linkara.", false),
		new Card("An electronic cigarette that resembles a Sonic Screwdriver.", false),
		new Card("An evangelizing minion.", false),
		new Card("An existential crisis over internet reviews.", false),
		new Card("An impassioned plea for understanding.", false),
		new Card("An unhinged Oancitizen rolling towards the sea.", false),
		new Card("Angry Joe dancing in a squid suit.", false),
		new Card("Angry Joe's raging boner.", false),
		new Card("Another fucking Iron Liz pun.", false),
		new Card("Another goddamn PhilBuni Vine.", false),
		new Card("Aplos, or Steve, the Wizard.", false),
		new Card("Arlo P. Arlo.", false),
		new Card("Arlo the Orc.", false),
		new Card("Ashens taking a blowtorch to a crappy toy.", false),
		new Card("Ashens.", false),
		new Card("Because...hippos.", false),
		new Card("Becoming possessed and insulting your colleague.", false),
		new Card("Being awkward around your favorite reviewer.", false),
		new Card("Bennett the Sage.", false),
		new Card("Big Butter Jesus.", false),
		new Card("Blip.", false),
		new Card("Brad, drinking a Turkey-flavored Jones Soda.", false),
		new Card("Bruno Matei.", false),
		new Card("Butchered Dutch.", false),
		new Card("Comicron One.", false),
		new Card("CR.", false),
		new Card("Cynthia Rothrock", false),
		new Card("DEATH FROM ABOOOOOVE!!!", false),
		new Card("Derek the Bard.", false),
		new Card("Derek the Bard's hat.", false),
		new Card("Disturbing comments in the RDA chat.", false),
		new Card("Dodger's ban chain.", false),
		new Card("Dodging blowjobs.", false),
		new Card("Dr. Tease & Dr. Block.", false),
		new Card("Dragging Oancitizen back home from a wild night of partying.", false),
		new Card("Dump cards.", false),
		new Card("E Rod's smooth, smooth dance skills.", false),
		new Card("Eating the flesh of your foes while howling at the moon.", false),
		new Card("Evilina.", false),
		new Card("Evilina's monstrous visage.", false),
		new Card("Film Brain, dressed tastefully in fashionable clothing.", false),
		new Card("Film Brain's hair.", false),
		new Card("Film Renegado creaming himself over Pacific Rim.", false),
		new Card("Forcing an NPC to haul your crap.", false),
		new Card("Fuckstick the Magic Dragon.", false),
		new Card("Gargoyle Cat.", false),
		new Card("Haganistan.", false),
		new Card("Harmony Korine.", false),
		new Card("HIPPOS!", false),
		new Card("Holly.", false),
		new Card("Il Neige in a freakishly accurate Film Brain costume.", false),
		new Card("Jaeris, the Gunslinger.", false),
		new Card("Joe Quesada.", false),
		new Card("Kali.", false),
		new Card("Kung Tai Ted.", false),
		new Card("Kyle playing GTA while drunk.", false),
		new Card("Kyle's 'unicorns.'", false),
		new Card("Laura, the Fender Stratocaster Goddess.", false),
		new Card("Linkara lying naked on his futon, playing with a Cybermat.", false),
		new Card("Linkara, dressed as the Green Ranger.", false),
		new Card("Linkara, dropping an F-Bomb.", false),
		new Card("Linkara, sexily eating a salad.", false),
		new Card("Linkara's massive ego.", false),
		new Card("Little Pluckies Ninja Protects.", false),
		new Card("Luke Mochrie's trust fund.", false),
		new Card("Maven of ze Eventide.", false),
		new Card("Mexican Spider-Man.", false),
		new Card("MikeJ.", false),
		new Card("Moarte.", false),
		new Card("Nash, dressed as The Undertaker.", false),
		new Card("Nash, making ", false),
		new Card("Nash, making train sounds in a bathtub.", false),
		new Card("Nella.", false),
		new Card("Nella's cleavage Altoids.", false),
		new Card("Not reading the FAQ.", false),
		new Card("Obelisk Blue Linkara.", false),
		new Card("Paw.", false),
		new Card("Paw's soul patch.", false),
		new Card("Penis whiskers.", false),
		new Card("Playing TGWTG Cards Against Humanity at stupid o'clock.", false),
		new Card("Pol Pot pies.", false),
		new Card("Rachel Tietz, trying to Kill the Nostalgia Critic.", false),
		new Card("Ripping off part of your penis.", false),
		new Card("ROCKET BOOTS!", false),
		new Card("ROCKET PUNCH!", false),
		new Card("Sad Panda's lanky, manly chest.", false),
		new Card("Sage's ", false),
		new Card("Sean.", false),
		new Card("Sex, violence, and Daffy Duck screaming.", false),
		new Card("Shouting ", false),
		new Card("Smarty.", false),
		new Card("Smarty's special bag of AIDS.", false),
		new Card("Snowflame's cocaine flavored popsicles.", false),
		new Card("Snowflame's fuzzy slippers.", false),
		new Card("Stealing money off dead wolves.", false),
		new Card("Tara's tramautic childhood stories.", false),
		new Card("That Dude In The Suede.", false),
		new Card("The Adventures of Horsemeat and the Placenta #1.", false),
		new Card("The Amazing Bulk.", false),
		new Card("The Channel Awesome satellite.", false),
		new Card("The Hippo Lantern Corps.", false),
		new Card("The Last Angry Geek.", false),
		new Card("The Longbox of the Damned.", false),
		new Card("The Nostalgia Ranger.", false),
		new Card("The Rap Critic.", false),
		new Card("The thick, muscular arms of ChaosD1.", false),
		new Card("The Uncanny Valley.", false),
		new Card("The Wal-Mart.", false),
		new Card("Todd in the Shadows.", false),
		new Card("Todd trolling Chris Brown on Twitter.", false),
		new Card("Tommy Wiseau.", false),
		new Card("Turtle.", false),
		new Card("Using a frontloader to steal deodorant.", false),
		new Card("Using donation money for weed.", false),
		new Card("Vangelus", false),
		new Card("Ven's voice, a gift from the fairies.", false),
		new Card("Zeo Linkara.", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] That Guy With The Glasses";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "TGWTG";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}