package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckAdminPicks extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("What is the next great Kickstarter project?", true),
		new Card("Praise ____!", true),
		new Card("____ for president!", true),
		new Card("Cunnilungus and psychiatry brought us to ____.", true),
		new Card("____ is the only thing that matters.", true),
		new Card("I'm an expert on ____.", true),
		new Card("What can you always find in between the couch cushions?", true),
		new Card("Don't get mad, get ____.", true),
		new Card("Have fun, don't be ____.", true),
		new Card("It's the end of ____ as we know it.", true),
		new Card("____ is my worst habit.", true),
		new Card("Everything's better with ____.", true),
		new Card("What would you taste like?", true),
		new Card("What have you accomplished today?", true),
		new Card("What made you happy today?", true),
		new Card("Why are you frothing with rage?", true),
		new Card("What mildy annoyed you today?", true),
		new Card("We'll always have ____.", true),
		new Card("____ uses ____. It is SUPER EFFECTIVE!", true),
		new Card("Let's all rock out to the sounds of ____.", true),
		new Card("Take ____, it will last longer.", true),
		new Card("A wild ____ appeared! It used ____!", true),
		new Card("If life gives you ____, make ____.", true),
		new Card("Who needs a bidet when you have ____?", true),
		new Card("Kill it with ____!", true),
		new Card("My ____ is too big!", true),
		new Card("Best drink ever: One part ____, three parts ____, and a splash of ____.", true),
		new Card("____ makes me uncomfortable.", true),
		new Card("Stop, drop, and ____.", true),
		new Card("Think before you ____.", true),
		new Card("____ is the name of my ____ cover band.", true),
		new Card("Alcoholic games of Clue&reg; lead to ____.", true),
		new Card("After I saw ____, I needed ____.", true),
		new Card("There's ____ in my soup.", true),
		new Card("____ sounds like a great alternative rock band.", true),
		new Card("____. Everything else is uncivilized.", true),
		new Card("Best game of 2013? ____, of course.", true),
		new Card("How do you get your dog to stop humping your leg?", true),
		new Card("Oh god, I can't believe we ate ____ at PAX.", true),
		new Card("Only in Korea can you see ____.", true),
		new Card("____? It's a DLC item.", true),
		new Card("The Holy Trinity: ____, ____, and ____!", true),
		new Card("My life for ____!", true),
		new Card("Who let the dogs out?", true),
		new Card("In his next movie, Will Smith saves the world from ____.", true),
		new Card("When North Korea gets ____, it will be the end of the world.", true),
		new Card("Plan a three course meal.", true),
		new Card("Tastes like ____.", true),
		new Card("____ and ____ are the new hot couple.", true),
		new Card("What will Xyzzy take over the world with?", true),
		new Card("Welcome to my secret lair on ____.", true),
		new Card("Dustin Browder demands more ____ in StarCraft&reg;.", true),
		new Card("I write slash fanfiction pairing ____ with ____.", true),
		new Card("Ladies and gentlemen, I give you ____... COVERED IN BEES!!!", true),
		new Card("When I was a kid, all we had in Lunchables were three ____ and ____.", true),
		new Card("On its last dying breath, ____ sent out a cry for help. A bunch of ____ heard the cry.", true),
		new Card("At first I couldn't understand ____, but now it's my biggest kink.", true),
		new Card("Long story short, I ended up with ____ in my ass.", true),
		new Card("Who knew I'd be able to make a living off of ____?", true),
		new Card("It's difficult to explain to friends and family why I know so much about ____.", true),
		new Card("I can't believe I spent most of my paycheck on ____.", true),
		new Card("Hey guys, check out my ____ montage!", true),
		new Card("____! You know, for kids.", true),
		new Card("I watch movies just to see if I can find a Big Lipped ____ Moment.", true),
		new Card("No one wants to see your ____.", true),
		new Card("OH MY GOD THIS IS THE GREATEST ____ I'VE EVER SEEN IN MY LIFE!", true),
		new Card("STOP OR I WILL ____.", true),
		new Card("What doesn't work that way?", true),
		new Card("What the fuck is wrong with you?", true),
		new Card("____ is camping my lane.", true),
		new Card("Vegeta, what does the scouter say?", true),
		new Card("Who the hell do you think I am?!", true),
		new Card("On the next episode of Dragon Ball Z, Goku has a fierce battle with ____.", true),
		new Card("So wait, ____ was actually ____? Wow, I didn't see that one coming!", true),
		new Card("Real men watch ____.", true),
		new Card("Whenever I'm splashed with cold water, I turn into ____.", true),
		new Card("No matter how you look at it, ultimately ____ is responsible for ____.", true),
		new Card("There are guilty pleasures. And then there's ____.", true),
		new Card("When it comes to Japanese cuisine, there's simply nothing better than ____.", true),
		new Card("Just announced: The brand new anime adaptation of ____, starring ____ as the voice of ____.", true),
		new Card("____. Goddammit, Japan.", true),
		new Card("I have never in my life laughed harder than the first time I watched ____.", true),
		new Card("Digimon! Digivolve to: ____-mon!", true),
		new Card("People die when they are ____.", true),
		new Card("Okay, I'll admit it. I would totally go gay for ____.", true),
		new Card("Truly and without question, ____ is the manliest of all men.", true),
		new Card("WANTED: $50,000,000,000 reward for the apprehension of____.", true),
		new Card("The government of Japan recently passed a law that effectively forbids all forms of ____.", true),
		new Card("Of my entire collection, my most prized possession is ____.", true),
		new Card("I'M-A FIRIN' MAH ____!", true),
		new Card("The sad truth is, that at the edge of the universe, there is nothing but ____.", true),
		new Card("The Himalayas are filled with many perils, such as ____.", true),
		new Card("The road to success is paved with ____.", true),
		new Card("And on his farm he had ____, E-I-E-I-O!", true),
		new Card("____ is the root of all evil.", true),
		new Card("The primitive villagers were both shocked and amazed when I showed them ____.", true),
		new Card("And it is said his ghost still wanders these halls, forever searching for his lost ____.", true),
		new Card("The best part of waking up is ____ in your cup.", true),
		new Card("What do I keep hidden in the crawlspace?", true),
		new Card("Go-Go-Gadget, ____!", true),
		new Card("I finally realized I hit rock bottom when I started digging through dumpsters for ____.", true),
		new Card("And the award for the filthiest scene in an adult film goes to '5 women and ____.'", true),
		new Card("'Why Grandma', said Little Red Riding Hood, 'What big ____ you have!'", true),
		new Card("Who would have guessed that the alien invasion would be easily thwarted by ____.", true),
		new Card("With Democrats and Republicans in a dead heat, the election was snatched by ____ party.", true),
		new Card("____. That is my fetish.", true),
		new Card("All your ____ are belong to us", true),
		new Card("Sorry Mario, but ____ is in another castle.", true),
		new Card("____ is a lie.", true),
		new Card("Who's an asshole?", true),
		new Card("____ is the greatest Canadian.", true),
		new Card("If you could fuck anyone in the world, who would you choose?", true),
		new Card("What is the meaning of life?", true),
		new Card("What is the saddest thing you've ever seen?", true),
		new Card("What is the worst thing anyone could say in front of the police?", true),
		new Card("What is your favorite book?", true),
		new Card("What is your mating call?", true),
		new Card("Why are there six ____ when there are only four ____?", true),
		new Card("TotalBiscuit's top hat is actually ____. ", true),
		new Card("The Xbox One's DRM policy isn't half as bad as ____.", true),
		new Card("What will YouTube add in its next unneeded update?", true),
		new Card("The seldomly mentioned 4th little pig built his house out of ____.", true),
		new Card("Mom, I swear! Despite its name, ____ is NOT a porno!", true),
	}, responseCards = new Card[]{
		new Card("The world's tallest midget.", false),
		new Card("Four Loko.", false),
		new Card("Xyzzy playing around with gender roles.", false),
		new Card("Sonic brutally murdering Mario.", false),
		new Card("Mario brutally murdering Sonic.", false),
		new Card("The Bible.", false),
		new Card("Two midgets stacked up pretending to be one person.", false),
		new Card("Mr. Hankey the Christmas Poo.", false),
		new Card("Show me your tits!", false),
		new Card("Thanking your sex slaves.", false),
		new Card("Googly eyes on a cock.", false),
		new Card("Typing with your genitals.", false),
		new Card("Pirate hookers.", false),
		new Card("Mandatory Sex Party.", false),
		new Card("Games you can play with bricks.", false),
		new Card("Fancy tampons.", false),
		new Card("Boobs.", false),
		new Card("Moobs.", false),
		new Card("Tinychat.", false),
		new Card("THE GODDAMN BATMAN.", false),
		new Card("Swinging an axe in the air while cornholing a bear.", false),
		new Card("Fuck you, I'm a bear.", false),
		new Card("Doctor Who.", false),
		new Card("EXTERMINATE.", false),
		new Card("Bearshark.", false),
		new Card("SCIENCE!!1!", false),
		new Card("Just the tip!", false),
		new Card("Trouser snakes.", false),
		new Card("Drinking on live TV.", false),
		new Card("The Power of Greyskull.", false),
		new Card("Hello Kitty.", false),
		new Card("Tots.", false),
		new Card("Getting drunk before noon.", false),
		new Card("Clown strippers.", false),
		new Card("KERMIT FLAIL.", false),
		new Card("Premature ejaculation.", false),
		new Card("Bounty, the Quicker Picker Upper.", false),
		new Card("A spoon that is too big.", false),
		new Card("Bleeding Anuses.", false),
		new Card("Not being pregnant.", false),
		new Card("Hookers and blow.", false),
		new Card("Standing next to short people to use them as armrests.", false),
		new Card("The sound a single ThunderStix&reg; makes.", false),
		new Card("Dr. Phil.", false),
		new Card("The Columbine Shooting.", false),
		new Card("A big wet pink laser sword.", false),
		new Card("A brief moment of aptitude.", false),
		new Card("A butt egg.", false),
		new Card("A delicious baby.", false),
		new Card("A street cleaning simulator.", false),
		new Card("John Madden.", false),
		new Card("Maple syrup.", false),
		new Card("A mile-long penis.", false),
		new Card("Novelty Twitter accounts.", false),
		new Card("Olmec.", false),
		new Card("Reddit.", false),
		new Card("Sex.", false),
		new Card("South Korea.", false),
		new Card("YouTube.", false),
		new Card("Type-C Tetris music.", false),
		new Card("Hentai.", false),
		new Card("Indiana Jones.", false),
		new Card("Smooth jazz.", false),
		new Card("Soviet Russia.", false),
		new Card("Using hot sauce as lube.", false),
		new Card("Fruit Fuckers.", false),
		new Card("Beer Pong.", false),
		new Card("Rule 34.", false),
		new Card("The smallest, whitest dick.", false),
		new Card("Skullcrusher Mountain.", false),
		new Card("Mr. Fancy Pants.", false),
		new Card("TotalBiscuit's top hat.", false),
		new Card("An 8-ball.", false),
		new Card("Penn and Teller.", false),
		new Card("My mom.", false),
		new Card("My penis catching fire.", false),
		new Card("Santa Christ.", false),
		new Card("Stick figure porn.", false),
		new Card("The Angry Video Game Nerd.", false),
		new Card("The elephant in the room.", false),
		new Card("The Nostalgia Critic.", false),
		new Card("The Power Glove.", false),
		new Card("Time travel.", false),
		new Card("Your mom.", false),
		new Card("Bees!", false),
		new Card("A baseball to the nuts.", false),
		new Card("A Big Lipped Alligator Moment.", false),
		new Card("A bird fucking a horse.", false),
		new Card("A killer rabbit.", false),
		new Card("A tiny white dick.", false),
		new Card("A zombie fisherman.", false),
		new Card("An obscure reference only two people will get.", false),
		new Card("Anal tearing.", false),
		new Card("Bees. My God.", false),
		new Card("Being frozen today.", false),
		new Card("Chuck Norris.", false),
		new Card("Fuck you, I do what I want.", false),
		new Card("FUCK YOU, I'M SPIDERMAN!", false),
		new Card("Getting mauled by a mountain lion AND a grizzly bear at the same time.", false),
		new Card("Glenn Beck being torn apart by zombies.", false),
		new Card("Going full retard.", false),
		new Card("Ham?", false),
		new Card("An awkward slash fic between The Nostalgia Critic and The Angry Video Game Nerd.", false),
		new Card("The League of Legends.", false),
		new Card("A tub of Vaseline.", false),
		new Card("Sex with strangers.", false),
		new Card("PetSmart.", false),
		new Card("StarFox.", false),
		new Card("Sonic the Hedgehog.", false),
		new Card("DeviantArt.", false),
		new Card("STEAL ALL THE FARM.", false),
		new Card("PEEEEEEEEEEEEEEEENIIIISSSSSSSS.", false),
		new Card("Jumanji.", false),
		new Card("Wards.", false),
		new Card("K-Pop.", false),
		new Card("Doing Gangnam Style at a funeral.", false),
		new Card("125% Reccomended Daily Allowance of cock.", false),
		new Card("A 3am phone call.", false),
		new Card("Ezreal's hot sugary ass.", false),
		new Card("Narutards.", false),
		new Card("Dead catgirls.", false),
		new Card("Tentacle rape.", false),
		new Card("A fuck-mothering vampire.", false),
		new Card("FUNimation.", false),
		new Card("Aya Hirano being gang-banged by her entire band.", false),
		new Card("OVER 9000!!", false),
		new Card("Idiots who don't seem to realize that Avatar: The Last Airbender isn't really an anime.", false),
		new Card("Yu-Gi-Oh! The Abridged Series.", false),
		new Card("A fat middle-aged man in a Sailor Moon costume.", false),
		new Card("Sarah Fuckin' Palin.", false),
		new Card("Naruto.", false),
		new Card("Vash the Stampede.", false),
		new Card("Cowboy Bebop.", false),
		new Card("Fullmetal Alchemist.", false),
		new Card("Futanari.", false),
		new Card("Tengen Toppa Gurren Lagann.", false),
		new Card("Being eaten by a titan.", false),
		new Card("The Death Note.", false),
		new Card("A Hello Kitty! vibrator.", false),
		new Card("A mindfuck.", false),
		new Card(". . . .', ", false),
		new Card("The Hare Hare Yukai dance.", false),
		new Card("Getting your penis cut in half.", false),
		new Card("Cousin marriage.", false),
		new Card("4Kids.", false),
		new Card("Watching FLCL while tripping on acid.", false),
		new Card("Sticking your finger up her ass.", false),
		new Card("Standing outside the gates of the White House completely naked with a revolver in your hand.", false),
		new Card("Catholic priests who drink, smoke, and carry guns.", false),
		new Card("Your virgin soul.", false),
		new Card("Engrish.", false),
		new Card("A dead meme.", false),
		new Card("Twincest.", false),
		new Card("Asian cock.", false),
		new Card("Holy dildos.", false),
		new Card("Drills for hands.", false),
		new Card("Taking a seat with Chris Hansen.", false),
		new Card("The Village People.", false),
		new Card("A Cleveland steamer.", false),
		new Card("A big floppy donkey dick.", false),
		new Card("Toilet paper.", false),
		new Card("Getting off on anime porn.", false),
		new Card("The Teenage Mutant Ninja Turtles.", false),
		new Card("Mining for nose gold.", false),
		new Card("Laxatives.", false),
		new Card("Genital warts.", false),
		new Card("A dead hooker.", false),
		new Card("A skeptical sheriff.", false),
		new Card("The crushed dreams of a stripper.", false),
		new Card("Peanutbutter jelly time.", false),
		new Card("Granny panties.", false),
		new Card("A Fleshlite&trade;.", false),
		new Card("A molotov cocktail.", false),
		new Card("The end of the world.", false),
		new Card("Don Knotts.", false),
		new Card("Morbid obesity.", false),
		new Card("A MILF.", false),
		new Card("Yellow snow.", false),
		new Card("Miss. Piggy.", false),
		new Card("The town drunk.", false),
		new Card("The Fresh Prince of Bel-Air.", false),
		new Card("Talking like a pirate.", false),
		new Card("A Facebook stalker.", false),
		new Card("Bed wetting.", false),
		new Card("Nuns.", false),
		new Card("Scotch.", false),
		new Card("Realizing, too late, that there is no toilet paper left.", false),
		new Card("Illegal immigrants.", false),
		new Card("That one episode of CSI.", false),
		new Card("A giant horse cock.", false),
		new Card("A juice box.", false),
		new Card("A tree.", false),
		new Card("Lesbians.", false),
		new Card("George Costanza", false),
		new Card("The Wii U", false),
		new Card("the PS4", false),
		new Card("the NES", false),
		new Card("the SNES", false),
		new Card("the SEGA Genesis", false),
		new Card("the PSX", false),
		new Card("the duck hunt dog", false),
		new Card("Mountain Dew", false),
		new Card("Duck Hunt", false),
		new Card("Space Core.", false),
		new Card("Surprise blowjobs.", false),
		new Card("DOTA 2.", false),
		new Card("A beautiful little moment.", false),
		new Card("A couch stinking of naked people.", false),
		new Card("A pretty epic poo.", false),
		new Card("A smaller, whiter dick.", false),
		new Card("A testicle examination.", false),
		new Card("An expensive rental costume.", false),
		new Card("Fart science.", false),
		new Card("Literally going to Hell.", false),
		new Card("Pacific Rim.", false),
		new Card("Reading the manual.", false),
		new Card("Surgeon Simulator 2013.", false),
		new Card("A wet paper towel.", false),
		new Card("Minecraft.", false),
		new Card("A bag of dicks.", false),
		new Card("The Card Czar.", false),
		new Card("Lara Croft.", false),
		new Card("Being banned from /r/pyongyang.", false),
		new Card("The lost city of Atlantis.", false),
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Admin's Picks";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Admin";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}