package org.tilegames.hexicube.cah.common.decks;

import org.tilegames.hexicube.cah.common.Deck;
import org.tilegames.hexicube.cah.common.Card;

public class DeckHomestuck extends Deck
{
	private static final Card[] callCards = new Card[]{
		new Card("What is your OT3?"),
		new Card("_ makes the Homestuck fandom uncomfortable."),
		new Card("_ stays awake at night, crying over _."),
		new Card("_. It keeps happening!"),
		new Card("'Sacred leggings' was a mistranslation. The Sufferer actually died in Sacred _."),
		new Card("After throwing _ at Karkat's head, Dave made the intriguing discover that troll horns are very sensitive."),
		new Card("AG: Who needs luck when you have _?"),
		new Card("All _. All of it!"),
		new Card("Alternia's political system was based upon _."),
		new Card("Believe it or not, Kankri's biggest trigger is _."),
		new Card("Dave Strider likes _, but only ironically."),
		new Card("Equius beats up Eridan for _."),
		new Card("Feferi secretly hates _."),
		new Card("For Betty Crocker's latest ad campaign/brainwashing scheme, she is using _ as inspiration."),
		new Card("For his birthday, Dave gave John _."),
		new Card("Fuckin' _. How do they work?"),
		new Card("Gamzee not only likes using his clubs for juggling and strifing, he also uses them for____."),
		new Card("Getting a friend to read Homestuck is like _."),
		new Card("How do I live without _?"),
		new Card("Hussie died on his quest bed and rose as the fully realized _ of _."),
		new Card("Hussie unintentionally revealed that Homestuck will end with _ and _ consummating their relationship at last."),
		new Card("I am _. It's me."),
		new Card("I finally became Tumblr famous when I released a gifset of _."),
		new Card("I just found _ in my closet it is like fucking christmas up in here."),
		new Card("I warned you about _, bro! I told you, dog!"),
		new Card("In the final battle, John distracts Lord English by showing him _."),
		new Card("It's hard, being _. It's hard and no one understands."),
		new Card("John is a good boy. And he loves _."),
		new Card("John may not be a homosexual, but he has a serious thing for _."),
		new Card("Kanaya reached into her dead lusus's stomach and retrieved _."),
		new Card("Kanaya tells Karkat about _ to cheer him up."),
		new Card("Karkat gave our universe _."),
		new Card("Latula and Porrin have decided to teach Kankri about the wonders of _."),
		new Card("Little did they know, the key to defeating Lord English was actually _."),
		new Card("Little known fact: Kurloz's stitching is actually made out of _."),
		new Card("Nanna baked a cake for John to commemorate _."),
		new Card("Nepeta only likes Karkat for his _."),
		new Card("Nepeta's secret OTP is _ with _."),
		new Card("The next thing Hussie will turn into a sex joke will be _."),
		new Card("Nobody was surprised to find _ under Jade's skirt. The surprise was she used it for/on _."),
		new Card("The only way to beat Vriska in an eating contest is to put _ on the table."),
		new Card("Porrim made Kankri a sweater to cover his _."),
		new Card("Problem Sleuth had a hard time investigating _."),
		new Card("The real reason Terezi stabbed Vriska was to punish her for _."),
		new Card("Rose was rather disgusted when she started reading about _."),
		new Card("The secret way to achieve God Tier is to die on top of _."),
		new Card("Terezi can top anyone except _."),
		new Card("The thing that made Kankri break his vow of celibacy was _."),
		new Card("Turns out, pre-entry prototyping with _ was not the best idea."),
		new Card("Vriska killed Spidermom with _."),
		new Card("Vriska roleplays _ with Terezi as _."),
		new Card("Vriska's greatest regret is _."),
		new Card("Wear  _. Be _."),
		new Card("What did Jake get Dirk for his birthday?"),
		new Card("What is the worst thing that Terezi ever licked?"),
		new Card("What makes your kokoro go "),
		new Card("What's in the box, Jack?"),
		new Card("When a bucket is unavailable, trolls with use _."),
		new Card("When Dave received _ from his Bro for his 9th birthday, be felt a little warm inside."),
		new Card("The hole in Kanaya's stomach is so large, she can fit _ in it."),
		new Card("where doing it man. where MAKING _ HAPEN!"),
		new Card("Your name is JOHN EGBERT and boy do you love _!"),
		new Card("_. On the roof. Now."),
		new Card("_ totally makes me question my sexuality."),
		new Card("Whenever I see _ on MSPARP, I disconnect immediately."),
		new Card("Calliborn wants you to draw pornography of _."),
		new Card("Everybody out of the god damn way. You've got a heart full of _, a soul full of _, and a body full of _.")
	}, responseCards = new Card[]{
		new Card("... . .-. . -. .. - -.—  (Serenity)"),
		new Card("Rails with pails."),
		new Card("Apple Juice.', "),
		new Card("The 7th Gate."),
		new Card("Accidentally touching Gamze's enormous codpiece."),
		new Card("An acrobatic fucking pirouette."),
		new Card("Alternian fine art."),
		new Card("Alternian rainbow-drinker romance novels."),
		new Card("Andrew Hussie."),
		new Card("Andrew Hussie's lips."),
		new Card("The animes."),
		new Card("Anonymous Soporifics Support."),
		new Card("Apple Juice."),
		new Card("Aradia Bot."),
		new Card("Aradia Megido."),
		new Card("Aradia's charred, rotting corpse."),
		new Card("Aranea Serket."),
		new Card("Aranea's exposition stand."),
		new Card("Arguing over troll sexuality."),
		new Card("ARquiusprite's muscles."),
		new Card("Arthour the lusus."),
		new Card("AVATAR."),
		new Card("Baby Dave."),
		new Card("Bard Quest."),
		new Card("Bec Noir."),
		new Card("Becoming Tumblr famous."),
		new Card("Being fuck deep in meowcats."),
		new Card("Being in a relationship with a non-Homestuck."),
		new Card("Being locked in a Prospitian prison."),
		new Card("Being the other guy."),
		new Card("BETTY FUCKING CROCKER."),
		new Card("Binge reading every fanfiction for a pairing and then hating yourself a little bit."),
		new Card("BL1ND JUST1C3."),
		new Card("Blackrom orgies."),
		new Card("Bro and Dave banging while Rose watches."),
		new Card("Bro."),
		new Card("Bro's rapping ventriloquism act."),
		new Card("Bro's death."),
		new Card("BUCKETS."),
		new Card("A bull penis cane."),
		new Card("Butler Island."),
		new Card("C4NDY R3D BLOOD &gt;:]"),
		new Card("Caledscratch."),
		new Card("Caliborn."),
		new Card("Caliginous speed dating."),
		new Card("Calliope."),
		new Card("Can Town."),
		new Card("Cards Against Alternia."),
		new Card("Carlos Maraka."),
		new Card("Casey."),
		new Card("Centaur milk."),
		new Card("Charging down halls, shouting profanities and being silly."),
		new Card("Cherub m-preg."),
		new Card("Cherub mating rituals."),
		new Card("Chest of WHIMSY."),
		new Card("A chip in your heart that forces you to love."),
		new Card("Cliched JohnKat fanfiction."),
		new Card("Cod Palace."),
		new Card("Cod Tier Gamzee."),
		new Card("Communism!"),
		new Card("The Condesce's crotch."),
		new Card("The Condesce's selfies."),
		new Card("Constantly breaking Hussie's copyright."),
		new Card("Cosplay sex."),
		new Card("Cosplayers who do photo shoots in bondage (God bless them)."),
		new Card("Cosplayers who don't seal their paint."),
		new Card("Crabdad."),
		new Card("Creative uses for Aradia's whip."),
		new Card("Cronus Ampora."),
		new Card("Dad Egbert/Dad Crocker."),
		new Card("Dad's pipe."),
		new Card("Dad's fedora."),
		new Card("Damara Megido wearing white at her wedding."),
		new Card("Damara Megido."),
		new Card("Damara Megido's existence."),
		new Card("Dante Basco."),
		new Card("Dating exclusively within the fandom."),
		new Card("Dave Strider."),
		new Card("Dave's throbbing beef truncheon."),
		new Card("A dead Ms. Paint."),
		new Card("Destroying clocks."),
		new Card("Developing a deep fear of the sound of clown horns after becoming a Homestuck."),
		new Card("The Dildo of Oglogoth."),
		new Card("Dirk Strider."),
		new Card("Dirk's self-insert MLP fan character."),
		new Card("The Disciple."),
		new Card("Discovering Sollux is red-blue colorblind."),
		new Card("Doc Scratch."),
		new Card("The Dolorosa."),
		new Card("A dominant Kankri."),
		new Card("Drawing pornography for Caliborn."),
		new Card("The E%ecutor/Expatri8 Darkleer."),
		new Card("Elf tears."),
		new Card("Equius Zahhak."),
		new Card("Equius's choice ass."),
		new Card("Equius's copy of 'Fifty Shades of Neigh.'"),
		new Card("Equius's towel."),
		new Card("Equius's used towel pile."),
		new Card("Eridan Ampora."),
		new Card("Eridan crying after pailing Vriska for the first time."),
		new Card("Eridan stripping to make rent."),
		new Card("Eridan's cape."),
		new Card("Eridan's empty quadrants."),
		new Card("Eridan's lowwer half."),
		new Card("Eridan's upper half."),
		new Card("The Exiles."),
		new Card("Fat Vriska."),
		new Card("Faygo."),
		new Card("Feferi Peixes."),
		new Card("The Felt."),
		new Card("Fiduspawn."),
		new Card("Fifty fucking Nepetas."),
		new Card("Filling all of your quadrants."),
		new Card("Finding grey paint on your bathroom door three weeks after the last meetup."),
		new Card("A five minute video of Cronus giving Kankri a blowjob."),
		new Card("Flighty broads."),
		new Card("Flipping the fuck out."),
		new Card("Game Bro Magazine."),
		new Card("Gamzee Makara."),
		new Card("Gamzee's clown horns."),
		new Card("gAmZeE'S pOtIoNs: 420 bOoNbUcKs."),
		new Card("Geromy."),
		new Card("Gl'bgolyb. AKA Feferi's fucking lusus."),
		new Card("The glory that is BroJohn."),
		new Card("Going to the bark side."),
		new Card("The Grand Highblood."),
		new Card("Grandpa Harley/Grandma English."),
		new Card("The Great Hiatus of 2013."),
		new Card("The green sun."),
		new Card("Grimbark Jade."),
		new Card("Groincobblers."),
		new Card("Gross misinterpretations of your favorite character."),
		new Card("The guy who fingered an Ampora."),
		new Card("The Handmaid."),
		new Card("Hateclown on the side."),
		new Card("Having STRONG surprise buttsex."),
		new Card("Hellmurder Island."),
		new Card("The hemospectrum."),
		new Card("Hemostuck."),
		new Card("Her Imperious Condescenscion."),
		new Card("Her Imperious Condescension's royal butt-plug collection."),
		new Card("The Hilarocaust."),
		new Card("Homesmut Voices."),
		new Card("The Homestuck drinking game (do a shot every time someone dies!)"),
		new Card("Homestuck stealing all the fans from Hetalia and then subsequently watching all its fans leave for OFF and Danganronpa."),
		new Card("Homestuck."),
		new Card("Homosuck."),
		new Card("HONK HONK, MOTHER FUCKER."),
		new Card("Horsearoni."),
		new Card("Horuss Zahhak."),
		new Card("Hunk Rump Magazine."),
		new Card("Hussie constantly breaking copyright and then telling his fans to not break his copyright."),
		new Card("Hussie constantly breaking copyright."),
		new Card("Hussie jacking it to our tears of anguish."),
		new Card("The Insane Clown Posse."),
		new Card("Jade Harley."),
		new Card("Jade's dog penis and knot."),
		new Card("Jailbreak."),
		new Card("Jake English."),
		new Card("Jake English's assless chaps."),
		new Card("Jake English's choice ass."),
		new Card("Jake English's manhood."),
		new Card("Jane Crocker."),
		new Card("John Egbert."),
		new Card("John's Prankster's Gambit."),
		new Card("Just KNOWING that Slick is going to stab Ms. Paint."),
		new Card("Kanaya destroying Cantown."),
		new Card("Kanaya Maryam."),
		new Card("Kanaya's ashen promiscuity."),
		new Card("Kanaya's chainsaw."),
		new Card("Kankri Vantas."),
		new Card("Karkat actually topping, for once."),
		new Card("Karkat and Jade's adorable little of mpreg puppies."),
		new Card("Karkat dying of a burst blood vessel mid-rant."),
		new Card("Karkat going through puberty before every other troll and being, like, nine feet tall."),
		new Card("Karkat Tantrum Bingo."),
		new Card("Karkat Vantas."),
		new Card("Karkat's ragegasm."),
		new Card("Kawaii Yaoi."),
		new Card("Kurloz Makara."),
		new Card("Lame bucket jokes."),
		new Card("Latula Pyrope."),
		new Card("Laying back and thinking of Alternia."),
		new Card("Leprechaun m-preg."),
		new Card("Liberty. Reason. Justice. Civility. Edification. Perfection. MAIL."),
		new Card("Lil' Cal's dead eyes."),
		new Card("Lil' Cal."),
		new Card("Lil' Cal's raging boner."),
		new Card("Lil' Hal."),
		new Card("Lil' Seb."),
		new Card("Little children who poop hard in their baby ass diapers."),
		new Card("The little red arm-swingy-dealy thing or whatever it is called."),
		new Card("Lord English."),
		new Card("Lord English's peg leg."),
		new Card("Lucky Charms."),
		new Card("Maid Equius."),
		new Card("Maple Hoof."),
		new Card("March Eridan."),
		new Card("The Marquise Spinneret Mindfang."),
		new Card("Masturbating while thinking of your OTP."),
		new Card("Maxing out your credit cards to buy Homestuck merchandise."),
		new Card("The Mayor."),
		new Card("Meenah Piexes."),
		new Card("The mere concept of the Olive Garden."),
		new Card("Meulin Leijon."),
		new Card("The Midnight Crew."),
		new Card("Mierfa Durgas."),
		new Card("Mierfa Durgas' troll-horn nunchakus."),
		new Card("A mighty wwizard of wwhite science."),
		new Card("Mind honey."),
		new Card("Mister Dude, Sir Brah, Dood Dude, Vitamin D, Dude Esquire."),
		new Card("Mituna Captor."),
		new Card("Mom."),
		new Card("MS Paint Adventures."),
		new Card("Murdering angels."),
		new Card("Muscle beasts."),
		new Card("My Little Hoofbeast: Moirailigence Is Magic."),
		new Card("Nektan Whelan."),
		new Card("Neophyte Redglare."),
		new Card("Nepeta Leijon."),
		new Card("Nepeta's heat cycle."),
		new Card("Nepeta's shipping chart."),
		new Card("Never being able to look at apple juice, milk, buckets, or knitting needles without feeling a little bit uncormfortable."),
		new Card("Never dating a Serket."),
		new Card("Nic Cage saying 'boner.'"),
		new Card("A Nicolas Cage body pillow."),
		new Card("Noping the fuck out of there."),
		new Card("Not shipping it."),
		new Card("Only cosplaying male characters when you get pregnant."),
		new Card("The Orphaner Dualscar."),
		new Card("Overtaking entire conventions."),
		new Card("A painting of a horse attacking a football player."),
		new Card("PantsKat."),
		new Card("Paradox slime."),
		new Card("Petstuck."),
		new Card("PipeFan413."),
		new Card("Plush Rump Magazine."),
		new Card("Plush rump."),
		new Card("Porrim Maryam."),
		new Card("Porrim's condom stash."),
		new Card("Porrim's motherly affections."),
		new Card("Post-apocalyptic shroudwear."),
		new Card("Problem Sleuth."),
		new Card("The Psiionic."),
		new Card("A rapist cuttlefish."),
		new Card("Recuperacoon."),
		new Card("The ridiculous fact that some people communicate without luminous rear ends."),
		new Card("Rose and Kanaya snuggling."),
		new Card("Rose Lalonde."),
		new Card("Rose telling John she's a lesbian and they will never be together."),
		new Card("Rose's review of 'My Immortal.'"),
		new Card("Roxy Lalonde."),
		new Card("Rufio."),
		new Card("Rufioh Nitram."),
		new Card("Sacred leggings."),
		new Card("SBAHJ hentai doujinshi."),
		new Card("Schrödinger's Nepeta."),
		new Card("SCIENCE WAND!"),
		new Card("Seadweller dick fins."),
		new Card("Shippers."),
		new Card("Shipping it."),
		new Card("The Shipping Olympics."),
		new Card("Shipping the fuck out of something."),
		new Card("Ships ending in -cest."),
		new Card("Shitty swords."),
		new Card("Shopping with Terezi."),
		new Card("Sick fires."),
		new Card("The significant purposes, biologically speaking, of troll nipples."),
		new Card("Skipping to Act 5."),
		new Card("The slammer."),
		new Card("A slaughtered sperm whale."),
		new Card("Sleeping ten people to a room at conventions."),
		new Card("Sloppy inter-species makeouts."),
		new Card("A smuppet in Dirk's pants."),
		new Card("Smuppets."),
		new Card("Sobbing uncontrollably while reading fanfiction."),
		new Card("Sollux Captor."),
		new Card("Sollux's bifurcated bone bulge."),
		new Card("Sopor pies."),
		new Card("SORD."),
		new Card("Soul portraits."),
		new Card("Species-swap fanfics."),
		new Card("Spidermom."),
		new Card("Staying up to three AM, cleaning the grey off every surface of your hotel room in a desperate bid to not get fined."),
		new Card("Stealing Tavros's wheelchair."),
		new Card("A Strider sandwich."),
		new Card("Stridercest."),
		new Card("The Sufferer/The Signless."),
		new Card("Sugoi Yuri."),
		new Card("The Summoner."),
		new Card("The sweat-drenched, rippling muscles of several truly majestically endowed hoofbeasts."),
		new Card("sweet bro and hell jeff."),
		new Card("TAB."),
		new Card("Tavros Nitram."),
		new Card("Tavros's wheelchair."),
		new Card("Telling Sollux what happens to male bees after sex."),
		new Card("Tentabulges."),
		new Card("Tentative thank-you stabs."),
		new Card("Terezi Pyrope."),
		new Card("That dead crow with the sword through it."),
		new Card("That human vacation with the giant red chimney-ass-hole."),
		new Card("That shitty apple."),
		new Card("That wonderful feeling when you take off your binder."),
		new Card("The "),
		new Card("Toilet displacement."),
		new Card("Topping from the bottom."),
		new Card("Triggers."),
		new Card("Troll blood."),
		new Card("Troll horns."),
		new Card("Troll Will Smith."),
		new Card("Trolls misunderstanding what "),
		new Card("Tumblr spoilers."),
		new Card("Tumblr user Egberts."),
		new Card("Tumblr user Pizza."),
		new Card("Tumblr."),
		new Card("Unreal air."),
		new Card("UPD8!!!!!!!!"),
		new Card("UPS delivery woman Nepeta."),
		new Card("Viceroy Bubbles von Salamancer."),
		new Card("Vodka Mutini."),
		new Card("Vodka."),
		new Card("Vriska dying after being stabbed by Terezi."),
		new Card("Vriska Serket."),
		new Card("Vriska's SEXY sex tips for having SEXY SEX!"),
		new Card("A VrisKan waffle."),
		new Card("Warhammer of Zillyhoo."),
		new Card("What pumpkin?"),
		new Card("When your favorite character dies."),
		new Card("where MAKING THIS HAPEN"),
		new Card("Willingly filling buckets with Eridan."),
		new Card("World building!"),
		new Card("The Wrinklefucker."),
		new Card("Your 300 pound matronly freight-train."),
		new Card("Your lusus giving you 'The Talk.'"),
		new Card("Your Mary Sue fantroll."),
		new Card("Your privilege."),
		new Card("Your significant other coming home and finding you in full grey cosplay."),
		new Card("Beating the shit out of Terezi."),
		new Card("Jake English standing there like a fucking idiot."),
		new Card("Falling into a pool of lava.")
	};
	
	@Override
	public String getDeckName()
	{
		return "[C] Cards Against Homestuck";
	}
	
	@Override
	public String getShortDeckName()
	{
		return "Stuck";
	}
	
	@Override
	public boolean officialDeck()
	{
		return true;
	}
	
	@Override
	public int numCallCards()
	{
		return callCards.length;
	}
	
	@Override
	public int numResponseCards()
	{
		return responseCards.length;
	}
	
	@Override
	public Card[] getCallCards()
	{
		return callCards;
	}
	
	@Override
	public Card[] getResponseCards()
	{
		return responseCards;
	}
}